CATEGORIES = {
    "animals": [
        "Lion", "Elephant", "Giraffe", "Penguin", "Dolphin", "Tiger",
        "Panda", "Koala", "Zebra", "Cheetah", "Gorilla", "Flamingo",
        "Octopus", "Chameleon", "Red fox", "Polar bear", "Bald eagle",
        "Sea turtle", "Whale shark", "Snow leopard", "Peacock",
        "Hippopotamus", "Rhinoceros", "Kangaroo", "Sloth", "Wolf",
        "Jaguar", "Orangutan", "Orca", "Hedgehog", "Platypus",
        "Manta ray", "Lemur", "Hyena", "Lynx", "Capybara",
        "Armadillo", "Tapir", "Wolverine", "Porcupine", "Pelican",
        "Toucan", "Albatross", "Hummingbird", "Kingfisher", "Owl",
        "Parrot", "Swan", "Crane (bird)", "Iguana", "Komodo dragon",
        "Cobra", "Rattlesnake", "Axolotl", "Jellyfish", "Starfish",
        "Seahorse", "Clownfish", "Pufferfish", "Hammerhead shark",
        "Moose", "Bison", "Gazelle", "Impala", "Wildebeest",
        "Wombat", "Quokka", "Red panda", "Arctic fox", "Fennec fox",
        "Mandrill", "Bonobo", "Gibbon", "Anteater", "Pangolin",
    ],
    "people": [
        "Albert Einstein", "Marie Curie", "Leonardo da Vinci",
        "Frida Kahlo", "Nelson Mandela", "Cleopatra",
        "William Shakespeare", "Nikola Tesla", "Ada Lovelace",
        "Mahatma Gandhi", "Wolfgang Amadeus Mozart", "Charles Darwin",
        "Rosa Parks", "Aristotle", "Amelia Earhart",
        "Martin Luther King Jr.", "Isaac Newton", "Jane Austen",
        "Pablo Picasso", "Coco Chanel", "Napoleon", "Galileo Galilei",
        "Vincent van Gogh", "Queen Victoria", "Abraham Lincoln",
        "Alexander the Great", "Julius Caesar", "Genghis Khan",
        "Marco Polo", "Florence Nightingale", "Beethoven",
        "Rembrandt", "Michelangelo", "Confucius", "Socrates",
        "Plato", "Archimedes", "Tutankhamun", "Nefertiti",
        "Joan of Arc", "Elizabeth I", "Catherine the Great",
        "Copernicus", "Johannes Kepler", "James Watt",
        "Thomas Edison", "Alexander Graham Bell", "Wright brothers",
        "Harriet Tubman", "Frederick Douglass", "Simón Bolívar",
        "Che Guevara", "Winston Churchill", "Charles de Gaulle",
        "Jawaharlal Nehru", "Emmeline Pankhurst", "Marie Antoinette",
        "Sigmund Freud", "Carl Jung", "Alan Turing",
        "Rosalind Franklin", "Jane Goodall", "Stephen Hawking",
        "Salvador Dalí", "Claude Monet", "Auguste Rodin",
    ],
    "countries": [
        "Japan", "Brazil", "Egypt", "Iceland", "India", "Italy",
        "Morocco", "New Zealand", "Norway", "Peru", "South Korea",
        "Thailand", "Turkey", "Greece", "Portugal", "Mexico",
        "Kenya", "Argentina", "Vietnam", "Switzerland",
        "Cuba", "Nepal", "Ireland", "Tanzania", "Colombia",
        "Australia", "Canada", "China", "France", "Germany",
        "Indonesia", "Iran", "Iraq", "Israel", "Jamaica",
        "Jordan", "Lebanon", "Madagascar", "Malaysia", "Mongolia",
        "Myanmar", "Nigeria", "Pakistan", "Philippines", "Poland",
        "Romania", "Russia", "Saudi Arabia", "Singapore", "Spain",
        "Sri Lanka", "Sweden", "Ukraine", "United Kingdom",
        "Venezuela", "Ethiopia", "Ghana", "Senegal", "Chile",
        "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Panama",
        "Costa Rica", "Guatemala", "Honduras", "Cambodia", "Laos",
        "Bangladesh", "Uzbekistan", "Kazakhstan", "Georgia (country)",
        "Armenia", "Croatia", "Czech Republic", "Hungary", "Austria",
    ],
    "plants": [
        "Sunflower", "Venus flytrap", "Baobab", "Cherry blossom",
        "Cactus", "Lavender", "Bamboo", "Orchid", "Tulip",
        "Rose", "Lotus", "Sequoia", "Rafflesia", "Dandelion",
        "Fern", "Ivy", "Olive tree", "Willow", "Maple",
        "Oak", "Pine", "Birch", "Palm tree", "Eucalyptus",
        "Magnolia", "Jasmine", "Hibiscus", "Carnation", "Daisy",
        "Chrysanthemum", "Poppy", "Lily", "Iris (plant)",
        "Daffodil", "Hydrangea", "Wisteria", "Bougainvillea",
        "Peony", "Camellia", "Azalea", "Rhododendron",
        "Redwood", "Cedar", "Cypress", "Banyan", "Mangrove",
        "Aloe vera", "Monstera", "Pitcher plant", "Sundew",
        "Foxglove", "Bluebell", "Snowdrop", "Edelweiss",
        "Passionflower", "Bird of paradise (plant)", "Protea",
        "Amaryllis", "Begonia", "Frangipani", "Acacia",
    ],
}
