COUNTRIES = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
    "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
    "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
    "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
    "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon",
    "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile",
    "China", "Colombia", "Comoros", "Costa Rica", "Croatia",
    "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo",
    "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
    "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia (country)", "Germany",
    "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
    "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq",
    "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica",
    "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
    "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon",
    "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives",
    "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
    "Mexico", "Micronesia (country)", "Moldova", "Monaco", "Mongolia",
    "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
    "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
    "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
    "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar", "Republic of the Congo", "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
    "Samoa", "San Marino", "São Tomé and Príncipe", "Saudi Arabia", "Senegal",
    "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia",
    "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea",
    "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname",
    "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
    "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
    "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
    "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
    "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela",
    "Vietnam", "Yemen", "Zambia", "Zimbabwe",
]

CATEGORIES = {
    "animals": [
        # Mammals
        "Lion", "Elephant", "Giraffe", "Tiger", "Panda", "Koala",
        "Zebra", "Cheetah", "Gorilla", "Wolf", "Jaguar", "Orangutan",
        "Orca", "Hedgehog", "Platypus", "Lemur", "Hyena", "Lynx",
        "Capybara", "Armadillo", "Tapir", "Wolverine", "Porcupine",
        "Moose", "Bison", "Gazelle", "Impala", "Wildebeest",
        "Wombat", "Quokka", "Red panda", "Arctic fox", "Fennec fox",
        "Mandrill", "Bonobo", "Gibbon", "Anteater", "Pangolin",
        "Hippopotamus", "Rhinoceros", "Kangaroo", "Sloth",
        "Dolphin", "Polar bear", "Snow leopard", "Red fox",
        "Meerkat", "Otter", "Badger", "Beaver", "Chipmunk",
        "Raccoon", "Opossum", "Manatee", "Narwhal", "Beluga whale",
        "Humpback whale", "Blue whale", "Sperm whale", "Walrus",
        "Sea lion", "Dugong", "Okapi", "Aardvark", "Chinchilla",
        "Ferret", "Mink", "Yak", "Water buffalo", "Gnu",
        "Kudu", "Oryx", "Ibex", "Chamois", "Dik-dik",
        "Echidna", "Tasmanian devil", "Numbat", "Sugar glider",
        "Flying fox", "Fruit bat", "Vampire bat",
        # Birds
        "Flamingo", "Peacock", "Bald eagle", "Pelican", "Toucan",
        "Albatross", "Hummingbird", "Kingfisher", "Owl", "Parrot",
        "Swan", "Crane (bird)", "Penguin", "Ostrich", "Emu",
        "Cassowary", "Kiwi (bird)", "Puffin", "Robin (bird)",
        "Blue jay", "Cardinal (bird)", "Woodpecker", "Hornbill",
        "Secretary bird", "Shoebill", "Harpy eagle", "Condor",
        "Vulture", "Falcon", "Hawk", "Osprey", "Snowy owl",
        "Cockatoo", "Macaw", "Lorikeet", "Kookaburra",
        "Magpie", "Raven", "Crow", "Starling", "Swallow",
        # Reptiles & amphibians
        "Iguana", "Komodo dragon", "Cobra", "Rattlesnake", "Chameleon",
        "Sea turtle", "Axolotl", "Gecko", "Tortoise", "Crocodile",
        "Alligator", "Tuatara", "Gila monster", "Frilled-neck lizard",
        "Green tree python", "King cobra", "Black mamba", "Anaconda",
        "Poison dart frog", "Red-eyed tree frog", "Salamander", "Newt",
        # Marine life
        "Octopus", "Jellyfish", "Starfish", "Seahorse", "Clownfish",
        "Pufferfish", "Hammerhead shark", "Whale shark", "Manta ray",
        "Great white shark", "Stingray", "Moray eel", "Lionfish",
        "Nautilus", "Cuttlefish", "Sea urchin", "Lobster", "Hermit crab",
        "Giant squid", "Blue-ringed octopus", "Coral",
        # Insects & arachnids
        "Monarch butterfly", "Ladybug", "Dragonfly", "Praying mantis",
        "Atlas moth", "Firefly", "Scarab beetle", "Tarantula",
        "Scorpion", "Stick insect", "Leaf insect", "Rhinoceros beetle",
    ],
    "people": [
        # Scientists
        "Albert Einstein", "Marie Curie", "Nikola Tesla", "Charles Darwin",
        "Isaac Newton", "Galileo Galilei", "Copernicus", "Johannes Kepler",
        "Archimedes", "Ada Lovelace", "Alan Turing", "Rosalind Franklin",
        "Stephen Hawking", "Richard Feynman", "Niels Bohr", "Max Planck",
        "Michael Faraday", "Louis Pasteur", "Alexander Fleming",
        "Dmitri Mendeleev", "Carl Linnaeus", "Gregor Mendel",
        "Rachel Carson", "Barbara McClintock", "Dorothy Hodgkin",
        "Lise Meitner", "Emmy Noether", "Hypatia",
        "Carl Sagan", "Jane Goodall", "Dian Fossey",
        "Alfred Nobel", "Enrico Fermi", "Ernest Rutherford",
        "James Clerk Maxwell", "Heinrich Hertz", "Erwin Schrödinger",
        "Werner Heisenberg", "Paul Dirac", "Robert Oppenheimer",
        # Explorers & adventurers
        "Marco Polo", "Amelia Earhart", "Christopher Columbus",
        "Ferdinand Magellan", "Vasco da Gama", "James Cook",
        "Roald Amundsen", "Ernest Shackleton", "Edmund Hillary",
        "Tenzing Norgay", "Neil Armstrong", "Yuri Gagarin",
        "Valentina Tereshkova", "Ibn Battuta", "Zheng He",
        # Artists & musicians
        "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh",
        "Frida Kahlo", "Salvador Dalí", "Claude Monet",
        "Rembrandt", "Michelangelo", "Auguste Rodin", "Andy Warhol",
        "Gustav Klimt", "Edvard Munch", "Henri Matisse",
        "Wassily Kandinsky", "Jackson Pollock", "Georgia O'Keeffe",
        "Yayoi Kusama", "Banksy", "Ai Weiwei",
        "Wolfgang Amadeus Mozart", "Beethoven", "Johann Sebastian Bach",
        "Frédéric Chopin", "Franz Liszt", "Pyotr Ilyich Tchaikovsky",
        "Antonio Vivaldi", "Giuseppe Verdi", "Richard Wagner",
        "Claude Debussy", "Igor Stravinsky",
        # Writers & philosophers
        "William Shakespeare", "Jane Austen", "Leo Tolstoy",
        "Fyodor Dostoevsky", "Mark Twain", "Charles Dickens",
        "Virginia Woolf", "Franz Kafka", "Jorge Luis Borges",
        "Gabriel García Márquez", "Toni Morrison", "Maya Angelou",
        "Homer", "Dante Alighieri", "Miguel de Cervantes",
        "Aristotle", "Socrates", "Plato", "Confucius",
        "Sigmund Freud", "Carl Jung", "Friedrich Nietzsche",
        "Immanuel Kant", "René Descartes", "Jean-Paul Sartre",
        "Simone de Beauvoir",
        # Leaders & historical figures
        "Nelson Mandela", "Mahatma Gandhi", "Martin Luther King Jr.",
        "Abraham Lincoln", "Napoleon", "Julius Caesar",
        "Alexander the Great", "Genghis Khan", "Cleopatra",
        "Queen Victoria", "Elizabeth I", "Catherine the Great",
        "Joan of Arc", "Tutankhamun", "Nefertiti",
        "Rosa Parks", "Harriet Tubman", "Frederick Douglass",
        "Emmeline Pankhurst", "Florence Nightingale",
        "Simón Bolívar", "Che Guevara", "Winston Churchill",
        "Charles de Gaulle", "Jawaharlal Nehru", "Marie Antoinette",
        "Coco Chanel", "Thomas Edison", "Alexander Graham Bell",
        "Wright brothers", "James Watt", "Henry Ford",
        "Nikola Tesla", "Gutenberg",
    ],
    "countries:flags": COUNTRIES,
    "countries:shapes": COUNTRIES,
    "plants": [
        # Flowers
        "Sunflower", "Rose", "Tulip", "Orchid", "Lotus",
        "Dandelion", "Daisy", "Chrysanthemum", "Poppy", "Lily",
        "Iris (plant)", "Daffodil", "Hydrangea", "Wisteria",
        "Bougainvillea", "Peony", "Camellia", "Azalea",
        "Carnation", "Hibiscus", "Jasmine", "Magnolia",
        "Lavender", "Cherry blossom", "Passionflower",
        "Bird of paradise (plant)", "Protea", "Amaryllis",
        "Begonia", "Frangipani", "Foxglove", "Bluebell",
        "Snowdrop", "Edelweiss", "Rhododendron",
        "Marigold", "Zinnia", "Dahlia", "Gardenia", "Freesia",
        "Anemone", "Crocus", "Gladiolus", "Delphinium",
        "Lupinus", "Plumeria", "Heliconia", "Anthurium",
        "Ranunculus", "Snapdragon", "Sweet pea", "Clematis",
        "Geranium", "Petunia", "Violet (plant)",
        # Trees
        "Oak", "Pine", "Birch", "Maple", "Willow",
        "Palm tree", "Eucalyptus", "Redwood", "Sequoia",
        "Cedar", "Cypress", "Banyan", "Baobab", "Mangrove",
        "Olive tree", "Acacia", "Jacaranda", "Kapok",
        "Dragon blood tree", "Ginkgo", "Japanese maple",
        "Weeping willow", "Scots pine", "Douglas fir",
        "Giant sequoia", "Coast redwood", "Boab",
        "Joshua tree", "Monkey puzzle tree",
        # Other plants
        "Bamboo", "Fern", "Ivy", "Cactus", "Aloe vera",
        "Monstera", "Venus flytrap", "Pitcher plant", "Sundew",
        "Rafflesia", "Corpse flower", "Welwitschia",
        "Saguaro", "Agave", "Yucca", "Air plant",
        "Spanish moss", "Seagrass", "Kelp", "Sphagnum",
        "Lichen", "Liverwort", "Horsetail", "Club moss",
    ],
}
