from memi.categories import (
    albums,
    animals,
    bones,
    characters,
    countries,
    directors,
    instruments,
    monuments,
    movies,
    nature,
    paintings,
    people,
    plants,
    rivers,
    roadsigns,
    space,
    sports,
    tvshows,
    usstates,
)

CATEGORIES = {
    # Culture
    "culture:characters:all": characters.ALL,
    "culture:characters:star wars": characters.STAR_WARS,
    "culture:characters:lord of the rings": characters.LORD_OF_THE_RINGS,
    "culture:characters:harry potter": characters.HARRY_POTTER,
    "culture:characters:disney": characters.DISNEY,
    "culture:characters:marvel": characters.MARVEL,
    "culture:characters:dc": characters.DC,
    "culture:characters:anime": characters.ANIME,
    "culture:monuments": monuments.ALL,
    "culture:paintings:movements": paintings.MOVEMENTS,
    "culture:paintings:painters": paintings.PAINTERS,
    "culture:paintings:paintings": paintings.PAINTINGS,
    "culture:movies:actors": people.ACTORS,
    "culture:movies:directors": directors.ALL,
    "culture:movies:posters": movies.ALL,
    "culture:movies:scenes": movies.ALL,
    "culture:instruments": instruments.ALL,
    "culture:music:albums": albums.ALL,
    "culture:sports:olympics": sports.OLYMPICS_ALL,
    "culture:sports:fifa world cup": sports.WORLD_CUPS_ALL,
    "culture:sports:uefa euro": sports.EUROS_ALL,
    "culture:tv shows:scenes": tvshows.ALL,
    # Geography
    "geography:countries:capitals": countries.ALL,
    "geography:countries:currencies": countries.ALL,
    "geography:countries:flags": countries.ALL,
    "geography:countries:shapes": countries.ALL,
    "geography:rivers": rivers.ALL,
    "geography:road signs": roadsigns.ALL,
    "geography:us states:capitals": usstates.ALL,
    "geography:us states:flags": usstates.ALL,
    "geography:us states:shapes": usstates.ALL,
    # Humans
    "humans:bones": bones.ALL,
    "humans:people": people.ALL,
    # Nature
    "nature:all": animals.ALL + plants.ALL + nature.ALL + space.ALL,
    "nature:animals": animals.ALL,
    "nature:landscapes": nature.ALL,
    "nature:plants:all": plants.ALL,
    "nature:plants:flowers": plants.FLOWERS,
    "nature:plants:fruits & vegetables": plants.FRUITS_AND_VEGETABLES,
    "nature:plants:houseplants": plants.HOUSEPLANTS,
    "nature:plants:other": plants.OTHER,
    "nature:plants:trees": plants.TREES,
    "nature:space": space.ALL,
    # Disabled
    # "logos": logos.ALL,  # TODO: find symbol-only logos without text
}
