from memi.categories import (
    albums,
    animals,
    bones,
    brands,
    characters,
    countries,
    directors,
    instruments,
    monuments,
    movies,
    nature,
    paintings,
    people,
    plants,
    rivers,
    roadsigns,
    space,
    sports,
    tvshows,
)

CATEGORIES = {
    # Culture
    "culture:art:monuments": monuments.ALL,
    "culture:art:paintings:movements": paintings.MOVEMENTS,
    "culture:art:paintings:painters": paintings.PAINTERS,
    "culture:art:paintings:paintings": paintings.PAINTINGS,
    "culture:cinema:characters:all": characters.ALL,
    "culture:cinema:characters:star wars": characters.STAR_WARS,
    "culture:cinema:characters:lord of the rings": characters.LORD_OF_THE_RINGS,
    "culture:cinema:characters:harry potter": characters.HARRY_POTTER,
    "culture:cinema:characters:disney": characters.DISNEY,
    "culture:cinema:characters:marvel": characters.MARVEL,
    "culture:cinema:characters:dc": characters.DC,
    "culture:cinema:characters:anime": characters.ANIME,
    "culture:cinema:actors": people.ACTORS,
    "culture:cinema:directors": directors.ALL,
    "culture:cinema:movies:posters": movies.ALL,
    "culture:cinema:movies:scenes": movies.ALL,
    "culture:cinema:tv shows:scenes": tvshows.ALL,
    "culture:music:albums": albums.ALL,
    "culture:music:instruments": instruments.ALL,
    "culture:sports:sports": sports.SPORTS_ALL,
    "culture:sports:olympics:all": sports.OLYMPICS_ALL,
    "culture:sports:olympics:summer": sports.SUMMER_OLYMPICS_ALL,
    "culture:sports:olympics:winter": sports.WINTER_OLYMPICS_ALL,
    "culture:sports:fifa world cup": sports.WORLD_CUPS_ALL,
    "culture:sports:uefa euro": sports.EUROS_ALL,
    "culture:sports:football clubs": sports.FOOTBALL_CLUBS_ALL,
    "culture:brands:all": brands.ALL_NAMES,
    "culture:brands:tech": brands.TECH_NAMES,
    "culture:brands:automotive": brands.AUTOMOTIVE_NAMES,
    "culture:brands:fashion": brands.FASHION_NAMES,
    "culture:brands:food & drink": brands.FOOD_AND_DRINK_NAMES,
    "culture:brands:airlines": brands.AIRLINES_NAMES,
    # Geography
    "geography:countries:capitals": countries.ALL,
    "geography:countries:currencies": countries.ALL,
    "geography:countries:flags": countries.ALL,
    "geography:countries:shapes": countries.ALL,
    "geography:rivers": rivers.ALL,
    "geography:road signs": roadsigns.ALL,
    # Humans
    "humans:bones": bones.ALL,
    "humans:people": people.ALL,
    # Nature
    "nature:all": animals.ALL + plants.ALL + nature.ALL + space.ALL,
    "nature:animals": animals.ALL,
    "nature:landscapes": nature.ALL,
    "nature:plants:all": plants.ALL,
    "nature:plants:flowers": plants.FLOWERS,
    "nature:plants:fruits & vegetables": plants.FRUITS_AND_VEGETABLES,
    "nature:plants:houseplants": plants.HOUSEPLANTS,
    "nature:plants:other": plants.OTHER,
    "nature:plants:trees": plants.TREES,
    "nature:space:all": space.ALL,
    "nature:space:solar system": space.SOLAR_SYSTEM,
    "nature:space:deep space": space.DEEP_SPACE,
    # Disabled
    # "logos": logos.ALL,  # TODO: find symbol-only logos without text
}
