"""Album covers from various genres and regions."""

# (display_name, artist, year)
ALBUMS = [
    # Rock
    ("Abbey Road", "The Beatles", "1969"),
    ("The Dark Side of the Moon", "Pink Floyd", "1973"),
    ("Led Zeppelin IV", "Led Zeppelin", "1971"),
    ("Nevermind", "Nirvana", "1991"),
    ("OK Computer", "Radiohead", "1997"),
    ("Rumours", "Fleetwood Mac", "1977"),
    ("Back in Black", "AC/DC", "1980"),
    ("The Wall", "Pink Floyd", "1979"),
    ("Born to Run", "Bruce Springsteen", "1975"),
    ("Who's Next", "The Who", "1971"),
    ("Sticky Fingers", "The Rolling Stones", "1971"),
    ("Appetite for Destruction", "Guns N' Roses", "1987"),
    ("The Joshua Tree", "U2", "1987"),
    ("London Calling", "The Clash", "1979"),
    ("Paranoid", "Black Sabbath", "1970"),
    ("In the Court of the Crimson King", "King Crimson", "1969"),
    ("Wish You Were Here", "Pink Floyd", "1975"),
    ("Disintegration", "The Cure", "1989"),
    ("Unknown Pleasures", "Joy Division", "1979"),
    ("Loveless", "My Bloody Valentine", "1991"),
    ("Is This It", "The Strokes", "2001"),
    ("In Rainbows", "Radiohead", "2007"),
    ("The Bends", "Radiohead", "1995"),
    # Pop
    ("Thriller", "Michael Jackson", "1982"),
    ("Purple Rain", "Prince", "1984"),
    ("Like a Prayer", "Madonna", "1989"),
    ("Ray of Light", "Madonna", "1998"),
    ("Lemonade", "Beyoncé", "2016"),
    ("1989", "Taylor Swift", "2014"),
    ("Future Nostalgia", "Dua Lipa", "2020"),
    ("Born This Way", "Lady Gaga", "2011"),
    ("21", "Adele", "2011"),
    ("Emotion", "Carly Rae Jepsen", "2015"),
    ("After Hours", "The Weeknd", "2020"),
    ("ANTI", "Rihanna", "2016"),
    ("folklore", "Taylor Swift", "2020"),
    ("Teenage Dream", "Katy Perry", "2010"),
    ("Channel Orange", "Frank Ocean", "2012"),
    ("Blonde", "Frank Ocean", "2016"),
    # Hip hop / R&B
    ("Illmatic", "Nas", "1994"),
    ("The Miseducation of Lauryn Hill", "Lauryn Hill", "1998"),
    ("Ready to Die", "The Notorious B.I.G.", "1994"),
    ("My Beautiful Dark Twisted Fantasy", "Kanye West", "2010"),
    ("To Pimp a Butterfly", "Kendrick Lamar", "2015"),
    ("Enter the Wu-Tang (36 Chambers)", "Wu-Tang Clan", "1993"),
    ("Stankonia", "OutKast", "2000"),
    ("The Blueprint", "Jay-Z", "2001"),
    ("good kid, m.A.A.d city", "Kendrick Lamar", "2012"),
    ("Madvillainy", "Madvillain", "2004"),
    ("The Low End Theory", "A Tribe Called Quest", "1991"),
    ("DAMN.", "Kendrick Lamar", "2017"),
    ("Igor", "Tyler, the Creator", "2019"),
    ("SOS", "SZA", "2022"),
    # Electronic / Dance
    ("Homework", "Daft Punk", "1997"),
    ("Discovery", "Daft Punk", "2001"),
    ("Random Access Memories", "Daft Punk", "2013"),
    ("Selected Ambient Works 85–92", "Aphex Twin", "1992"),
    ("Music Has the Right to Children", "Boards of Canada", "1998"),
    ("Cross", "Justice", "2007"),
    ("In Colour", "Jamie xx", "2015"),
    ("Mezzanine", "Massive Attack", "1998"),
    ("Blue Lines", "Massive Attack", "1991"),
    ("Dummy", "Portishead", "1994"),
    # Metal
    ("Master of Puppets", "Metallica", "1986"),
    ("Reign in Blood", "Slayer", "1986"),
    ("The Number of the Beast", "Iron Maiden", "1982"),
    ("Rust in Peace", "Megadeth", "1990"),
    ("Toxicity", "System of a Down", "2001"),
    ("Lateralus", "Tool", "2001"),
    # Jazz
    ("Kind of Blue", "Miles Davis", "1959"),
    ("A Love Supreme", "John Coltrane", "1965"),
    ("Head Hunters", "Herbie Hancock", "1973"),
    ("The Black Saint and the Sinner Lady", "Charles Mingus", "1963"),
    ("Mingus Ah Um", "Charles Mingus", "1959"),
    ("Blue Train", "John Coltrane", "1958"),
    # Soul / Funk
    ("What's Going On", "Marvin Gaye", "1971"),
    ("Songs in the Key of Life", "Stevie Wonder", "1976"),
    ("Innervisions", "Stevie Wonder", "1973"),
    ("Superfly", "Curtis Mayfield", "1972"),
    ("There's a Riot Goin' On", "Sly and the Family Stone", "1971"),
    ("Sign 'o' the Times", "Prince", "1987"),
    # Country / Folk
    ("Blue", "Joni Mitchell", "1971"),
    ("Graceland", "Paul Simon", "1986"),
    ("Johnny Cash at Folsom Prison", "Johnny Cash", "1968"),
    ("Harvest", "Neil Young", "1972"),
    ("For Emma, Forever Ago", "Bon Iver", "2007"),
    # Reggae
    ("Exodus", "Bob Marley and the Wailers", "1977"),
    ("Catch a Fire", "Bob Marley and the Wailers", "1973"),
    # Latin
    ("Buena Vista Social Club", "Buena Vista Social Club", "1997"),
    ("Re", "Café Tacvba", "1994"),
    ("Tropicália: ou Panis et Circensis", "Various Artists", "1968"),
    ("Clube da Esquina", "Milton Nascimento and Lô Borges", "1972"),
    ("Construcción", "Jorge Drexler", "2004"),
    # African
    ("Graceland", "Paul Simon", "1986"),
    ("Zombie", "Fela Kuti", "1977"),
    ("Talking Timbuktu", "Ali Farka Touré and Ry Cooder", "1994"),
    # Asian
    ("Fantôme", "Utada Hikaru", "2016"),
    ("Yellow Submarine Soundtrack", "The Beatles", "1999"),
    # Alternative / Indie
    ("Funeral", "Arcade Fire", "2004"),
    ("The Suburbs", "Arcade Fire", "2010"),
    ("Kid A", "Radiohead", "2000"),
    ("Yankee Hotel Foxtrot", "Wilco", "2002"),
    ("Currents", "Tame Impala", "2015"),
    ("Lonerism", "Tame Impala", "2012"),
    ("AM", "Arctic Monkeys", "2013"),
    ("House of Balloons", "The Weeknd", "2011"),
    ("Vespertine", "Björk", "2001"),
    ("Homogenic", "Björk", "1997"),
    ("Carrie & Lowell", "Sufjan Stevens", "2015"),
    # Punk / Post-punk
    ("Never Mind the Bollocks, Here's the Sex Pistols", "Sex Pistols", "1977"),
    ("Remain in Light", "Talking Heads", "1980"),
    ("Doolittle", "Pixies", "1989"),
    ("Damaged", "Black Flag", "1981"),
    # Grunge
    ("Ten", "Pearl Jam", "1991"),
    ("Superunknown", "Soundgarden", "1994"),
    ("Dirt", "Alice in Chains", "1992"),
    # 2020s
    ("Midnights", "Taylor Swift", "2022"),
    ("Renaissance", "Beyoncé", "2022"),
    ("Mr. Morale & The Big Steppers", "Kendrick Lamar", "2022"),
    ("Harry's House", "Harry Styles", "2022"),
    ("Cowboy Carter", "Beyoncé", "2024"),
    ("Brat", "Charli XCX", "2024"),
    ("GNX", "Kendrick Lamar", "2024"),
    ("The Rise and Fall of a Midwest Princess", "Chappell Roan", "2023"),
    ("Hit Me Hard and Soft", "Billie Eilish", "2024"),
]

ALL = [a[0] for a in ALBUMS]
ARTISTS = {a[0]: a[1] for a in ALBUMS}
YEARS = {a[0]: a[2] for a in ALBUMS}

# For MusicBrainz search: need artist + album name
SEARCH_TERMS = {a[0]: (a[1], a[0]) for a in ALBUMS}
