from memi.categories.dinosaurs import ALL as DINOSAURS

MAMMALS = [
    # Big cats
    "Black-footed cat",
    "Bobcat",
    "Caracal",
    "Cheetah",
    "Clouded leopard",
    "Cougar",
    "Eurasian lynx",
    "Fishing cat",
    "Iberian lynx",
    "Jaguar",
    "Jaguarundi",
    "Leopard",
    "Lion",
    "Lynx",
    "Margay",
    "Ocelot",
    "Pallas's cat",
    "Sand cat",
    "Serval",
    "Snow leopard",
    "Sunda clouded leopard",
    "Tiger",
    # Canines
    "African wild dog",
    "Arctic fox",
    "Bat-eared fox",
    "Bush dog",
    "Coyote",
    "Dhole",
    "Dingo",
    "Fennec fox",
    "Gray fox",
    "Jackal",
    "Kit fox",
    "Maned wolf",
    "Raccoon dog",
    "Red fox",
    "Wolf",
    # Bears
    "American black bear",
    "Asian black bear",
    "Brown bear",
    "Giant panda",
    "Polar bear",
    "Red panda",
    "Sloth bear",
    "Spectacled bear",
    "Sun bear",
    # Primates
    "Aye-aye",
    "Baboon",
    "Bonobo",
    "Capuchin monkey",
    "Chimpanzee",
    "Colobus monkey",
    "Galago",
    "Gelada",
    "Gibbon",
    "Golden lion tamarin",
    "Gorilla",
    "Howler monkey",
    "Indri",
    "Japanese macaque",
    "Lemur",
    "Mandrill",
    "Orangutan",
    "Proboscis monkey",
    "Ring-tailed lemur",
    "Sifaka",
    "Slow loris",
    "Spider monkey",
    "Tarsier",
    "Vervet monkey",
    # Marine mammals
    "Beluga whale",
    "Blue whale",
    "Bowhead whale",
    "Dolphin",
    "Dugong",
    "Elephant seal",
    "Fin whale",
    "Fur seal",
    "Gray whale",
    "Harbor seal",
    "Humpback whale",
    "Leopard seal",
    "Manatee",
    "Minke whale",
    "Narwhal",
    "Orca",
    "Pilot whale",
    "Right whale",
    "Sea lion",
    "Sea otter",
    "Sei whale",
    "Sperm whale",
    "Walrus",
    # Elephants & large herbivores
    "African elephant",
    "Asian elephant",
    "Bison",
    "Black rhinoceros",
    "Caribou",
    "Elk",
    "Giraffe",
    "Hippopotamus",
    "Indian rhinoceros",
    "Javan rhinoceros",
    "Moose",
    "Musk ox",
    "Okapi",
    "Sumatran rhinoceros",
    "Tapir",
    "Water buffalo",
    "White rhinoceros",
    "Yak",
    "Zebra",
    # Antelopes & deer
    "Axis deer",
    "Bongo (antelope)",
    "Bushbuck",
    "Chamois",
    "Dik-dik",
    "Eland",
    "Fallow deer",
    "Gazelle",
    "Gerenuk",
    "Hartebeest",
    "Ibex",
    "Impala",
    "Kudu",
    "Markhor",
    "Mouflon",
    "Muntjac",
    "Nyala",
    "Oryx",
    "Pronghorn",
    "Pudu",
    "Red deer",
    "Roe deer",
    "Sable antelope",
    "Saiga antelope",
    "Sambar deer",
    "Springbok",
    "Topi",
    "Waterbuck",
    "Wildebeest",
    # Small mammals
    "Agouti",
    "Badger",
    "Beaver",
    "Binturong",
    "Capybara",
    "Chinchilla",
    "Chipmunk",
    "Civet",
    "Coypu",
    "Dormouse",
    "Ferret",
    "Flying squirrel",
    "Genet",
    "Groundhog",
    "Hedgehog",
    "Mara",
    "Marmot",
    "Meerkat",
    "Mink",
    "Mongoose",
    "Opossum",
    "Otter",
    "Pika",
    "Pine marten",
    "Porcupine",
    "Prairie dog",
    "Raccoon",
    "Red squirrel",
    "Skunk",
    "Stoat",
    "Viscacha",
    "Weasel",
    # Unusual mammals
    "Aardvark",
    "Aardwolf",
    "Anteater",
    "Armadillo",
    "Cacomistle",
    "Coati",
    "Echidna",
    "Fossa",
    "Hyena",
    "Kangaroo",
    "Kinkajou",
    "Koala",
    "Numbat",
    "Pangolin",
    "Platypus",
    "Quokka",
    "Sloth",
    "Sugar glider",
    "Tasmanian devil",
    "Tree-kangaroo",
    "Wallaby",
    "Wolverine",
    "Wombat",
    # Bats
    "Bumblebee bat",
    "Flying fox",
    "Fruit bat",
    "Horseshoe bat",
    "Long-eared bat",
    "Vampire bat",
]

BIRDS = [
    # Raptors
    "Andean condor",
    "Bald eagle",
    "Bearded vulture",
    "Black kite",
    "Brahminy kite",
    "California condor",
    "Cooper's hawk",
    "Crowned eagle",
    "Golden eagle",
    "Griffon vulture",
    "Gyrfalcon",
    "Harpy eagle",
    "Harris's hawk",
    "Kestrel",
    "King vulture",
    "Martial eagle",
    "Merlin (bird)",
    "Northern goshawk",
    "Osprey",
    "Peregrine falcon",
    "Philippine eagle",
    "Red kite",
    "Red-tailed hawk",
    "Secretary bird",
    "Steller's sea eagle",
    "Turkey vulture",
    "Verreaux's eagle",
    "Wedge-tailed eagle",
    "White-tailed eagle",
    # Owls
    "Barn owl",
    "Barred owl",
    "Burrowing owl",
    "Eagle-owl",
    "Elf owl",
    "Great grey owl",
    "Great horned owl",
    "Long-eared owl",
    "Northern saw-whet owl",
    "Screech owl",
    "Short-eared owl",
    "Snowy owl",
    "Spectacled owl",
    "Tawny owl",
    # Parrots & cockatoos
    "African grey parrot",
    "Amazon parrot",
    "Blue-and-yellow macaw",
    "Budgerigar",
    "Cockatiel",
    "Cockatoo",
    "Eclectus parrot",
    "Galah",
    "Hyacinth macaw",
    "Kakapo",
    "Kea",
    "Lorikeet",
    "Lovebird",
    "Macaw",
    "Ring-necked parakeet",
    "Scarlet macaw",
    "Sulphur-crested cockatoo",
    "Sun conure",
    # Waterbirds
    "Albatross",
    "Anhinga",
    "Avocet",
    "Booby",
    "Cormorant",
    "Crane (bird)",
    "Curlew",
    "Dipper",
    "Egret",
    "Flamingo",
    "Frigatebird",
    "Gannet",
    "Great blue heron",
    "Guillemot",
    "Gull",
    "Heron",
    "Ibis",
    "Kingfisher",
    "Oystercatcher",
    "Pelican",
    "Petrel",
    "Plover",
    "Puffin",
    "Razorbill",
    "Sandpiper",
    "Shearwater",
    "Skua",
    "Spoonbill",
    "Stork",
    "Swan",
    "Tern",
    # Penguins & flightless
    "Adélie penguin",
    "Cassowary",
    "Chinstrap penguin",
    "Emperor penguin",
    "Emu",
    "Gentoo penguin",
    "King penguin",
    "Kiwi (bird)",
    "Little blue penguin",
    "Macaroni penguin",
    "Ostrich",
    "Rhea",
    "Rockhopper penguin",
    # Songbirds & passerines
    "Blackbird",
    "Blue jay",
    "Bullfinch",
    "Bunting",
    "Cardinal (bird)",
    "Catbird",
    "Chaffinch",
    "Crossbill",
    "Crow",
    "Goldfinch",
    "Jackdaw",
    "Jay",
    "Linnet",
    "Magpie",
    "Martin (bird)",
    "Mockingbird",
    "Nightingale",
    "Nuthatch",
    "Oriole",
    "Pipit",
    "Raven",
    "Redstart",
    "Robin (bird)",
    "Shrike",
    "Siskin",
    "Skylark",
    "Sparrow",
    "Starling",
    "Swallow",
    "Swift",
    "Tanager",
    "Thrush",
    "Treecreeper",
    "Vireo",
    "Wagtail",
    "Warbler",
    "Waxwing",
    "Wren",
    # Tropical & exotic
    "Barbet",
    "Bee-eater",
    "Bird-of-paradise",
    "Cock-of-the-rock",
    "Cotinga",
    "Flowerpecker",
    "Hoopoe",
    "Hornbill",
    "Hummingbird",
    "Jacamar",
    "Manakin",
    "Motmot",
    "Quetzal",
    "Roller (bird)",
    "Sunbird",
    "Toucan",
    "Trogon",
    "Turaco",
    "Umbrella bird",
    # Game birds & others
    "Cuckoo",
    "Dove",
    "Golden pheasant",
    "Grouse",
    "Guinea fowl",
    "Hoatzin",
    "Kookaburra",
    "Loon",
    "Parrot",
    "Partridge",
    "Peacock",
    "Pheasant",
    "Pigeon",
    "Ptarmigan",
    "Quail",
    "Roadrunner",
    "Tawny frogmouth",
    "Tragopan",
    "Turkey (bird)",
    "Woodpecker",
]

REPTILES = [
    # Lizards
    "Anole",
    "Armadillo girdled lizard",
    "Basilisk lizard",
    "Bearded dragon",
    "Blue-tongued skink",
    "Chameleon",
    "Chuckwalla",
    "Collared lizard",
    "Day gecko",
    "Flying lizard",
    "Frilled-neck lizard",
    "Gecko",
    "Gila monster",
    "Glass lizard",
    "Green iguana",
    "Horned lizard",
    "Iguana",
    "Komodo dragon",
    "Leaf-tailed gecko",
    "Leopard gecko",
    "Marine iguana",
    "Mexican beaded lizard",
    "Monitor lizard",
    "Nile monitor",
    "Slow worm",
    "Tegu",
    "Thorny devil",
    "Tokay gecko",
    "Tuatara",
    "Water monitor",
    # Snakes
    "Anaconda",
    "Ball python",
    "Black mamba",
    "Boa constrictor",
    "Boomslang",
    "Burmese python",
    "Bushmaster",
    "Cobra",
    "Copperhead (snake)",
    "Coral snake",
    "Corn snake",
    "Cottonmouth",
    "Death adder",
    "Eastern brown snake",
    "Emerald tree boa",
    "Eyelash viper",
    "Fer-de-lance",
    "Flying snake",
    "Gaboon viper",
    "Garter snake",
    "Green anaconda",
    "Green mamba",
    "Green tree python",
    "Hognose snake",
    "Indigo snake",
    "King cobra",
    "King snake",
    "Mangrove snake",
    "Milk snake",
    "Pit viper",
    "Puff adder",
    "Rainbow boa",
    "Rat snake",
    "Rattlesnake",
    "Reticulated python",
    "Russell's viper",
    "Saw-scaled viper",
    "Sea snake",
    "Sidewinder",
    "Taipan",
    "Vine snake",
    # Turtles & tortoises
    "Aldabra giant tortoise",
    "Alligator snapping turtle",
    "Box turtle",
    "Diamondback terrapin",
    "Galápagos tortoise",
    "Green sea turtle",
    "Hawksbill sea turtle",
    "Leatherback sea turtle",
    "Loggerhead sea turtle",
    "Mata mata",
    "Painted turtle",
    "Red-eared slider",
    "Red-footed tortoise",
    "Sea turtle",
    "Snapping turtle",
    "Softshell turtle",
    "Sulcata tortoise",
    # Crocodilians
    "Alligator",
    "American alligator",
    "American crocodile",
    "Black caiman",
    "Caiman",
    "Chinese alligator",
    "Crocodile",
    "Dwarf crocodile",
    "False gharial",
    "Gharial",
    "Nile crocodile",
    "Saltwater crocodile",
    "Spectacled caiman",
]

AMPHIBIANS = [
    # Frogs
    "African bullfrog",
    "Amazon milk frog",
    "Blue poison dart frog",
    "Bull frog",
    "Cane toad",
    "Common toad",
    "Darwin's frog",
    "Fire-bellied toad",
    "Glass frog",
    "Golden poison frog",
    "Golden toad",
    "Goliath frog",
    "Green tree frog",
    "Harlequin toad",
    "Leopard frog",
    "Mantella",
    "Midwife toad",
    "Natterjack toad",
    "Oriental fire-bellied toad",
    "Pac-Man frog",
    "Poison dart frog",
    "Poison frog",
    "Purple frog",
    "Rain frog",
    "Red-eyed tree frog",
    "Spadefoot toad",
    "Spring peeper",
    "Strawberry poison-dart frog",
    "Surinam toad",
    "Tomato frog",
    "Tree frog",
    "Vietnamese mossy frog",
    "Wallace's flying frog",
    "Waxy monkey tree frog",
    "White's tree frog",
    "Wood frog",
    # Salamanders & newts
    "Alpine newt",
    "Axolotl",
    "Cave salamander",
    "Chinese giant salamander",
    "Eastern newt",
    "Fire salamander",
    "Giant salamander",
    "Great crested newt",
    "Hellbender",
    "Japanese giant salamander",
    "Marbled newt",
    "Mudpuppy",
    "Olm",
    "Palmate newt",
    "Red-backed salamander",
    "Red-spotted newt",
    "Slimy salamander",
    "Smooth newt",
    "Spotted salamander",
    "Spring salamander",
    "Tiger salamander",
    # Caecilians
    "Caecilian",
]

MARINE = [
    # Cephalopods
    "Blanket octopus",
    "Blue-ringed octopus",
    "Colossal squid",
    "Cuttlefish",
    "Dumbo octopus",
    "Firefly squid",
    "Flamboyant cuttlefish",
    "Giant cuttlefish",
    "Giant Pacific octopus",
    "Giant squid",
    "Humboldt squid",
    "Mimic octopus",
    "Nautilus",
    "Octopus",
    # Sharks & rays
    "Basking shark",
    "Blacktip reef shark",
    "Blue shark",
    "Bull shark",
    "Cookiecutter shark",
    "Eagle ray",
    "Electric ray",
    "Goblin shark",
    "Great white shark",
    "Greenland shark",
    "Guitarfish",
    "Hammerhead shark",
    "Leopard shark",
    "Mako shark",
    "Manta ray",
    "Megamouth shark",
    "Nurse shark",
    "Sawfish",
    "Stingray",
    "Thornback ray",
    "Thresher shark",
    "Tiger shark",
    "Whale shark",
    "Whitetip reef shark",
    "Wobbegong",
    # Bony fish
    "Angelfish",
    "Anglerfish",
    "Arapaima",
    "Archerfish",
    "Barracuda",
    "Betta",
    "Bonefish",
    "Butterflyfish",
    "Clownfish",
    "Coelacanth",
    "Discus (fish)",
    "Electric eel",
    "Flying fish",
    "Frogfish",
    "Grouper",
    "Guppy",
    "Lanternfish",
    "Leafy seadragon",
    "Lionfish",
    "Mahi-mahi",
    "Mandarin fish",
    "Marlin",
    "Moray eel",
    "Mudskipper",
    "Oarfish",
    "Oscar (fish)",
    "Parrotfish",
    "Pipefish",
    "Piranha",
    "Pufferfish",
    "Sailfish",
    "Seahorse",
    "Sunfish (Mola mola)",
    "Surgeonfish",
    "Swordfish",
    "Tarpon",
    "Triggerfish",
    "Tuna",
    "Viperfish",
    "Weedy seadragon",
    "Wrasse",
    # Cnidarians & jellies
    "Box jellyfish",
    "Brain coral",
    "Coral",
    "Jellyfish",
    "Lion's mane jellyfish",
    "Moon jellyfish",
    "Portuguese man o' war",
    "Sea anemone",
    "Sea fan",
    "Staghorn coral",
    # Echinoderms
    "Brittle star",
    "Crown-of-thorns starfish",
    "Sand dollar",
    "Sea cucumber",
    "Sea urchin",
    "Starfish",
    # Crustaceans
    "Barnacle",
    "Cleaner shrimp",
    "Coconut crab",
    "Fiddler crab",
    "Hermit crab",
    "Horseshoe crab",
    "Isopod",
    "Japanese spider crab",
    "King crab",
    "Krill",
    "Lobster",
    "Mantis shrimp",
    "Pistol shrimp",
    "Spider crab",
    # Molluscs
    "Abalone",
    "Chambered nautilus",
    "Cone snail",
    "Giant clam",
    "Nudibranch",
    "Scallop",
    "Sea slug",
    # Other marine
    "Christmas tree worm",
    "Comb jelly",
    "Feather star",
    "Remora",
    "Sea pen",
    "Sea sponge",
    "Sea squirt",
    "Whale louse",
]

INSECTS = [
    # Butterflies & moths
    "Atlas moth",
    "Birdwing butterfly",
    "Blue morpho",
    "Cabbage white butterfly",
    "Cecropia moth",
    "Cinnabar moth",
    "Clouded yellow butterfly",
    "Comet moth",
    "Comma butterfly",
    "Death's-head hawkmoth",
    "Garden tiger moth",
    "Glasswing butterfly",
    "Hairstreak butterfly",
    "Hawk moth",
    "Hummingbird hawk-moth",
    "Io moth",
    "Luna moth",
    "Monarch butterfly",
    "Owl butterfly",
    "Painted lady (butterfly)",
    "Peacock butterfly",
    "Peppered moth",
    "Polyphemus moth",
    "Red admiral (butterfly)",
    "Silk moth",
    "Swallowtail butterfly",
    # Beetles
    "Atlas beetle",
    "Blister beetle",
    "Bombardier beetle",
    "Click beetle",
    "Deathwatch beetle",
    "Diving beetle",
    "Dung beetle",
    "Firefly",
    "Giraffe weevil",
    "Goliath beetle",
    "Ground beetle",
    "Hercules beetle",
    "Jewel beetle",
    "Ladybug",
    "Longhorn beetle",
    "Rhinoceros beetle",
    "Scarab beetle",
    "Stag beetle",
    "Tiger beetle",
    "Titan beetle",
    "Weevil",
    "Whirligig beetle",
    # Dragonflies & damselflies
    "Banded demoiselle",
    "Blue dasher",
    "Common darter",
    "Damselfly",
    "Dragonfly",
    "Ebony jewelwing",
    "Emperor dragonfly",
    # Hymenoptera (ants, bees, wasps)
    "Army ant",
    "Asian giant hornet",
    "Bullet ant",
    "Bumblebee",
    "Carpenter ant",
    "Carpenter bee",
    "Fire ant",
    "Honeybee",
    "Hornet",
    "Ichneumon wasp",
    "Leafcutter ant",
    "Leafcutter bee",
    "Mason bee",
    "Mud dauber",
    "Orchid bee",
    "Paper wasp",
    "Sweat bee",
    "Tarantula hawk",
    "Velvet ant",
    "Weaver ant",
    "Yellow jacket",
    # Mantises & stick insects
    "Dead leaf mantis",
    "Ghost mantis",
    "Giant Asian mantis",
    "Giant prickly stick insect",
    "Leaf insect",
    "Orchid mantis",
    "Praying mantis",
    "Stick insect",
    # True bugs & cicadas
    "Assassin bug",
    "Cicada",
    "Giant water bug",
    "Lanternfly",
    "Leafhopper",
    "Periodical cicada",
    "Planthopper",
    "Shield bug",
    "Thorn bug",
    "Water strider",
    # Flies & mosquitoes
    "Bee fly",
    "Bluebottle fly",
    "Crane fly",
    "Fruit fly",
    "Horsefly",
    "Hoverfly",
    "Robber fly",
    # Grasshoppers & crickets
    "Cricket (insect)",
    "Grasshopper",
    "Katydid",
    "Locust",
    "Mole cricket",
    "Weta",
    # Arachnids
    "Arizona bark scorpion",
    "Black widow spider",
    "Brazilian wandering spider",
    "Brown recluse spider",
    "Camel spider",
    "Crab spider",
    "Deathstalker",
    "Emperor scorpion",
    "Fishing spider",
    "Garden spider",
    "Golden silk orb-weaver",
    "Goliath birdeater",
    "Harvestman",
    "Huntsman spider",
    "Jumping spider",
    "Mexican red-knee tarantula",
    "Ogre-faced spider",
    "Peacock spider",
    "Pseudoscorpion",
    "Scorpion",
    "Tarantula",
    "Tick",
    "Trapdoor spider",
    "Velvet mite",
    "Whip scorpion",
    "Wolf spider",
    # Other arthropods
    "Centipede",
    "Earwig",
    "Giant African millipede",
    "Giant centipede",
    "Millipede",
    "Pill millipede",
    "Silverfish",
    "Woodlouse",
]

DOG_BREEDS = [
    "Afghan Hound",
    "Airedale Terrier",
    "Akita (dog breed)",
    "Alaskan Malamute",
    "American Bulldog",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Anatolian Shepherd Dog",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Australian Terrier",
    "Azawakh",
    "Barbet (dog breed)",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Beauceron",
    "Belgian Malinois",
    "Belgian Shepherd",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bloodhound",
    "Bolognese (dog)",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer (dog)",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Briard",
    "Brittany (dog)",
    "Brussels Griffon",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua (dog breed)",
    "Chinese Crested Dog",
    "Chinese Shar-Pei",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Collie",
    "Coton de Tulear",
    "Dachshund",
    "Dalmatian dog",
    "Dobermann",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Setter",
    "English Springer Spaniel",
    "Entlebucher Mountain Dog",
    "Field Spaniel",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "French Bulldog",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Harrier (dog breed)",
    "Havanese dog",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Keeshond",
    "Kerry Blue Terrier",
    "Komondor",
    "Kuvasz",
    "Labradoodle",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Leonberger",
    "Lhasa Apso",
    "Lowchen",
    "Maltese dog",
    "Manchester Terrier",
    "Mastiff (dog breed)",
    "Miniature Bull Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Mudi (dog breed)",
    "Neapolitan Mastiff",
    "Newfoundland dog",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon (dog)",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Petit Basset Griffon Vendéen",
    "Pharaoh Hound",
    "Plott Hound",
    "Pointer (dog breed)",
    "Polish Lowland Sheepdog",
    "Pomeranian (dog breed)",
    "Poodle",
    "Portuguese Podengo",
    "Portuguese Water Dog",
    "Pug",
    "Puli (dog breed)",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Russell Terrier",
    "Saluki",
    "Saint Bernard (dog)",
    "Samoyed (dog breed)",
    "Schipperke",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Soft-coated Wheaten Terrier",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Swedish Vallhund",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintle",
    "Yorkshire Terrier",
]

CAT_BREEDS = [
    "Abyssinian (cat)",
    "American Curl",
    "American Shorthair",
    "Bengal cat",
    "Birman",
    "Bombay cat",
    "British Longhair",
    "British Shorthair",
    "Burmese cat",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Himalayan cat",
    "Japanese Bobtail",
    "Korat",
    "Maine Coon",
    "Manx cat",
    "Munchkin cat",
    "Norwegian Forest cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian cat",
    "Peterbald",
    "Ragamuffin cat",
    "Ragdoll",
    "Russian Blue",
    "Savannah cat",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese cat",
    "Siberian cat",
    "Singapura cat",
    "Snowshoe cat",
    "Somali cat",
    "Sphynx cat",
    "Tonkinese cat",
    "Turkish Angora",
    "Turkish Van",
]

ALL = (
    MAMMALS
    + BIRDS
    + REPTILES
    + AMPHIBIANS
    + MARINE
    + INSECTS
    + DOG_BREEDS
    + CAT_BREEDS
    + DINOSAURS
)

CLASSES = {
    "mammals": MAMMALS,
    "birds": BIRDS,
    "reptiles": REPTILES,
    "amphibians": AMPHIBIANS,
    "marine": MARINE,
    "insects": INSECTS,
    "dogs": DOG_BREEDS,
    "cats": CAT_BREEDS,
    "dinosaurs": DINOSAURS,
}
