from memi.categories.dinosaurs import ALL as DINOSAURS

EASY_MAMMALS = [
    # Big cats
    "Cheetah",
    "Cougar",
    "Jaguar",
    "Leopard",
    "Lion",
    "Lynx",
    "Snow leopard",
    "Tiger",
    # Canines
    "Arctic fox",
    "Coyote",
    "Dingo",
    "Jackal",
    "Red fox",
    "Wolf",
    # Bears
    "Brown bear",
    "Giant panda",
    "Polar bear",
    "Red panda",
    # Primates
    "Baboon",
    "Chimpanzee",
    "Gorilla",
    "Lemur",
    "Orangutan",
    # Marine mammals
    "Blue whale",
    "Dolphin",
    "Humpback whale",
    "Manatee",
    "Narwhal",
    "Orca",
    "Sea lion",
    "Sea otter",
    "Sperm whale",
    "Walrus",
    # Elephants & large herbivores
    "African elephant",
    "Asian elephant",
    "Bison",
    "Caribou",
    "Elk",
    "Giraffe",
    "Hippopotamus",
    "Moose",
    "Water buffalo",
    "Yak",
    "Zebra",
    # Antelopes & deer
    "Gazelle",
    "Impala",
    "Wildebeest",
    # Small mammals
    "Badger",
    "Beaver",
    "Chipmunk",
    "Ferret",
    "Groundhog",
    "Hedgehog",
    "Meerkat",
    "Mongoose",
    "Opossum",
    "Otter",
    "Porcupine",
    "Prairie dog",
    "Raccoon",
    "Skunk",
    "Weasel",
    # Unusual mammals
    "Anteater",
    "Armadillo",
    "Hyena",
    "Kangaroo",
    "Koala",
    "Platypus",
    "Sloth",
    "Tasmanian devil",
    "Wolverine",
    "Wombat",
    # Bats
    "Vampire bat",
]

HARD_MAMMALS = [
    # Big cats
    "Black-footed cat",
    "Bobcat",
    "Caracal",
    "Clouded leopard",
    "Eurasian lynx",
    "Fishing cat",
    "Iberian lynx",
    "Jaguarundi",
    "Margay",
    "Ocelot",
    "Pallas's cat",
    "Sand cat",
    "Serval",
    "Sunda clouded leopard",
    # Canines
    "African wild dog",
    "Bat-eared fox",
    "Bush dog",
    "Dhole",
    "Fennec fox",
    "Gray fox",
    "Kit fox",
    "Maned wolf",
    "Raccoon dog",
    # Bears
    "American black bear",
    "Asian black bear",
    "Sloth bear",
    "Spectacled bear",
    "Sun bear",
    # Primates
    "Aye-aye",
    "Bonobo",
    "Capuchin monkey",
    "Colobus monkey",
    "Galago",
    "Gelada",
    "Gibbon",
    "Golden lion tamarin",
    "Howler monkey",
    "Indri",
    "Japanese macaque",
    "Mandrill",
    "Proboscis monkey",
    "Ring-tailed lemur",
    "Sifaka",
    "Slow loris",
    "Spider monkey",
    "Tarsier",
    "Vervet monkey",
    # Marine mammals
    "Beluga whale",
    "Bowhead whale",
    "Dugong",
    "Elephant seal",
    "Fin whale",
    "Fur seal",
    "Gray whale",
    "Harbor seal",
    "Leopard seal",
    "Minke whale",
    "Pilot whale",
    "Right whale",
    "Sei whale",
    # Elephants & large herbivores
    "Black rhinoceros",
    "Indian rhinoceros",
    "Javan rhinoceros",
    "Musk ox",
    "Okapi",
    "Sumatran rhinoceros",
    "Tapir",
    "White rhinoceros",
    # Antelopes & deer
    "Axis deer",
    "Bongo (antelope)",
    "Bushbuck",
    "Chamois",
    "Dik-dik",
    "Eland",
    "Fallow deer",
    "Gerenuk",
    "Hartebeest",
    "Ibex",
    "Kudu",
    "Markhor",
    "Mouflon",
    "Muntjac",
    "Nyala",
    "Oryx",
    "Pronghorn",
    "Pudu",
    "Red deer",
    "Roe deer",
    "Sable antelope",
    "Saiga antelope",
    "Sambar deer",
    "Springbok",
    "Topi",
    "Waterbuck",
    # Small mammals
    "Agouti",
    "Binturong",
    "Capybara",
    "Chinchilla",
    "Civet",
    "Coypu",
    "Dormouse",
    "Flying squirrel",
    "Genet",
    "Mara",
    "Marmot",
    "Mink",
    "Pika",
    "Pine marten",
    "Red squirrel",
    "Stoat",
    "Viscacha",
    # Unusual mammals
    "Aardvark",
    "Aardwolf",
    "Cacomistle",
    "Coati",
    "Echidna",
    "Fossa",
    "Kinkajou",
    "Numbat",
    "Pangolin",
    "Quokka",
    "Sugar glider",
    "Tree-kangaroo",
    "Wallaby",
    # Bats
    "Bumblebee bat",
    "Flying fox",
    "Fruit bat",
    "Horseshoe bat",
    "Long-eared bat",
]

MAMMALS = EASY_MAMMALS + HARD_MAMMALS

EASY_BIRDS = [
    # Raptors
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    # Owls
    "Barn owl",
    "Great horned owl",
    "Snowy owl",
    # Parrots & cockatoos
    "Budgerigar",
    "Cockatiel",
    "Cockatoo",
    "Macaw",
    "Parrot",
    # Waterbirds
    "Albatross",
    "Crane (bird)",
    "Egret",
    "Flamingo",
    "Gull",
    "Heron",
    "Kingfisher",
    "Pelican",
    "Puffin",
    "Stork",
    "Swan",
    # Penguins & flightless
    "Emperor penguin",
    "Emu",
    "Kiwi (bird)",
    "Ostrich",
    # Songbirds & passerines
    "Blackbird",
    "Blue jay",
    "Cardinal (bird)",
    "Crow",
    "Magpie",
    "Mockingbird",
    "Nightingale",
    "Raven",
    "Robin (bird)",
    "Sparrow",
    "Starling",
    "Swallow",
    "Woodpecker",
    # Tropical & exotic
    "Hummingbird",
    "Toucan",
    # Game birds & others
    "Cuckoo",
    "Dove",
    "Peacock",
    "Pheasant",
    "Pigeon",
    "Quail",
    "Turkey (bird)",
]

HARD_BIRDS = [
    # Raptors
    "Andean condor",
    "Bearded vulture",
    "Black kite",
    "Brahminy kite",
    "California condor",
    "Cooper's hawk",
    "Crowned eagle",
    "Griffon vulture",
    "Gyrfalcon",
    "Harpy eagle",
    "Harris's hawk",
    "Kestrel",
    "King vulture",
    "Martial eagle",
    "Merlin (bird)",
    "Northern goshawk",
    "Philippine eagle",
    "Red kite",
    "Red-tailed hawk",
    "Secretary bird",
    "Steller's sea eagle",
    "Turkey vulture",
    "Verreaux's eagle",
    "Wedge-tailed eagle",
    "White-tailed eagle",
    # Owls
    "Barred owl",
    "Burrowing owl",
    "Eagle-owl",
    "Elf owl",
    "Great grey owl",
    "Long-eared owl",
    "Northern saw-whet owl",
    "Screech owl",
    "Short-eared owl",
    "Spectacled owl",
    "Tawny owl",
    # Parrots & cockatoos
    "African grey parrot",
    "Amazon parrot",
    "Blue-and-yellow macaw",
    "Eclectus parrot",
    "Galah",
    "Hyacinth macaw",
    "Kakapo",
    "Kea",
    "Lorikeet",
    "Lovebird",
    "Ring-necked parakeet",
    "Scarlet macaw",
    "Sulphur-crested cockatoo",
    "Sun conure",
    # Waterbirds
    "Anhinga",
    "Avocet",
    "Booby",
    "Cormorant",
    "Curlew",
    "Dipper",
    "Frigatebird",
    "Gannet",
    "Great blue heron",
    "Guillemot",
    "Ibis",
    "Oystercatcher",
    "Petrel",
    "Plover",
    "Razorbill",
    "Sandpiper",
    "Shearwater",
    "Skua",
    "Spoonbill",
    "Tern",
    # Penguins & flightless
    "Adélie penguin",
    "Cassowary",
    "Chinstrap penguin",
    "Gentoo penguin",
    "King penguin",
    "Little blue penguin",
    "Macaroni penguin",
    "Rhea",
    "Rockhopper penguin",
    # Songbirds & passerines
    "Bullfinch",
    "Bunting",
    "Catbird",
    "Chaffinch",
    "Crossbill",
    "Goldfinch",
    "Jackdaw",
    "Jay",
    "Linnet",
    "Martin (bird)",
    "Nuthatch",
    "Oriole",
    "Pipit",
    "Redstart",
    "Shrike",
    "Siskin",
    "Skylark",
    "Swift",
    "Tanager",
    "Thrush",
    "Treecreeper",
    "Vireo",
    "Wagtail",
    "Warbler",
    "Waxwing",
    "Wren",
    # Tropical & exotic
    "Barbet",
    "Bee-eater",
    "Bird-of-paradise",
    "Cock-of-the-rock",
    "Cotinga",
    "Flowerpecker",
    "Hoopoe",
    "Hornbill",
    "Jacamar",
    "Manakin",
    "Motmot",
    "Quetzal",
    "Roller (bird)",
    "Sunbird",
    "Trogon",
    "Turaco",
    "Umbrella bird",
    # Game birds & others
    "Golden pheasant",
    "Grouse",
    "Guinea fowl",
    "Hoatzin",
    "Kookaburra",
    "Loon",
    "Partridge",
    "Ptarmigan",
    "Roadrunner",
    "Tawny frogmouth",
    "Tragopan",
]

BIRDS = EASY_BIRDS + HARD_BIRDS

EASY_REPTILES = [
    # Lizards
    "Chameleon",
    "Gecko",
    "Green iguana",
    "Iguana",
    "Komodo dragon",
    # Snakes
    "Anaconda",
    "Boa constrictor",
    "Cobra",
    "Coral snake",
    "King cobra",
    "Rattlesnake",
    # Turtles & tortoises
    "Sea turtle",
    "Snapping turtle",
    # Crocodilians
    "Alligator",
    "Crocodile",
]

HARD_REPTILES = [
    # Lizards
    "Anole",
    "Armadillo girdled lizard",
    "Basilisk lizard",
    "Bearded dragon",
    "Blue-tongued skink",
    "Chuckwalla",
    "Collared lizard",
    "Day gecko",
    "Flying lizard",
    "Frilled-neck lizard",
    "Gila monster",
    "Glass lizard",
    "Horned lizard",
    "Leaf-tailed gecko",
    "Leopard gecko",
    "Marine iguana",
    "Mexican beaded lizard",
    "Monitor lizard",
    "Nile monitor",
    "Slow worm",
    "Tegu",
    "Thorny devil",
    "Tokay gecko",
    "Tuatara",
    "Water monitor",
    # Snakes
    "Ball python",
    "Black mamba",
    "Boomslang",
    "Burmese python",
    "Bushmaster",
    "Copperhead (snake)",
    "Corn snake",
    "Cottonmouth",
    "Death adder",
    "Eastern brown snake",
    "Emerald tree boa",
    "Eyelash viper",
    "Fer-de-lance",
    "Flying snake",
    "Gaboon viper",
    "Garter snake",
    "Green anaconda",
    "Green mamba",
    "Green tree python",
    "Hognose snake",
    "Indigo snake",
    "King snake",
    "Mangrove snake",
    "Milk snake",
    "Pit viper",
    "Puff adder",
    "Rainbow boa",
    "Rat snake",
    "Reticulated python",
    "Russell's viper",
    "Saw-scaled viper",
    "Sea snake",
    "Sidewinder",
    "Taipan",
    "Vine snake",
    # Turtles & tortoises
    "Aldabra giant tortoise",
    "Alligator snapping turtle",
    "Box turtle",
    "Diamondback terrapin",
    "Galápagos tortoise",
    "Green sea turtle",
    "Hawksbill sea turtle",
    "Leatherback sea turtle",
    "Loggerhead sea turtle",
    "Mata mata",
    "Painted turtle",
    "Red-eared slider",
    "Red-footed tortoise",
    "Softshell turtle",
    "Sulcata tortoise",
    # Crocodilians
    "American alligator",
    "American crocodile",
    "Black caiman",
    "Caiman",
    "Chinese alligator",
    "Dwarf crocodile",
    "False gharial",
    "Gharial",
    "Nile crocodile",
    "Saltwater crocodile",
    "Spectacled caiman",
]

REPTILES = EASY_REPTILES + HARD_REPTILES

EASY_AMPHIBIANS = [
    # Frogs
    "Bull frog",
    "Poison dart frog",
    "Tree frog",
    # Salamanders & newts
    "Axolotl",
]

HARD_AMPHIBIANS = [
    # Frogs
    "African bullfrog",
    "Amazon milk frog",
    "Blue poison dart frog",
    "Cane toad",
    "Common toad",
    "Darwin's frog",
    "Fire-bellied toad",
    "Glass frog",
    "Golden poison frog",
    "Golden toad",
    "Goliath frog",
    "Green tree frog",
    "Harlequin toad",
    "Leopard frog",
    "Mantella",
    "Midwife toad",
    "Natterjack toad",
    "Oriental fire-bellied toad",
    "Pac-Man frog",
    "Poison frog",
    "Purple frog",
    "Rain frog",
    "Red-eyed tree frog",
    "Spadefoot toad",
    "Spring peeper",
    "Strawberry poison-dart frog",
    "Surinam toad",
    "Tomato frog",
    "Vietnamese mossy frog",
    "Wallace's flying frog",
    "Waxy monkey tree frog",
    "White's tree frog",
    "Wood frog",
    # Salamanders & newts
    "Alpine newt",
    "Cave salamander",
    "Chinese giant salamander",
    "Eastern newt",
    "Fire salamander",
    "Giant salamander",
    "Great crested newt",
    "Hellbender",
    "Japanese giant salamander",
    "Marbled newt",
    "Mudpuppy",
    "Olm",
    "Palmate newt",
    "Red-backed salamander",
    "Red-spotted newt",
    "Slimy salamander",
    "Smooth newt",
    "Spotted salamander",
    "Spring salamander",
    "Tiger salamander",
    # Caecilians
    "Caecilian",
]

AMPHIBIANS = EASY_AMPHIBIANS + HARD_AMPHIBIANS

EASY_MARINE = [
    # Cephalopods
    "Octopus",
    # Sharks & rays
    "Great white shark",
    "Hammerhead shark",
    "Manta ray",
    "Stingray",
    "Tiger shark",
    "Whale shark",
    # Bony fish
    "Angelfish",
    "Barracuda",
    "Clownfish",
    "Electric eel",
    "Piranha",
    "Pufferfish",
    "Seahorse",
    "Swordfish",
    "Tuna",
    # Cnidarians & jellies
    "Coral",
    "Jellyfish",
    "Sea anemone",
    # Echinoderms
    "Sea urchin",
    "Starfish",
    # Crustaceans
    "Hermit crab",
    "Lobster",
]

HARD_MARINE = [
    # Cephalopods
    "Blanket octopus",
    "Blue-ringed octopus",
    "Colossal squid",
    "Cuttlefish",
    "Dumbo octopus",
    "Firefly squid",
    "Flamboyant cuttlefish",
    "Giant cuttlefish",
    "Giant Pacific octopus",
    "Giant squid",
    "Humboldt squid",
    "Mimic octopus",
    "Nautilus",
    # Sharks & rays
    "Basking shark",
    "Blacktip reef shark",
    "Blue shark",
    "Bull shark",
    "Cookiecutter shark",
    "Eagle ray",
    "Electric ray",
    "Goblin shark",
    "Greenland shark",
    "Guitarfish",
    "Leopard shark",
    "Mako shark",
    "Megamouth shark",
    "Nurse shark",
    "Sawfish",
    "Thornback ray",
    "Thresher shark",
    "Whitetip reef shark",
    "Wobbegong",
    # Bony fish
    "Anglerfish",
    "Arapaima",
    "Archerfish",
    "Betta",
    "Bonefish",
    "Butterflyfish",
    "Coelacanth",
    "Discus (fish)",
    "Flying fish",
    "Frogfish",
    "Grouper",
    "Guppy",
    "Lanternfish",
    "Leafy seadragon",
    "Lionfish",
    "Mahi-mahi",
    "Mandarin fish",
    "Marlin",
    "Moray eel",
    "Mudskipper",
    "Oarfish",
    "Oscar (fish)",
    "Parrotfish",
    "Pipefish",
    "Sailfish",
    "Sunfish (Mola mola)",
    "Surgeonfish",
    "Tarpon",
    "Triggerfish",
    "Viperfish",
    "Weedy seadragon",
    "Wrasse",
    # Cnidarians & jellies
    "Box jellyfish",
    "Brain coral",
    "Lion's mane jellyfish",
    "Moon jellyfish",
    "Portuguese man o' war",
    "Sea fan",
    "Staghorn coral",
    # Echinoderms
    "Brittle star",
    "Crown-of-thorns starfish",
    "Sand dollar",
    "Sea cucumber",
    # Crustaceans
    "Barnacle",
    "Cleaner shrimp",
    "Coconut crab",
    "Fiddler crab",
    "Horseshoe crab",
    "Isopod",
    "Japanese spider crab",
    "King crab",
    "Krill",
    "Mantis shrimp",
    "Pistol shrimp",
    "Spider crab",
    # Molluscs
    "Abalone",
    "Chambered nautilus",
    "Cone snail",
    "Giant clam",
    "Nudibranch",
    "Scallop",
    "Sea slug",
    # Other marine
    "Christmas tree worm",
    "Comb jelly",
    "Feather star",
    "Remora",
    "Sea pen",
    "Sea sponge",
    "Sea squirt",
    "Whale louse",
]

MARINE = EASY_MARINE + HARD_MARINE

EASY_INSECTS = [
    # Butterflies & moths
    "Monarch butterfly",
    # Beetles
    "Firefly",
    "Ladybug",
    # Dragonflies & damselflies
    "Dragonfly",
    # Hymenoptera (ants, bees, wasps)
    "Bumblebee",
    "Honeybee",
    "Hornet",
    # Mantises & stick insects
    "Praying mantis",
    # True bugs & cicadas
    "Cicada",
    # Grasshoppers & crickets
    "Cricket (insect)",
    "Grasshopper",
    "Locust",
    # Arachnids
    "Black widow spider",
    "Scorpion",
    "Tarantula",
    "Tick",
    # Other arthropods
    "Centipede",
    "Millipede",
]

HARD_INSECTS = [
    # Butterflies & moths
    "Atlas moth",
    "Birdwing butterfly",
    "Blue morpho",
    "Cabbage white butterfly",
    "Cecropia moth",
    "Cinnabar moth",
    "Clouded yellow butterfly",
    "Comet moth",
    "Comma butterfly",
    "Death's-head hawkmoth",
    "Garden tiger moth",
    "Glasswing butterfly",
    "Hairstreak butterfly",
    "Hawk moth",
    "Hummingbird hawk-moth",
    "Io moth",
    "Luna moth",
    "Owl butterfly",
    "Painted lady (butterfly)",
    "Peacock butterfly",
    "Peppered moth",
    "Polyphemus moth",
    "Red admiral (butterfly)",
    "Silk moth",
    "Swallowtail butterfly",
    # Beetles
    "Atlas beetle",
    "Blister beetle",
    "Bombardier beetle",
    "Click beetle",
    "Deathwatch beetle",
    "Diving beetle",
    "Dung beetle",
    "Giraffe weevil",
    "Goliath beetle",
    "Ground beetle",
    "Hercules beetle",
    "Jewel beetle",
    "Longhorn beetle",
    "Rhinoceros beetle",
    "Scarab beetle",
    "Stag beetle",
    "Tiger beetle",
    "Titan beetle",
    "Weevil",
    "Whirligig beetle",
    # Dragonflies & damselflies
    "Banded demoiselle",
    "Blue dasher",
    "Common darter",
    "Damselfly",
    "Ebony jewelwing",
    "Emperor dragonfly",
    # Hymenoptera (ants, bees, wasps)
    "Army ant",
    "Asian giant hornet",
    "Bullet ant",
    "Carpenter ant",
    "Carpenter bee",
    "Fire ant",
    "Ichneumon wasp",
    "Leafcutter ant",
    "Leafcutter bee",
    "Mason bee",
    "Mud dauber",
    "Orchid bee",
    "Paper wasp",
    "Sweat bee",
    "Tarantula hawk",
    "Velvet ant",
    "Weaver ant",
    "Yellow jacket",
    # Mantises & stick insects
    "Dead leaf mantis",
    "Ghost mantis",
    "Giant Asian mantis",
    "Giant prickly stick insect",
    "Leaf insect",
    "Orchid mantis",
    "Stick insect",
    # True bugs & cicadas
    "Assassin bug",
    "Giant water bug",
    "Lanternfly",
    "Leafhopper",
    "Periodical cicada",
    "Planthopper",
    "Shield bug",
    "Thorn bug",
    "Water strider",
    # Flies & mosquitoes
    "Bee fly",
    "Bluebottle fly",
    "Crane fly",
    "Fruit fly",
    "Horsefly",
    "Hoverfly",
    "Robber fly",
    # Grasshoppers & crickets
    "Katydid",
    "Mole cricket",
    "Weta",
    # Arachnids
    "Arizona bark scorpion",
    "Brazilian wandering spider",
    "Brown recluse spider",
    "Camel spider",
    "Crab spider",
    "Deathstalker",
    "Emperor scorpion",
    "Fishing spider",
    "Garden spider",
    "Golden silk orb-weaver",
    "Goliath birdeater",
    "Harvestman",
    "Huntsman spider",
    "Jumping spider",
    "Mexican red-knee tarantula",
    "Ogre-faced spider",
    "Peacock spider",
    "Pseudoscorpion",
    "Trapdoor spider",
    "Velvet mite",
    "Whip scorpion",
    "Wolf spider",
    # Other arthropods
    "Earwig",
    "Giant African millipede",
    "Giant centipede",
    "Pill millipede",
    "Silverfish",
    "Woodlouse",
]

INSECTS = EASY_INSECTS + HARD_INSECTS

EASY_DOGS = [
    "Basset Hound",
    "Beagle",
    "Boxer (dog)",
    "Bulldog",
    "Chihuahua (dog breed)",
    "Cocker Spaniel",
    "Collie",
    "Dachshund",
    "Dalmatian dog",
    "Dobermann",
    "French Bulldog",
    "German Shepherd",
    "Golden Retriever",
    "Great Dane",
    "Greyhound",
    "Husky",
    "Jack Russell Terrier",
    "Labrador Retriever",
    "Maltese dog",
    "Poodle",
    "Pug",
    "Rottweiler",
    "Saint Bernard (dog)",
    "Shih Tzu",
    "Siberian Husky",
    "Yorkshire Terrier",
    "Pembroke Welsh Corgi",
    "Pomeranian (dog breed)",
    "Border Collie",
    "Chow Chow",
]

HARD_DOGS = [
    "Afghan Hound",
    "Airedale Terrier",
    "Akita (dog breed)",
    "Alaskan Malamute",
    "American Bulldog",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Anatolian Shepherd Dog",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Australian Terrier",
    "Azawakh",
    "Barbet (dog breed)",
    "Basenji",
    "Beauceron",
    "Belgian Malinois",
    "Belgian Shepherd",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bloodhound",
    "Bolognese (dog)",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Briard",
    "Brittany (dog)",
    "Brussels Griffon",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chinese Crested Dog",
    "Chinese Shar-Pei",
    "Clumber Spaniel",
    "Coton de Tulear",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Setter",
    "English Springer Spaniel",
    "Entlebucher Mountain Dog",
    "Field Spaniel",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "German Pinscher",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Gordon Setter",
    "Great Pyrenees",
    "Harrier (dog breed)",
    "Havanese dog",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Japanese Chin",
    "Keeshond",
    "Kerry Blue Terrier",
    "Komondor",
    "Kuvasz",
    "Labradoodle",
    "Lagotto Romagnolo",
    "Leonberger",
    "Lhasa Apso",
    "Lowchen",
    "Manchester Terrier",
    "Mastiff (dog breed)",
    "Miniature Bull Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Mudi (dog breed)",
    "Neapolitan Mastiff",
    "Newfoundland dog",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon (dog)",
    "Pekingese",
    "Petit Basset Griffon Vendéen",
    "Pharaoh Hound",
    "Plott Hound",
    "Pointer (dog breed)",
    "Polish Lowland Sheepdog",
    "Portuguese Podengo",
    "Portuguese Water Dog",
    "Puli (dog breed)",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Russell Terrier",
    "Saluki",
    "Samoyed (dog breed)",
    "Schipperke",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Soft-coated Wheaten Terrier",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Swedish Vallhund",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintle",
]

DOG_BREEDS = EASY_DOGS + HARD_DOGS

EASY_CATS = [
    "Bengal cat",
    "British Shorthair",
    "Maine Coon",
    "Norwegian Forest cat",
    "Persian cat",
    "Ragdoll",
    "Russian Blue",
    "Scottish Fold",
    "Siamese cat",
    "Sphynx cat",
    "Burmese cat",
    "Himalayan cat",
    "Abyssinian (cat)",
]

HARD_CATS = [
    "American Curl",
    "American Shorthair",
    "Birman",
    "Bombay cat",
    "British Longhair",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Japanese Bobtail",
    "Korat",
    "Manx cat",
    "Munchkin cat",
    "Ocicat",
    "Oriental Shorthair",
    "Peterbald",
    "Ragamuffin cat",
    "Savannah cat",
    "Selkirk Rex",
    "Siberian cat",
    "Singapura cat",
    "Snowshoe cat",
    "Somali cat",
    "Tonkinese cat",
    "Turkish Angora",
    "Turkish Van",
]

CAT_BREEDS = EASY_CATS + HARD_CATS

ALL = (
    MAMMALS
    + BIRDS
    + REPTILES
    + AMPHIBIANS
    + MARINE
    + INSECTS
    + DOG_BREEDS
    + CAT_BREEDS
    + DINOSAURS
)

CLASSES = {
    "mammals": MAMMALS,
    "birds": BIRDS,
    "reptiles": REPTILES,
    "amphibians": AMPHIBIANS,
    "marine": MARINE,
    "insects": INSECTS,
    "dogs": DOG_BREEDS,
    "cats": CAT_BREEDS,
    "dinosaurs": DINOSAURS,
}

DIFFICULTY = {
    "easy": EASY_MAMMALS + EASY_BIRDS + EASY_REPTILES + EASY_AMPHIBIANS + EASY_MARINE + EASY_INSECTS + EASY_DOGS + EASY_CATS,
    "hard": HARD_MAMMALS + HARD_BIRDS + HARD_REPTILES + HARD_AMPHIBIANS + HARD_MARINE + HARD_INSECTS + HARD_DOGS + HARD_CATS,
}
