STAR_WARS = [
    # Original trilogy
    "Admiral Ackbar",
    "Bib Fortuna",
    "Boba Fett",
    "Bossk",
    "C-3PO",
    "Chewbacca",
    "Darth Vader",
    "Dengar",
    "Emperor Palpatine",
    "Figrin D'an",
    "Grand Moff Tarkin",
    "Greedo",
    "Han Solo",
    "IG-88",
    "Jabba the Hutt",
    "Lando Calrissian",
    "Leia Organa",
    "Lobot",
    "Luke Skywalker",
    "Max Rebo",
    "Mon Mothma",
    "Nien Nunb",
    "Obi-Wan Kenobi",
    "R2-D2",
    "Salacious B. Crumb",
    "Wedge Antilles",
    "Wicket W. Warrick",
    "Yoda",
    # Prequel trilogy
    "Aayla Secura",
    "Anakin Skywalker",
    "Bail Organa",
    "Barriss Offee",
    "Captain Typho",
    "Count Dooku",
    "Darth Maul",
    "Dexter Jettster",
    "General Grievous",
    "Jango Fett",
    "Jar Jar Binks",
    "Ki-Adi-Mundi",
    "Kit Fisto",
    "Luminara Unduli",
    "Mace Windu",
    "Nute Gunray",
    "Padmé Amidala",
    "Plo Koon",
    "Qui-Gon Jinn",
    "Sebulba",
    "Shaak Ti",
    "Shmi Skywalker",
    "Watto",
    "Zam Wesell",
    # Sequel trilogy
    "BB-8",
    "Captain Phasma",
    "DJ (Star Wars)",
    "Finn (Star Wars)",
    "General Hux",
    "Jannah (Star Wars)",
    "Kylo Ren",
    "Maz Kanata",
    "Poe Dameron",
    "Pryde",
    "Rey (Star Wars)",
    "Rose Tico",
    "Supreme Leader Snoke",
    "Zorii Bliss",
    # Clone Wars & Rebels
    "Ahsoka Tano",
    "Asajj Ventress",
    "Bo-Katan Kryze",
    "Cad Bane",
    "Captain Rex",
    "Chopper (Star Wars)",
    "Ezra Bridger",
    "Grand Admiral Thrawn",
    "Grand Inquisitor",
    "Hera Syndulla",
    "Kanan Jarrus",
    "Pre Vizsla",
    "Sabine Wren",
    "Satine Kryze",
    "Savage Opress",
    # Mandalorian & other shows
    "Baze Malbus",
    "Cal Kestis",
    "Cara Dune",
    "Cassian Andor",
    "Chirrut Îmwe",
    "Cobb Vanth",
    "Fennec Shand",
    "Greef Karga",
    "Grogu",
    "Inquisitor (Star Wars)",
    "Jyn Erso",
    "K-2SO",
    "Moff Gideon",
    "Orson Krennic",
    "The Mandalorian (character)",
]

LORD_OF_THE_RINGS = [
    # Fellowship
    "Aragorn",
    "Boromir",
    "Frodo Baggins",
    "Gandalf",
    "Gimli (Middle-earth)",
    "Legolas",
    "Merry Brandybuck",
    "Pippin Took",
    "Samwise Gamgee",
    # Hobbits
    "Bilbo Baggins",
    "Farmer Maggot",
    "Lobelia Sackville-Baggins",
    "Old Gaffer",
    "Rosie Cotton",
    # Elves
    "Arwen",
    "Celeborn",
    "Círdan",
    "Elladan and Elrohir",
    "Elrond",
    "Erestor",
    "Galadriel",
    "Gil-galad",
    "Glorfindel",
    "Haldir (Middle-earth)",
    "Legolas",
    "Thranduil",
    # Men
    "Bard the Bowman",
    "Beregond",
    "Denethor",
    "Faramir",
    "Hama (Middle-earth)",
    "Imrahil",
    "Théoden",
    "Wormtongue",
    "Éomer",
    "Éowyn",
    # Villains & creatures
    "Balrog",
    "Gollum",
    "Gothmog (Third Age)",
    "Lurtz",
    "Mouth of Sauron",
    "Saruman",
    "Sauron",
    "Shelob",
    "Witch-king of Angmar",
    # Wizards & others
    "Goldberry",
    "Quickbeam",
    "Radagast",
    "Tom Bombadil",
    "Treebeard",
    # The Hobbit
    "Azog",
    "Balin (Middle-earth)",
    "Bard the Bowman",
    "Beorn",
    "Bolg",
    "Bombur",
    "Dwalin",
    "Fíli and Kíli",
    "Great Goblin",
    "Smaug",
    "Thorin Oakenshield",
    # Silmarillion
    "Beren",
    "Fingolfin",
    "Fëanor",
    "Gothmog",
    "Lúthien",
    "Morgoth",
    "Túrin Turambar",
    "Ungoliant",
]

HARRY_POTTER = [
    # Main trio
    "Harry Potter (character)",
    "Hermione Granger",
    "Ron Weasley",
    # Hogwarts staff
    "Alastor Moody",
    "Albus Dumbledore",
    "Argus Filch",
    "Dolores Umbridge",
    "Filius Flitwick",
    "Firenze (Harry Potter)",
    "Gilderoy Lockhart",
    "Horace Slughorn",
    "Madam Hooch",
    "Madam Pomfrey",
    "Minerva McGonagall",
    "Pomona Sprout",
    "Professor Binns",
    "Quirinus Quirrell",
    "Remus Lupin",
    "Rubeus Hagrid",
    "Rubeus Hagrid",
    "Severus Snape",
    "Sybill Trelawney",
    # Students
    "Angelina Johnson",
    "Blaise Zabini",
    "Cedric Diggory",
    "Cho Chang",
    "Colin Creevey",
    "Cormac McLaggen",
    "Crabbe and Goyle",
    "Dean Thomas",
    "Draco Malfoy",
    "Fred and George Weasley",
    "Ginny Weasley",
    "Katie Bell",
    "Lavender Brown",
    "Lee Jordan",
    "Luna Lovegood",
    "Neville Longbottom",
    "Oliver Wood",
    "Pansy Parkinson",
    "Parvati Patil",
    "Seamus Finnigan",
    # Order of the Phoenix
    "Aberforth Dumbledore",
    "Arthur Weasley",
    "Bill Weasley",
    "Charlie Weasley",
    "Kingsley Shacklebolt",
    "Molly Weasley",
    "Mundungus Fletcher",
    "Nymphadora Tonks",
    "Percy Weasley",
    "Sirius Black",
    # Death Eaters & villains
    "Antonin Dolohov",
    "Barty Crouch Jr.",
    "Bellatrix Lestrange",
    "Corban Yaxley",
    "Fenrir Greyback",
    "Lord Voldemort",
    "Lucius Malfoy",
    "Narcissa Malfoy",
    "Peter Pettigrew",
    "Regulus Black",
    # Magical creatures & beings
    "Aragog",
    "Buckbeak",
    "Dobby (Harry Potter)",
    "Fawkes (Harry Potter)",
    "Fluffy (Harry Potter)",
    "Hedwig (Harry Potter)",
    "Kreacher",
    "Moaning Myrtle",
    "Nagini",
    "Nearly Headless Nick",
    "Norbert (Harry Potter)",
    "Peeves (Harry Potter)",
    "The Bloody Baron",
    # Other
    "Cornelius Fudge",
    "Dudley Dursley",
    "Fleur Delacour",
    "Griphook",
    "Newt Scamander",
    "Ollivander",
    "Rita Skeeter",
    "Rufus Scrimgeour",
    "Vernon Dursley",
    "Viktor Krum",
]

DISNEY = [
    # Classic characters
    "Chip 'n' Dale",
    "Daisy Duck",
    "Donald Duck",
    "Goofy",
    "Huey, Dewey, and Louie",
    "Mickey Mouse",
    "Minnie Mouse",
    "Pluto (Disney)",
    "Scrooge McDuck",
    # Classic films
    "Alice (Alice in Wonderland)",
    "Aurora (Sleeping Beauty)",
    "Baloo",
    "Bambi (character)",
    "Captain Hook",
    "Cheshire Cat",
    "Cruella de Vil",
    "Dumbo",
    "Eeyore",
    "King Louie",
    "Lady (Lady and the Tramp)",
    "Maleficent",
    "Mowgli",
    "Peter Pan (character)",
    "Piglet (Winnie-the-Pooh)",
    "Pinocchio (character)",
    "Pongo (101 Dalmatians)",
    "Robin Hood (Disney character)",
    "Shere Khan",
    "Sleeping Beauty",
    "Snow White (Disney character)",
    "Thumper (Bambi)",
    "Tigger",
    "Tinker Bell",
    "Tramp (Lady and the Tramp)",
    "Winnie-the-Pooh (character)",
    # Renaissance
    "Aladdin (character)",
    "Ariel (The Little Mermaid)",
    "Beast (Beauty and the Beast)",
    "Belle (Beauty and the Beast)",
    "Cogsworth",
    "Gaston (Beauty and the Beast)",
    "Genie (Aladdin)",
    "Hades (Disney)",
    "Hercules (Disney character)",
    "Jafar",
    "Jasmine (Aladdin)",
    "Lumière",
    "Mufasa",
    "Mulan (character)",
    "Mushu",
    "Nala (The Lion King)",
    "Pocahontas (character)",
    "Prince Eric",
    "Quasimodo",
    "Rafiki",
    "Scar (The Lion King)",
    "Sebastian (The Little Mermaid)",
    "Simba",
    "Tarzan (character)",
    "Timon and Pumbaa",
    "Ursula (The Little Mermaid)",
    "Zazu",
    # Modern Disney
    "Anna (Frozen)",
    "Bruno Madrigal",
    "Elsa (Frozen)",
    "Flynn Rider",
    "Hans (Frozen)",
    "Kristoff (Frozen)",
    "Maui (Moana)",
    "Mirabel Madrigal",
    "Moana (character)",
    "Mother Gothel",
    "Olaf (Frozen)",
    "Rapunzel",
    "Raya (Raya and the Last Dragon)",
    "Sven (Frozen)",
    "Tamatoa",
    "Vanellope von Schweetz",
    "Wreck-It Ralph",
    # Pixar
    "Bing Bong (Inside Out)",
    "Boo (Monsters, Inc.)",
    "Buzz Lightyear",
    "Carl Fredricksen",
    "Dory (Finding Nemo)",
    "Dug (Up)",
    "EVE (WALL-E)",
    "Jessie (Toy Story)",
    "Joy (Inside Out)",
    "Lightning McQueen",
    "Marlin (Finding Nemo)",
    "Mater (Cars)",
    "Merida (Brave)",
    "Miguel Rivera",
    "Mike Wazowski",
    "Mr. Potato Head",
    "Nemo (Finding Nemo)",
    "Remy (Ratatouille)",
    "Rex (Toy Story)",
    "Russell (Up)",
    "Sadness (Inside Out)",
    "Sulley (Monsters, Inc.)",
    "WALL-E (character)",
    "Woody (Toy Story)",
    # Villains
    "Baymax",
    "Captain Hook",
    "Gaston (Beauty and the Beast)",
    "Hades (Disney)",
    "Jafar",
    "Queen of Hearts (Alice in Wonderland)",
    "Scar (The Lion King)",
    "Stitch (Lilo & Stitch)",
]

MARVEL = [
    # Avengers
    "Ant-Man",
    "Black Panther (Marvel Comics)",
    "Black Widow (Marvel Comics)",
    "Captain America",
    "Captain Marvel (Marvel Comics)",
    "Doctor Strange",
    "Falcon (Marvel Comics)",
    "Hawkeye (Clint Barton)",
    "Hulk",
    "Iron Man",
    "Quicksilver (Marvel Comics)",
    "Scarlet Witch",
    "She-Hulk",
    "Spider-Man",
    "Thor (Marvel Comics)",
    "Vision (Marvel Comics)",
    "War Machine",
    "Wasp (Marvel Comics)",
    "Winter Soldier",
    # Guardians of the Galaxy
    "Drax the Destroyer",
    "Gamora",
    "Groot",
    "Mantis (Marvel Comics)",
    "Nebula (Marvel Comics)",
    "Rocket Raccoon",
    "Star-Lord",
    "Yondu",
    # X-Men
    "Angel (Marvel Comics)",
    "Apocalypse (character)",
    "Banshee (Marvel Comics)",
    "Beast (Marvel Comics)",
    "Bishop (Marvel Comics)",
    "Cable (character)",
    "Colossus (character)",
    "Cyclops (Marvel Comics)",
    "Dark Phoenix",
    "Emma Frost",
    "Gambit (Marvel Comics)",
    "Iceman (Marvel Comics)",
    "Jean Grey",
    "Jubilee (Marvel Comics)",
    "Kitty Pryde",
    "Magneto (Marvel Comics)",
    "Mystique (character)",
    "Nightcrawler (Marvel Comics)",
    "Professor X",
    "Psylocke",
    "Rogue (Marvel Comics)",
    "Sentinel (comics)",
    "Storm (Marvel Comics)",
    "Wolverine (character)",
    # Spider-verse
    "Carnage (character)",
    "Doctor Octopus",
    "Electro (Marvel Comics)",
    "Green Goblin",
    "Gwen Stacy",
    "J. Jonah Jameson",
    "Kingpin (character)",
    "Kraven the Hunter",
    "Mary Jane Watson",
    "Miles Morales",
    "Mysterio",
    "Sandman (Marvel Comics)",
    "Spider-Man 2099",
    "Venom (character)",
    "Vulture (Marvel Comics)",
    # Other heroes
    "Blade (character)",
    "Daredevil (Marvel Comics character)",
    "Deadpool",
    "Elektra (character)",
    "Ghost Rider",
    "Iron Fist (Marvel Comics)",
    "Jessica Jones",
    "Kate Bishop",
    "Luke Cage",
    "Moon Knight",
    "Ms. Marvel",
    "Namor",
    "Nova (Richard Rider)",
    "Punisher",
    "Shang-Chi",
    "Silver Surfer",
    # Villains
    "Baron Zemo",
    "Doctor Doom",
    "Dormammu",
    "Galactus",
    "Hela (character)",
    "Kang the Conqueror",
    "Killmonger",
    "Loki (Marvel Comics)",
    "MODOK",
    "Mysterio",
    "Red Skull",
    "Taskmaster (character)",
    "Thanos",
    "Ultron",
    # Supporting
    "Aunt May",
    "Happy Hogan",
    "Nick Fury",
    "Okoye (character)",
    "Pepper Potts",
    "Phil Coulson",
    "Wong (Marvel Comics)",
]

DC = [
    # Justice League
    "Aquaman",
    "Batman",
    "Cyborg (DC Comics)",
    "Green Lantern",
    "Hawkgirl",
    "Hawkman",
    "Martian Manhunter",
    "Superman",
    "The Flash",
    "Wonder Woman",
    # Batman family
    "Alfred Pennyworth",
    "Barbara Gordon",
    "Batgirl",
    "Commissioner Gordon",
    "Damian Wayne",
    "Lucius Fox",
    "Nightwing",
    "Red Hood",
    "Robin (character)",
    "Tim Drake",
    # Batman villains
    "Bane (DC Comics)",
    "Catwoman",
    "Clayface",
    "Deathstroke",
    "Harley Quinn",
    "Hugo Strange",
    "Hush (character)",
    "Joker (character)",
    "Killer Croc",
    "Mad Hatter (DC Comics)",
    "Mr. Freeze",
    "Penguin (character)",
    "Poison Ivy (character)",
    "Ra's al Ghul",
    "Riddler",
    "Scarecrow (DC Comics)",
    "Talia al Ghul",
    "Two-Face",
    "Victor Zsasz",
    # Superman family & villains
    "Bizarro",
    "Brainiac (character)",
    "Darkseid",
    "Doomsday (DC Comics)",
    "General Zod",
    "Jimmy Olsen",
    "Lex Luthor",
    "Lois Lane",
    "Metallo",
    "Parasite (comics)",
    "Supergirl",
    # Other heroes
    "Black Adam",
    "Black Canary",
    "Blue Beetle",
    "Booster Gold",
    "Constantine (character)",
    "Doctor Fate",
    "Firestorm (character)",
    "Green Arrow",
    "Plastic Man",
    "Shazam (character)",
    "Static (DC Comics)",
    "Swamp Thing",
    "The Atom (Ray Palmer)",
    "Zatanna",
    # Teen Titans
    "Beast Boy",
    "Cyborg (DC Comics)",
    "Raven (DC Comics)",
    "Starfire (Teen Titans)",
    "Terra (character)",
    # Villains
    "Anti-Monitor",
    "Ares (DC Comics)",
    "Black Manta",
    "Captain Cold",
    "Cheetah (character)",
    "Circe (DC Comics)",
    "Darkseid",
    "Gorilla Grodd",
    "Ocean Master",
    "Reverse-Flash",
    "Sinestro",
    # Vertigo / other
    "Death (DC Comics)",
    "Dream (character)",
    "Lucifer (DC Comics)",
    "Sandman (DC Comics)",
]

ANIME = [
    "All Might",
    "Ash Ketchum",
    "Astro Boy",
    "Dio Brando",
    "Doraemon",
    "Edward Elric",
    "Eren Yeager",
    "Goku",
    "Gon Freecss",
    "Griffith (Berserk)",
    "Guts (Berserk)",
    "Ichigo Kurosaki",
    "Inuyasha (character)",
    "Itachi Uchiha",
    "Izuku Midoriya",
    "Jotaro Kujo",
    "Kakashi Hatake",
    "Killua Zoldyck",
    "L (Death Note)",
    "Levi Ackerman",
    "Light Yagami",
    "Mikasa Ackerman",
    "Monkey D. Luffy",
    "Naruto Uzumaki",
    "Nezuko Kamado",
    "Pikachu",
    "Princess Mononoke (character)",
    "Roronoa Zoro",
    "Sailor Moon (character)",
    "Saitama (One-Punch Man)",
    "Sasuke Uchiha",
    "Shin-chan",
    "Spike Spiegel",
    "Spirited Away",
    "Tanjiro Kamado",
    "Totoro",
    "Tuxedo Mask",
    "Vegeta",
]

ALL = STAR_WARS + LORD_OF_THE_RINGS + HARRY_POTTER + DISNEY + MARVEL + DC + ANIME
