STAR_WARS = [
    # Original trilogy
    "Luke Skywalker", "Darth Vader", "Leia Organa",
    "Han Solo", "Chewbacca", "Yoda", "Obi-Wan Kenobi",
    "Emperor Palpatine", "R2-D2", "C-3PO",
    "Boba Fett", "Jabba the Hutt", "Lando Calrissian",
    "Grand Moff Tarkin", "Admiral Ackbar", "Wedge Antilles",
    "Wicket W. Warrick", "Nien Nunb", "Mon Mothma",
    "Greedo", "Bossk", "IG-88", "Dengar",
    "Lobot", "Max Rebo", "Salacious B. Crumb",
    "Figrin D'an", "Bib Fortuna",
    # Prequel trilogy
    "Anakin Skywalker", "Padmé Amidala", "Qui-Gon Jinn",
    "Darth Maul", "Mace Windu", "Count Dooku",
    "General Grievous", "Jango Fett", "Jar Jar Binks",
    "Watto", "Sebulba", "Shmi Skywalker",
    "Ki-Adi-Mundi", "Aayla Secura", "Plo Koon",
    "Kit Fisto", "Shaak Ti", "Luminara Unduli",
    "Barriss Offee", "Zam Wesell", "Dexter Jettster",
    "Captain Typho", "Bail Organa", "Nute Gunray",
    # Sequel trilogy
    "Kylo Ren", "Rey (Star Wars)", "Finn (Star Wars)",
    "Poe Dameron", "BB-8", "Supreme Leader Snoke",
    "Rose Tico", "Maz Kanata", "General Hux",
    "Captain Phasma", "DJ (Star Wars)", "Zorii Bliss",
    "Jannah (Star Wars)", "Pryde",
    # Clone Wars & Rebels
    "Ahsoka Tano", "Captain Rex", "Asajj Ventress",
    "Cad Bane", "Savage Opress", "Pre Vizsla",
    "Bo-Katan Kryze", "Satine Kryze",
    "Hera Syndulla", "Kanan Jarrus", "Ezra Bridger",
    "Sabine Wren", "Chopper (Star Wars)", "Grand Admiral Thrawn",
    "Grand Inquisitor",
    # Mandalorian & other shows
    "The Mandalorian (character)", "Grogu",
    "Cara Dune", "Greef Karga", "Moff Gideon",
    "Fennec Shand", "Cobb Vanth",
    "Cassian Andor", "K-2SO", "Chirrut Îmwe", "Baze Malbus",
    "Jyn Erso", "Orson Krennic",
    "Cal Kestis", "Inquisitor (Star Wars)",
]

LORD_OF_THE_RINGS = [
    "Frodo Baggins", "Gandalf", "Aragorn",
    "Legolas", "Gimli (Middle-earth)", "Samwise Gamgee",
    "Gollum", "Sauron", "Saruman",
    "Boromir", "Faramir", "Éowyn",
    "Théoden", "Éomer", "Treebeard",
    "Elrond", "Galadriel", "Arwen",
    "Bilbo Baggins", "Merry Brandybuck", "Pippin Took",
    "Tom Bombadil", "Radagast",
    "Witch-king of Angmar", "Shelob",
    "Sméagol", "Denethor", "Wormtongue",
    "Balrog", "Glorfindel", "Celeborn",
    "Thranduil", "Thorin Oakenshield",
    "Balin (Middle-earth)", "Bard the Bowman",
    "Smaug", "Beorn",
]

HARRY_POTTER = [
    "Harry Potter (character)", "Hermione Granger", "Ron Weasley",
    "Albus Dumbledore", "Lord Voldemort", "Severus Snape",
    "Rubeus Hagrid", "Draco Malfoy", "Sirius Black",
    "Remus Lupin", "Neville Longbottom", "Luna Lovegood",
    "Ginny Weasley", "Fred and George Weasley",
    "Minerva McGonagall", "Bellatrix Lestrange",
    "Dolores Umbridge", "Dobby (Harry Potter)",
    "Lucius Malfoy", "Nymphadora Tonks",
    "Alastor Moody", "Cedric Diggory",
    "Cho Chang", "Gilderoy Lockhart",
    "Horace Slughorn", "Molly Weasley", "Arthur Weasley",
    "Peter Pettigrew", "Quirinus Quirrell",
    "Sybill Trelawney", "Filius Flitwick",
    "Pomona Sprout", "Hedwig (Harry Potter)",
    "Kreacher", "Nagini",
]

DISNEY = [
    "Mickey Mouse", "Minnie Mouse", "Donald Duck", "Goofy",
    "Pluto (Disney)", "Bambi (character)", "Dumbo",
    "Pinocchio (character)", "Snow White (Disney character)",
    "Cinderella (Disney character)", "Aurora (Sleeping Beauty)",
    "Ariel (The Little Mermaid)", "Belle (Beauty and the Beast)",
    "Jasmine (Aladdin)", "Pocahontas (character)", "Mulan (character)",
    "Rapunzel", "Moana (character)", "Elsa (Frozen)",
    "Anna (Frozen)", "Simba", "Mufasa", "Scar (The Lion King)",
    "Timon and Pumbaa", "Nemo (Finding Nemo)", "Dory (Finding Nemo)",
    "Buzz Lightyear", "Woody (Toy Story)", "Sulley (Monsters, Inc.)",
    "Mike Wazowski", "WALL-E (character)",
    "Aladdin (character)", "Genie (Aladdin)",
    "Maleficent", "Ursula (The Little Mermaid)",
    "Cruella de Vil", "Captain Hook",
    "Stitch (Lilo & Stitch)", "Baymax",
    "Maui (Moana)", "Olaf (Frozen)",
]

MARVEL = [
    "Spider-Man", "Iron Man", "Captain America",
    "Thor (Marvel Comics)", "Hulk", "Black Widow (Marvel Comics)",
    "Wolverine (character)", "Black Panther (Marvel Comics)",
    "Doctor Strange", "Captain Marvel (Marvel Comics)",
    "Scarlet Witch", "Vision (Marvel Comics)",
    "Ant-Man", "Hawkeye (Clint Barton)",
    "Groot", "Rocket Raccoon", "Star-Lord",
    "Gamora", "Drax the Destroyer", "Nebula (Marvel Comics)",
    "Thanos", "Loki (Marvel Comics)",
    "Magneto (Marvel Comics)", "Professor X",
    "Cyclops (Marvel Comics)", "Storm (Marvel Comics)",
    "Jean Grey", "Mystique (character)",
    "Deadpool", "Venom (character)",
    "Daredevil (Marvel Comics character)", "Punisher",
    "Nick Fury", "War Machine",
    "Falcon (Marvel Comics)", "Winter Soldier",
    "Shang-Chi", "Moon Knight",
    "Ms. Marvel", "Kate Bishop",
]

DC = [
    "Superman", "Batman", "Wonder Woman",
    "The Flash", "Aquaman", "Green Lantern",
    "Cyborg (DC Comics)", "Martian Manhunter",
    "Batgirl", "Robin (character)", "Nightwing",
    "Supergirl", "Catwoman", "Harley Quinn",
    "Joker (character)", "Lex Luthor", "Darkseid",
    "Bane (DC Comics)", "Riddler", "Penguin (character)",
    "Two-Face", "Poison Ivy (character)", "Mr. Freeze",
    "Scarecrow (DC Comics)", "Ra's al Ghul",
    "Deathstroke", "Black Adam",
    "Shazam (character)", "Green Arrow",
    "Zatanna", "Constantine (character)",
    "Swamp Thing", "Alfred Pennyworth",
    "Commissioner Gordon", "Lois Lane",
]

ANIME = [
    "Goku", "Vegeta", "Naruto Uzumaki", "Sasuke Uchiha",
    "Monkey D. Luffy", "Roronoa Zoro",
    "Pikachu", "Ash Ketchum",
    "Sailor Moon (character)", "Tuxedo Mask",
    "Spike Spiegel", "Edward Elric",
    "Light Yagami", "L (Death Note)",
    "Eren Yeager", "Mikasa Ackerman", "Levi Ackerman",
    "Gon Freecss", "Killua Zoldyck",
    "Saitama (One-Punch Man)", "Tanjiro Kamado",
    "Nezuko Kamado", "Totoro",
    "Spirited Away", "Princess Mononoke (character)",
    "Astro Boy", "Doraemon", "Shin-chan",
    "Inuyasha (character)", "Ichigo Kurosaki",
    "Jotaro Kujo", "Dio Brando",
    "Itachi Uchiha", "Kakashi Hatake",
    "All Might", "Izuku Midoriya",
    "Guts (Berserk)", "Griffith (Berserk)",
]

ALL = STAR_WARS + LORD_OF_THE_RINGS + HARRY_POTTER + DISNEY + MARVEL + DC + ANIME
