CAPITALS = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Algeria": "Algiers",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Antigua and Barbuda": "St. John's",
    "Argentina": "Buenos Aires",
    "Armenia": "Yerevan",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Azerbaijan": "Baku",
    "Bahamas": "Nassau",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Barbados": "Bridgetown",
    "Belarus": "Minsk",
    "Belgium": "Brussels",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bhutan": "Thimphu",
    "Bolivia": "Sucre",
    "Bosnia and Herzegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Brazil": "Brasilia",
    "Brunei": "Bandar Seri Begawan",
    "Bulgaria": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Cambodia": "Phnom Penh",
    "Cameroon": "Yaoundé",
    "Canada": "Ottawa",
    "Cape Verde": "Praia",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Chile": "Santiago",
    "China": "Beijing",
    "Colombia": "Bogotá",
    "Comoros": "Moroni",
    "Costa Rica": "San José",
    "Croatia": "Zagreb",
    "Cuba": "Havana",
    "Cyprus": "Nicosia",
    "Czech Republic": "Prague",
    "Democratic Republic of the Congo": "Kinshasa",
    "Denmark": "Copenhagen",
    "Djibouti": "Djibouti City",
    "Dominica": "Roseau",
    "Dominican Republic": "Santo Domingo",
    "East Timor": "Dili",
    "Ecuador": "Quito",
    "Egypt": "Cairo",
    "El Salvador": "San Salvador",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Estonia": "Tallinn",
    "Eswatini": "Mbabane",
    "Ethiopia": "Addis Ababa",
    "Fiji": "Suva",
    "Finland": "Helsinki",
    "France": "Paris",
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Georgia (country)": "Tbilisi",
    "Germany": "Berlin",
    "Ghana": "Accra",
    "Greece": "Athens",
    "Grenada": "St. George's",
    "Guatemala": "Guatemala City",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Hungary": "Budapest",
    "Iceland": "Reykjavik",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Israel": "Jerusalem",
    "Italy": "Rome",
    "Ivory Coast": "Yamoussoukro",
    "Jamaica": "Kingston",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kenya": "Nairobi",
    "Kiribati": "Tarawa",
    "Kosovo": "Pristina",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Latvia": "Riga",
    "Lebanon": "Beirut",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg City",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaysia": "Kuala Lumpur",
    "Maldives": "Malé",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshall Islands": "Majuro",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Mexico": "Mexico City",
    "Micronesia (country)": "Palikir",
    "Moldova": "Chișinău",
    "Monaco": "Monaco",
    "Mongolia": "Ulaanbaatar",
    "Montenegro": "Podgorica",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Myanmar": "Naypyidaw",
    "Namibia": "Windhoek",
    "Nauru": "Yaren",
    "Nepal": "Kathmandu",
    "Netherlands": "Amsterdam",
    "New Zealand": "Wellington",
    "Nicaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "North Korea": "Pyongyang",
    "North Macedonia": "Skopje",
    "Norway": "Oslo",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Palau": "Ngerulmud",
    "Palestine": "Ramallah",
    "Panama": "Panama City",
    "Papua New Guinea": "Port Moresby",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Qatar": "Doha",
    "Republic of the Congo": "Brazzaville",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "Rwanda": "Kigali",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Vincent and the Grenadines": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "San Marino",
    "São Tomé and Príncipe": "São Tomé",
    "Saudi Arabia": "Riyadh",
    "Senegal": "Dakar",
    "Serbia": "Belgrade",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapore": "Singapore",
    "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana",
    "Solomon Islands": "Honiara",
    "Somalia": "Mogadishu",
    "South Africa": "Pretoria",
    "South Korea": "Seoul",
    "South Sudan": "Juba",
    "Spain": "Madrid",
    "Sri Lanka": "Sri Jayawardenepura Kotte",
    "Sudan": "Khartoum",
    "Suriname": "Paramaribo",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Syria": "Damascus",
    "Taiwan": "Taipei",
    "Tajikistan": "Dushanbe",
    "Tanzania": "Dodoma",
    "Thailand": "Bangkok",
    "Togo": "Lomé",
    "Tonga": "Nukuʻalofa",
    "Trinidad and Tobago": "Port of Spain",
    "Tunisia": "Tunis",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "Tuvalu": "Funafuti",
    "Uganda": "Kampala",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington, D.C.",
    "Uruguay": "Montevideo",
    "Uzbekistan": "Tashkent",
    "Vanuatu": "Port Vila",
    "Vatican City": "Vatican City",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoi",
    "Yemen": "Sana'a",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare",
}

CURRENCIES = {
    "Afghanistan": "Afghan afghani (AFN)",
    "Albania": "Albanian lek (ALL)",
    "Algeria": "Algerian dinar (DZD)",
    "Andorra": "Euro (EUR)",
    "Angola": "Angolan kwanza (AOA)",
    "Antigua and Barbuda": "East Caribbean dollar (XCD)",
    "Argentina": "Argentine peso (ARS)",
    "Armenia": "Armenian dram (AMD)",
    "Australia": "Australian dollar (AUD)",
    "Austria": "Euro (EUR)",
    "Azerbaijan": "Azerbaijani manat (AZN)",
    "Bahamas": "Bahamian dollar (BSD)",
    "Bahrain": "Bahraini dinar (BHD)",
    "Bangladesh": "Bangladeshi taka (BDT)",
    "Barbados": "Barbadian dollar (BBD)",
    "Belarus": "Belarusian ruble (BYN)",
    "Belgium": "Euro (EUR)",
    "Belize": "Belize dollar (BZD)",
    "Benin": "West African CFA franc (XOF)",
    "Bhutan": "Bhutanese ngultrum (BTN)",
    "Bolivia": "Bolivian boliviano (BOB)",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina convertible mark (BAM)",
    "Botswana": "Botswana pula (BWP)",
    "Brazil": "Brazilian real (BRL)",
    "Brunei": "Brunei dollar (BND)",
    "Bulgaria": "Bulgarian lev (BGN)",
    "Burkina Faso": "West African CFA franc (XOF)",
    "Burundi": "Burundian franc (BIF)",
    "Cambodia": "Cambodian riel (KHR)",
    "Cameroon": "Central African CFA franc (XAF)",
    "Canada": "Canadian dollar (CAD)",
    "Cape Verde": "Cape Verdean escudo (CVE)",
    "Central African Republic": "Central African CFA franc (XAF)",
    "Chad": "Central African CFA franc (XAF)",
    "Chile": "Chilean peso (CLP)",
    "China": "Chinese yuan (CNY)",
    "Colombia": "Colombian peso (COP)",
    "Comoros": "Comorian franc (KMF)",
    "Costa Rica": "Costa Rican colón (CRC)",
    "Croatia": "Euro (EUR)",
    "Cuba": "Cuban peso (CUP)",
    "Cyprus": "Euro (EUR)",
    "Czech Republic": "Czech koruna (CZK)",
    "Democratic Republic of the Congo": "Congolese franc (CDF)",
    "Denmark": "Danish krone (DKK)",
    "Djibouti": "Djiboutian franc (DJF)",
    "Dominica": "East Caribbean dollar (XCD)",
    "Dominican Republic": "Dominican peso (DOP)",
    "East Timor": "United States dollar (USD)",
    "Ecuador": "United States dollar (USD)",
    "Egypt": "Egyptian pound (EGP)",
    "El Salvador": "United States dollar (USD)",
    "Equatorial Guinea": "Central African CFA franc (XAF)",
    "Eritrea": "Eritrean nakfa (ERN)",
    "Estonia": "Euro (EUR)",
    "Eswatini": "Swazi lilangeni (SZL)",
    "Ethiopia": "Ethiopian birr (ETB)",
    "Fiji": "Fijian dollar (FJD)",
    "Finland": "Euro (EUR)",
    "France": "Euro (EUR)",
    "Gabon": "Central African CFA franc (XAF)",
    "Gambia": "Gambian dalasi (GMD)",
    "Georgia (country)": "Georgian lari (GEL)",
    "Germany": "Euro (EUR)",
    "Ghana": "Ghanaian cedi (GHS)",
    "Greece": "Euro (EUR)",
    "Grenada": "East Caribbean dollar (XCD)",
    "Guatemala": "Guatemalan quetzal (GTQ)",
    "Guinea": "Guinean franc (GNF)",
    "Guinea-Bissau": "West African CFA franc (XOF)",
    "Guyana": "Guyanese dollar (GYD)",
    "Haiti": "Haitian gourde (HTG)",
    "Honduras": "Honduran lempira (HNL)",
    "Hungary": "Hungarian forint (HUF)",
    "Iceland": "Icelandic króna (ISK)",
    "India": "Indian rupee (INR)",
    "Indonesia": "Indonesian rupiah (IDR)",
    "Iran": "Iranian rial (IRR)",
    "Iraq": "Iraqi dinar (IQD)",
    "Ireland": "Euro (EUR)",
    "Israel": "Israeli new shekel (ILS)",
    "Italy": "Euro (EUR)",
    "Ivory Coast": "West African CFA franc (XOF)",
    "Jamaica": "Jamaican dollar (JMD)",
    "Japan": "Japanese yen (JPY)",
    "Jordan": "Jordanian dinar (JOD)",
    "Kazakhstan": "Kazakhstani tenge (KZT)",
    "Kenya": "Kenyan shilling (KES)",
    "Kiribati": "Australian dollar (AUD)",
    "Kosovo": "Euro (EUR)",
    "Kuwait": "Kuwaiti dinar (KWD)",
    "Kyrgyzstan": "Kyrgyzstani som (KGS)",
    "Laos": "Lao kip (LAK)",
    "Latvia": "Euro (EUR)",
    "Lebanon": "Lebanese pound (LBP)",
    "Lesotho": "Lesotho loti (LSL)",
    "Liberia": "Liberian dollar (LRD)",
    "Libya": "Libyan dinar (LYD)",
    "Liechtenstein": "Swiss franc (CHF)",
    "Lithuania": "Euro (EUR)",
    "Luxembourg": "Euro (EUR)",
    "Madagascar": "Malagasy ariary (MGA)",
    "Malawi": "Malawian kwacha (MWK)",
    "Malaysia": "Malaysian ringgit (MYR)",
    "Maldives": "Maldivian rufiyaa (MVR)",
    "Mali": "West African CFA franc (XOF)",
    "Malta": "Euro (EUR)",
    "Marshall Islands": "United States dollar (USD)",
    "Mauritania": "Mauritanian ouguiya (MRU)",
    "Mauritius": "Mauritian rupee (MUR)",
    "Mexico": "Mexican peso (MXN)",
    "Micronesia (country)": "United States dollar (USD)",
    "Moldova": "Moldovan leu (MDL)",
    "Monaco": "Euro (EUR)",
    "Mongolia": "Mongolian tögrög (MNT)",
    "Montenegro": "Euro (EUR)",
    "Morocco": "Moroccan dirham (MAD)",
    "Mozambique": "Mozambican metical (MZN)",
    "Myanmar": "Myanmar kyat (MMK)",
    "Namibia": "Namibian dollar (NAD)",
    "Nauru": "Australian dollar (AUD)",
    "Nepal": "Nepalese rupee (NPR)",
    "Netherlands": "Euro (EUR)",
    "New Zealand": "New Zealand dollar (NZD)",
    "Nicaragua": "Nicaraguan córdoba (NIO)",
    "Niger": "West African CFA franc (XOF)",
    "Nigeria": "Nigerian naira (NGN)",
    "North Korea": "North Korean won (KPW)",
    "North Macedonia": "Macedonian denar (MKD)",
    "Norway": "Norwegian krone (NOK)",
    "Oman": "Omani rial (OMR)",
    "Pakistan": "Pakistani rupee (PKR)",
    "Palau": "United States dollar (USD)",
    "Palestine": "Israeli new shekel (ILS)",
    "Panama": "Panamanian balboa (PAB)",
    "Papua New Guinea": "Papua New Guinean kina (PGK)",
    "Paraguay": "Paraguayan guaraní (PYG)",
    "Peru": "Peruvian sol (PEN)",
    "Philippines": "Philippine peso (PHP)",
    "Poland": "Polish złoty (PLN)",
    "Portugal": "Euro (EUR)",
    "Qatar": "Qatari riyal (QAR)",
    "Republic of the Congo": "Central African CFA franc (XAF)",
    "Romania": "Romanian leu (RON)",
    "Russia": "Russian ruble (RUB)",
    "Rwanda": "Rwandan franc (RWF)",
    "Saint Kitts and Nevis": "East Caribbean dollar (XCD)",
    "Saint Lucia": "East Caribbean dollar (XCD)",
    "Saint Vincent and the Grenadines": "East Caribbean dollar (XCD)",
    "Samoa": "Samoan tālā (WST)",
    "San Marino": "Euro (EUR)",
    "São Tomé and Príncipe": "São Tomé and Príncipe dobra (STN)",
    "Saudi Arabia": "Saudi riyal (SAR)",
    "Senegal": "West African CFA franc (XOF)",
    "Serbia": "Serbian dinar (RSD)",
    "Seychelles": "Seychellois rupee (SCR)",
    "Sierra Leone": "Sierra Leonean leone (SLE)",
    "Singapore": "Singapore dollar (SGD)",
    "Slovakia": "Euro (EUR)",
    "Slovenia": "Euro (EUR)",
    "Solomon Islands": "Solomon Islands dollar (SBD)",
    "Somalia": "Somali shilling (SOS)",
    "South Africa": "South African rand (ZAR)",
    "South Korea": "South Korean won (KRW)",
    "South Sudan": "South Sudanese pound (SSP)",
    "Spain": "Euro (EUR)",
    "Sri Lanka": "Sri Lankan rupee (LKR)",
    "Sudan": "Sudanese pound (SDG)",
    "Suriname": "Surinamese dollar (SRD)",
    "Sweden": "Swedish krona (SEK)",
    "Switzerland": "Swiss franc (CHF)",
    "Syria": "Syrian pound (SYP)",
    "Taiwan": "New Taiwan dollar (TWD)",
    "Tajikistan": "Tajikistani somoni (TJS)",
    "Tanzania": "Tanzanian shilling (TZS)",
    "Thailand": "Thai baht (THB)",
    "Togo": "West African CFA franc (XOF)",
    "Tonga": "Tongan paʻanga (TOP)",
    "Trinidad and Tobago": "Trinidad and Tobago dollar (TTD)",
    "Tunisia": "Tunisian dinar (TND)",
    "Turkey": "Turkish lira (TRY)",
    "Turkmenistan": "Turkmenistan manat (TMT)",
    "Tuvalu": "Australian dollar (AUD)",
    "Uganda": "Ugandan shilling (UGX)",
    "Ukraine": "Ukrainian hryvnia (UAH)",
    "United Arab Emirates": "United Arab Emirates dirham (AED)",
    "United Kingdom": "Pound sterling (GBP)",
    "United States": "United States dollar (USD)",
    "Uruguay": "Uruguayan peso (UYU)",
    "Uzbekistan": "Uzbekistani sum (UZS)",
    "Vanuatu": "Vanuatu vatu (VUV)",
    "Vatican City": "Euro (EUR)",
    "Venezuela": "Venezuelan bolívar (VES)",
    "Vietnam": "Vietnamese đồng (VND)",
    "Yemen": "Yemeni rial (YER)",
    "Zambia": "Zambian kwacha (ZMW)",
    "Zimbabwe": "Zimbabwe Gold (ZiG)",
}

CONTINENTS = {
    "africa": [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Republic of the Congo",
        "Rwanda",
        "São Tomé and Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ],
    "america": [
        "Antigua and Barbuda",
        "Argentina",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bolivia",
        "Brazil",
        "Canada",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "Grenada",
        "Guatemala",
        "Guyana",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Mexico",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Suriname",
        "Trinidad and Tobago",
        "United States",
        "Uruguay",
        "Venezuela",
    ],
    "asia": [
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China",
        "East Timor",
        "Georgia (country)",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North Korea",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkey",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen",
    ],
    "europe": [
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom",
        "Vatican City",
    ],
    "oceania": [
        "Australia",
        "Fiji",
        "Kiribati",
        "Marshall Islands",
        "Micronesia (country)",
        "Nauru",
        "New Zealand",
        "Palau",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
    ],
}

ALL = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia (country)",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia (country)",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Republic of the Congo",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "São Tomé and Príncipe",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
