ALL = [
    # Theropods
    "Tyrannosaurus",
    "Velociraptor",
    "Allosaurus",
    "Spinosaurus",
    "Giganotosaurus",
    "Carnotaurus",
    "Dilophosaurus",
    "Compsognathus",
    "Deinonychus",
    "Therizinosaurus",
    "Oviraptor",
    "Baryonyx",
    "Megalosaurus",
    "Ceratosaurus",
    "Coelophysis",
    "Gallimimus",
    "Utahraptor",
    "Microraptor",
    "Archaeopteryx",
    "Herrerasaurus",
    # Sauropods
    "Brachiosaurus",
    "Diplodocus",
    "Apatosaurus",
    "Argentinosaurus",
    "Brontosaurus",
    "Camarasaurus",
    "Titanosaurus",
    "Patagotitan",
    "Amargasaurus",
    "Nigersaurus",
    "Saltasaurus",
    "Mamenchisaurus",
    # Ceratopsians
    "Triceratops",
    "Styracosaurus",
    "Protoceratops",
    "Pachyrhinosaurus",
    "Centrosaurus",
    "Chasmosaurus",
    "Psittacosaurus",
    "Einiosaurus",
    # Ornithopods
    "Iguanodon",
    "Parasaurolophus",
    "Hadrosaurus",
    "Edmontosaurus",
    "Corythosaurus",
    "Lambeosaurus",
    "Maiasaura",
    "Hypsilophodon",
    "Muttaburrasaurus",
    "Tenontosaurus",
    # Thyreophorans (armored)
    "Stegosaurus",
    "Ankylosaurus",
    "Euoplocephalus",
    "Kentrosaurus",
    "Polacanthus",
    "Nodosaurus",
    "Minmi (dinosaur)",
    "Huayangosaurus",
    # Pachycephalosaurs
    "Pachycephalosaurus",
    "Stygimoloch",
    "Dracorex",
    # Pterosaurs (flying reptiles)
    "Pteranodon",
    "Pterodactylus",
    "Quetzalcoatlus",
    "Dimorphodon",
    "Rhamphorhynchus",
    # Marine reptiles
    "Plesiosauria",
    "Mosasaurus",
    "Ichthyosaurus",
    "Elasmosaurus",
    "Liopleurodon",
    "Kronosaurus",
    # Early / other
    "Dimetrodon",
    "Megalania",
    "Sarcosuchus",
    "Smilodon",
    "Woolly mammoth",
    "Megalodon",
]
