"""Musical instruments from around the world."""

STRINGS = [
    # Bowed
    "Violin",
    "Viola",
    "Cello",
    "Double bass",
    "Erhu",
    "Hardingfele",
    "Hurdy-gurdy",
    "Kamancheh",
    "Morin khuur",
    "Nyckelharpa",
    "Rebab",
    "Sarangi",
    # Plucked
    "Acoustic guitar",
    "Balalaika",
    "Banjo",
    "Bouzouki",
    "Charango",
    "Classical guitar",
    "Electric bass guitar",
    "Electric guitar",
    "Guqin",
    "Guzheng",
    "Harp",
    "Kora (instrument)",
    "Koto (instrument)",
    "Lute",
    "Lyre",
    "Mandolin",
    "Oud",
    "Pipa",
    "Shamisen",
    "Sitar",
    "Theorbo",
    "Ukulele",
    "Veena",
    "Zither",
    # Struck
    "Cimbalom",
    "Hammered dulcimer",
    "Piano",
]

WOODWINDS = [
    "Bagpipes",
    "Bassoon",
    "Clarinet",
    "Cor anglais",
    "Didgeridoo",
    "Duduk",
    "Flute",
    "Ney",
    "Oboe",
    "Ocarina",
    "Pan flute",
    "Piccolo (instrument)",
    "Recorder (musical instrument)",
    "Saxophone",
    "Shakuhachi",
    "Shehnai",
    "Tin whistle",
    "Zurna",
]

BRASS = [
    "Bugle",
    "Cornet",
    "Euphonium",
    "Flugelhorn",
    "French horn",
    "Sousaphone",
    "Trombone",
    "Trumpet",
    "Tuba",
    "Vuvuzela",
]

PERCUSSION = [
    "Bass drum",
    "Bodhrán",
    "Bongo drum",
    "Cajón",
    "Castanets",
    "Celesta",
    "Conga",
    "Cymbals",
    "Djembe",
    "Drum kit",
    "Frame drum",
    "Glockenspiel",
    "Gong",
    "Güiro",
    "Maracas",
    "Marimba",
    "Pandeiro",
    "Snare drum",
    "Steelpan",
    "Surdo",
    "Tabla",
    "Taiko",
    "Talking drum",
    "Tambourine",
    "Timpani",
    "Triangle (musical instrument)",
    "Vibraphone",
    "Xylophone",
]

KEYBOARDS = [
    "Accordion",
    "Clavichord",
    "Harpsichord",
    "Melodica",
    "Organ (music)",
    "Pipe organ",
    "Synthesizer",
]

OTHER = [
    "Alphorn",
    "Berimbau",
    "Daf",
    "Drum machine",
    "Gamelan",
    "Hang (instrument)",
    "Jaw harp",
    "Kalimba",
    "Mbira",
    "Moog synthesizer",
    "Theremin",
    "Tongue drum",
]

ALL = STRINGS + WOODWINDS + BRASS + PERCUSSION + KEYBOARDS + OTHER

FAMILIES = {
    "strings": STRINGS,
    "woodwinds": WOODWINDS,
    "brass": BRASS,
    "percussion": PERCUSSION,
    "keyboards": KEYBOARDS,
    "other": OTHER,
}
