LOGOS = {
    "AC Milan": "/static/logos/ac_milan.png",
    "AEK Athens": "/static/logos/aek_athens.png",
    "AS Monaco": "/static/logos/as_monaco.png",
    "AS Roma": "/static/logos/as_roma.png",
    "Ajax": "/static/logos/ajax.png",
    "Anderlecht": "/static/logos/anderlecht.png",
    "Arsenal": "/static/logos/arsenal.png",
    "Aston Villa": "/static/logos/aston_villa.png",
    "Atalanta": "/static/logos/atalanta.png",
    "Athletic Bilbao": "/static/logos/athletic_bilbao.png",
    "Atlanta Hawks": "/static/logos/atlanta_hawks.png",
    "Atletico Madrid": "/static/logos/atletico_madrid.png",
    "Barcelona": "/static/logos/barcelona.png",
    "Bayer Leverkusen": "/static/logos/bayer_leverkusen.png",
    "Bayern Munich": "/static/logos/bayern_munich.png",
    "Benfica": "/static/logos/benfica.png",
    "Besiktas": "/static/logos/besiktas.png",
    "Boca Juniors": "/static/logos/boca_juniors.png",
    "Borussia Dortmund": "/static/logos/borussia_dortmund.png",
    "Borussia Monchengladbach": "/static/logos/borussia_monchengladbach.png",
    "Boston Celtics": "/static/logos/boston_celtics.png",
    "Braga": "/static/logos/braga.png",
    "Brooklyn Nets": "/static/logos/brooklyn_nets.png",
    "CSKA Moscow": "/static/logos/cska_moscow.png",
    "Celtic": "/static/logos/celtic.png",
    "Charlotte Hornets": "/static/logos/charlotte_hornets.png",
    "Chelsea": "/static/logos/chelsea.png",
    "Chicago Bulls": "/static/logos/chicago_bulls.png",
    "Chivas": "/static/logos/chivas.png",
    "Cleveland Cavaliers": "/static/logos/cleveland_cavaliers.png",
    "Club America": "/static/logos/club_america.png",
    "Club Brugge": "/static/logos/club_brugge.png",
    "Corinthians": "/static/logos/corinthians.png",
    "Dallas Mavericks": "/static/logos/dallas_mavericks.png",
    "Denver Nuggets": "/static/logos/denver_nuggets.png",
    "Detroit Pistons": "/static/logos/detroit_pistons.png",
    "Dinamo Zagreb": "/static/logos/dinamo_zagreb.png",
    "Dynamo Kyiv": "/static/logos/dynamo_kyiv.png",
    "Eintracht Frankfurt": "/static/logos/eintracht_frankfurt.png",
    "Everton": "/static/logos/everton.png",
    "FC Basel": "/static/logos/fc_basel.png",
    "Fenerbahce": "/static/logos/fenerbahce.png",
    "Ferencvaros": "/static/logos/ferencvaros.png",
    "Feyenoord": "/static/logos/feyenoord.png",
    "Fiorentina": "/static/logos/fiorentina.png",
    "Flamengo": "/static/logos/flamengo.png",
    "Galatasaray": "/static/logos/galatasaray.png",
    "Golden State Warriors": "/static/logos/golden_state_warriors.png",
    "Hajduk Split": "/static/logos/hajduk_split.png",
    "Houston Rockets": "/static/logos/houston_rockets.png",
    "Indiana Pacers": "/static/logos/indiana_pacers.png",
    "Inter Milan": "/static/logos/inter_milan.png",
    "Juventus": "/static/logos/juventus.png",
    "LA Clippers": "/static/logos/la_clippers.png",
    "LOSC Lille": "/static/logos/losc_lille.png",
    "Lazio": "/static/logos/lazio.png",
    "Leeds United": "/static/logos/leeds_united.png",
    "Legia Warsaw": "/static/logos/legia_warsaw.png",
    "Liverpool": "/static/logos/liverpool.png",
    "Los Angeles Lakers": "/static/logos/los_angeles_lakers.png",
    "Malmo FF": "/static/logos/malmo_ff.png",
    "Manchester City": "/static/logos/manchester_city.png",
    "Manchester United": "/static/logos/manchester_united.png",
    "Memphis Grizzlies": "/static/logos/memphis_grizzlies.png",
    "Miami Heat": "/static/logos/miami_heat.png",
    "Milwaukee Bucks": "/static/logos/milwaukee_bucks.png",
    "Minnesota Timberwolves": "/static/logos/minnesota_timberwolves.png",
    "Napoli": "/static/logos/napoli.png",
    "New Orleans Pelicans": "/static/logos/new_orleans_pelicans.png",
    "New York Knicks": "/static/logos/new_york_knicks.png",
    "Newcastle United": "/static/logos/newcastle_united.png",
    "Nottingham Forest": "/static/logos/nottingham_forest.png",
    "Oklahoma City Thunder": "/static/logos/oklahoma_city_thunder.png",
    "Olympiacos": "/static/logos/olympiacos.png",
    "Olympique Lyonnais": "/static/logos/olympique_lyonnais.png",
    "Olympique Marseille": "/static/logos/olympique_marseille.png",
    "Orlando Magic": "/static/logos/orlando_magic.png",
    "PSV Eindhoven": "/static/logos/psv_eindhoven.png",
    "Palmeiras": "/static/logos/palmeiras.png",
    "Panathinaikos": "/static/logos/panathinaikos.png",
    "Paris Saint-Germain": "/static/logos/paris_saint-germain.png",
    "Partizan": "/static/logos/partizan.png",
    "Philadelphia 76ers": "/static/logos/philadelphia_76ers.png",
    "Phoenix Suns": "/static/logos/phoenix_suns.png",
    "Portland Trail Blazers": "/static/logos/portland_trail_blazers.png",
    "Porto": "/static/logos/porto.png",
    "RB Leipzig": "/static/logos/rb_leipzig.png",
    "Rangers": "/static/logos/rangers.png",
    "Rapid Wien": "/static/logos/rapid_wien.png",
    "Real Betis": "/static/logos/real_betis.png",
    "Real Madrid": "/static/logos/real_madrid.png",
    "Real Sociedad": "/static/logos/real_sociedad.png",
    "Red Bull Salzburg": "/static/logos/red_bull_salzburg.png",
    "Red Star Belgrade": "/static/logos/red_star_belgrade.png",
    "River Plate": "/static/logos/river_plate.png",
    "Rosenborg": "/static/logos/rosenborg.png",
    "Sacramento Kings": "/static/logos/sacramento_kings.png",
    "San Antonio Spurs": "/static/logos/san_antonio_spurs.png",
    "Santos": "/static/logos/santos.png",
    "Sao Paulo": "/static/logos/sao_paulo.png",
    "Schalke 04": "/static/logos/schalke_04.png",
    "Sevilla": "/static/logos/sevilla.png",
    "Shakhtar Donetsk": "/static/logos/shakhtar_donetsk.png",
    "Slavia Prague": "/static/logos/slavia_prague.png",
    "Sparta Prague": "/static/logos/sparta_prague.png",
    "Spartak Moscow": "/static/logos/spartak_moscow.png",
    "Sporting CP": "/static/logos/sporting_cp.png",
    "Steaua Bucharest": "/static/logos/steaua_bucharest.png",
    "Toronto Raptors": "/static/logos/toronto_raptors.png",
    "Tottenham Hotspur": "/static/logos/tottenham_hotspur.png",
    "Utah Jazz": "/static/logos/utah_jazz.png",
    "Valencia": "/static/logos/valencia.png",
    "VfB Stuttgart": "/static/logos/vfb_stuttgart.png",
    "Villarreal": "/static/logos/villarreal.png",
    "Washington Wizards": "/static/logos/washington_wizards.png",
    "Werder Bremen": "/static/logos/werder_bremen.png",
    "West Ham United": "/static/logos/west_ham_united.png",
    "Young Boys": "/static/logos/young_boys.png",
    "Zenit St Petersburg": "/static/logos/zenit_st_petersburg.png",
}
