LOGOS = {
    "AC Milan": "/static/logos/ac_milan.png",
    "AEK Athens": "/static/logos/aek_athens.png",
    "AS Monaco": "/static/logos/as_monaco.png",
    "AS Roma": "/static/logos/as_roma.png",
    "AVS": "/static/logos/avs.png",
    "Ajax": "/static/logos/ajax.png",
    "Albertville 1992": "/static/logos/events/albertville_1992.png",
    "Amsterdam 1928": "/static/logos/events/amsterdam_1928.png",
    "Anderlecht": "/static/logos/anderlecht.png",
    "Antwerp 1920": "/static/logos/events/antwerp_1920.png",
    "Argentina 1978": "/static/logos/events/argentina_1978.png",
    "Arouca": "/static/logos/arouca.png",
    "Arsenal": "/static/logos/arsenal.png",
    "Aston Villa": "/static/logos/aston_villa.png",
    "Atalanta": "/static/logos/atalanta.png",
    "Athens 1896": "/static/logos/events/athens_1896.png",
    "Athens 2004": "/static/logos/events/athens_2004.png",
    "Athletic Bilbao": "/static/logos/athletic_bilbao.png",
    "Atlanta 1996": "/static/logos/events/atlanta_1996.png",
    "Atlanta Hawks": "/static/logos/atlanta_hawks.png",
    "Atletico Madrid": "/static/logos/atletico_madrid.png",
    "Barcelona": "/static/logos/barcelona.png",
    "Barcelona 1992": "/static/logos/events/barcelona_1992.png",
    "Bayer Leverkusen": "/static/logos/bayer_leverkusen.png",
    "Bayern Munich": "/static/logos/bayern_munich.png",
    "Beijing 2008": "/static/logos/events/beijing_2008.png",
    "Beijing 2022": "/static/logos/events/beijing_2022.png",
    "Belgium 1972": "/static/logos/events/belgium_1972.png",
    "Belgium/Netherlands 2000": "/static/logos/events/belgium_netherlands_2000.png",
    "Benfica": "/static/logos/benfica.png",
    "Berlin 1936": "/static/logos/events/berlin_1936.png",
    "Besiktas": "/static/logos/besiktas.png",
    "Boavista": "/static/logos/boavista.png",
    "Boca Juniors": "/static/logos/boca_juniors.png",
    "Borussia Dortmund": "/static/logos/borussia_dortmund.png",
    "Borussia Monchengladbach": "/static/logos/borussia_monchengladbach.png",
    "Boston Celtics": "/static/logos/boston_celtics.png",
    "Bournemouth": "/static/logos/bournemouth.png",
    "Braga": "/static/logos/braga.png",
    "Brazil 1950": "/static/logos/events/brazil_1950.png",
    "Brazil 2014": "/static/logos/events/brazil_2014.png",
    "Brentford": "/static/logos/brentford.png",
    "Brighton": "/static/logos/brighton.png",
    "Brooklyn Nets": "/static/logos/brooklyn_nets.png",
    "CSKA Moscow": "/static/logos/cska_moscow.png",
    "Calgary 1988": "/static/logos/events/calgary_1988.png",
    "Casa Pia": "/static/logos/casa_pia.png",
    "Celtic": "/static/logos/celtic.png",
    "Chamonix 1924": "/static/logos/events/chamonix_1924.png",
    "Charlotte Hornets": "/static/logos/charlotte_hornets.png",
    "Chelsea": "/static/logos/chelsea.png",
    "Chicago Bulls": "/static/logos/chicago_bulls.png",
    "Chile 1962": "/static/logos/events/chile_1962.png",
    "Chivas": "/static/logos/chivas.png",
    "Cleveland Cavaliers": "/static/logos/cleveland_cavaliers.png",
    "Club America": "/static/logos/club_america.png",
    "Club Brugge": "/static/logos/club_brugge.png",
    "Corinthians": "/static/logos/corinthians.png",
    "Cortina 1956": "/static/logos/events/cortina_1956.png",
    "Crystal Palace": "/static/logos/crystal_palace.png",
    "Dallas Mavericks": "/static/logos/dallas_mavericks.png",
    "Denver Nuggets": "/static/logos/denver_nuggets.png",
    "Detroit Pistons": "/static/logos/detroit_pistons.png",
    "Dinamo Zagreb": "/static/logos/dinamo_zagreb.png",
    "Dynamo Kyiv": "/static/logos/dynamo_kyiv.png",
    "Eintracht Frankfurt": "/static/logos/eintracht_frankfurt.png",
    "England 1966": "/static/logos/events/england_1966.png",
    "England 1996": "/static/logos/events/england_1996.png",
    "Estoril": "/static/logos/estoril.png",
    "Estrela Amadora": "/static/logos/estrela_amadora.png",
    "Europe 2020": "/static/logos/events/europe_2020.png",
    "Everton": "/static/logos/everton.png",
    "FC Basel": "/static/logos/fc_basel.png",
    "Famalicao": "/static/logos/famalicao.png",
    "Farense": "/static/logos/farense.png",
    "Fenerbahce": "/static/logos/fenerbahce.png",
    "Ferencvaros": "/static/logos/ferencvaros.png",
    "Feyenoord": "/static/logos/feyenoord.png",
    "Fiorentina": "/static/logos/fiorentina.png",
    "Flamengo": "/static/logos/flamengo.png",
    "France 1938": "/static/logos/events/france_1938.png",
    "France 1960": "/static/logos/events/france_1960.png",
    "France 1984": "/static/logos/events/france_1984.png",
    "France 1998": "/static/logos/events/france_1998.png",
    "France 2016": "/static/logos/events/france_2016.png",
    "Fulham": "/static/logos/fulham.png",
    "Galatasaray": "/static/logos/galatasaray.png",
    "Garmisch 1936": "/static/logos/events/garmisch_1936.png",
    "Germany 2006": "/static/logos/events/germany_2006.png",
    "Germany 2024": "/static/logos/events/germany_2024.png",
    "Gil Vicente": "/static/logos/gil_vicente.png",
    "Golden State Warriors": "/static/logos/golden_state_warriors.png",
    "Grenoble 1968": "/static/logos/events/grenoble_1968.png",
    "Hajduk Split": "/static/logos/hajduk_split.png",
    "Helsinki 1952": "/static/logos/events/helsinki_1952.png",
    "Houston Rockets": "/static/logos/houston_rockets.png",
    "Indiana Pacers": "/static/logos/indiana_pacers.png",
    "Innsbruck 1964": "/static/logos/events/innsbruck_1964.png",
    "Innsbruck 1976": "/static/logos/events/innsbruck_1976.png",
    "Inter Milan": "/static/logos/inter_milan.png",
    "Ipswich Town": "/static/logos/ipswich_town.png",
    "Italy 1934": "/static/logos/events/italy_1934.png",
    "Italy 1968": "/static/logos/events/italy_1968.png",
    "Italy 1980": "/static/logos/events/italy_1980.png",
    "Italy 1990": "/static/logos/events/italy_1990.png",
    "Juventus": "/static/logos/juventus.png",
    "LA Clippers": "/static/logos/la_clippers.png",
    "LOSC Lille": "/static/logos/losc_lille.png",
    "Lake Placid 1932": "/static/logos/events/lake_placid_1932.png",
    "Lake Placid 1980": "/static/logos/events/lake_placid_1980.png",
    "Lazio": "/static/logos/lazio.png",
    "Leeds United": "/static/logos/leeds_united.png",
    "Legia Warsaw": "/static/logos/legia_warsaw.png",
    "Leicester City": "/static/logos/leicester_city.png",
    "Lillehammer 1994": "/static/logos/events/lillehammer_1994.png",
    "Liverpool": "/static/logos/liverpool.png",
    "London 1908": "/static/logos/events/london_1908.png",
    "London 1948": "/static/logos/events/london_1948.png",
    "London 2012": "/static/logos/events/london_2012.png",
    "Los Angeles 1932": "/static/logos/events/los_angeles_1932.png",
    "Los Angeles 1984": "/static/logos/events/los_angeles_1984.png",
    "Los Angeles 2028": "/static/logos/events/los_angeles_2028.png",
    "Los Angeles Lakers": "/static/logos/los_angeles_lakers.png",
    "Malmo FF": "/static/logos/malmo_ff.png",
    "Manchester City": "/static/logos/manchester_city.png",
    "Manchester United": "/static/logos/manchester_united.png",
    "Melbourne 1956": "/static/logos/events/melbourne_1956.png",
    "Memphis Grizzlies": "/static/logos/memphis_grizzlies.png",
    "Mexico 1970": "/static/logos/events/mexico_1970.png",
    "Mexico 1986": "/static/logos/events/mexico_1986.png",
    "Mexico City 1968": "/static/logos/events/mexico_city_1968.png",
    "Miami Heat": "/static/logos/miami_heat.png",
    "Milano Cortina 2026": "/static/logos/events/milano_cortina_2026.png",
    "Milwaukee Bucks": "/static/logos/milwaukee_bucks.png",
    "Minnesota Timberwolves": "/static/logos/minnesota_timberwolves.png",
    "Montreal 1976": "/static/logos/events/montreal_1976.png",
    "Moreirense": "/static/logos/moreirense.png",
    "Moscow 1980": "/static/logos/events/moscow_1980.png",
    "Munich 1972": "/static/logos/events/munich_1972.png",
    "Nacional": "/static/logos/nacional.png",
    "Nagano 1998": "/static/logos/events/nagano_1998.png",
    "Napoli": "/static/logos/napoli.png",
    "New Orleans Pelicans": "/static/logos/new_orleans_pelicans.png",
    "New York Knicks": "/static/logos/new_york_knicks.png",
    "Newcastle United": "/static/logos/newcastle_united.png",
    "Nottingham Forest": "/static/logos/nottingham_forest.png",
    "Oklahoma City Thunder": "/static/logos/oklahoma_city_thunder.png",
    "Olympiacos": "/static/logos/olympiacos.png",
    "Olympique Lyonnais": "/static/logos/olympique_lyonnais.png",
    "Olympique Marseille": "/static/logos/olympique_marseille.png",
    "Orlando Magic": "/static/logos/orlando_magic.png",
    "Oslo 1952": "/static/logos/events/oslo_1952.png",
    "PSV Eindhoven": "/static/logos/psv_eindhoven.png",
    "Palmeiras": "/static/logos/palmeiras.png",
    "Panathinaikos": "/static/logos/panathinaikos.png",
    "Paris 1900": "/static/logos/events/paris_1900.png",
    "Paris 1924": "/static/logos/events/paris_1924.png",
    "Paris 2024": "/static/logos/events/paris_2024.png",
    "Paris Saint-Germain": "/static/logos/paris_saint-germain.png",
    "Partizan": "/static/logos/partizan.png",
    "Philadelphia 76ers": "/static/logos/philadelphia_76ers.png",
    "Phoenix Suns": "/static/logos/phoenix_suns.png",
    "Poland/Ukraine 2012": "/static/logos/events/poland_ukraine_2012.png",
    "Portland Trail Blazers": "/static/logos/portland_trail_blazers.png",
    "Porto": "/static/logos/porto.png",
    "Portugal 2004": "/static/logos/events/portugal_2004.png",
    "Pyeongchang 2018": "/static/logos/events/pyeongchang_2018.png",
    "RB Leipzig": "/static/logos/rb_leipzig.png",
    "Rangers": "/static/logos/rangers.png",
    "Rapid Wien": "/static/logos/rapid_wien.png",
    "Real Betis": "/static/logos/real_betis.png",
    "Real Madrid": "/static/logos/real_madrid.png",
    "Real Sociedad": "/static/logos/real_sociedad.png",
    "Red Bull Salzburg": "/static/logos/red_bull_salzburg.png",
    "Red Star Belgrade": "/static/logos/red_star_belgrade.png",
    "Rio 2016": "/static/logos/events/rio_2016.png",
    "Rio Ave": "/static/logos/rio_ave.png",
    "River Plate": "/static/logos/river_plate.png",
    "Rome 1960": "/static/logos/events/rome_1960.png",
    "Rosenborg": "/static/logos/rosenborg.png",
    "Russia 2018": "/static/logos/events/russia_2018.png",
    "Sacramento Kings": "/static/logos/sacramento_kings.png",
    "Salt Lake City 2002": "/static/logos/events/salt_lake_city_2002.png",
    "San Antonio Spurs": "/static/logos/san_antonio_spurs.png",
    "Santa Clara": "/static/logos/santa_clara.png",
    "Santos": "/static/logos/santos.png",
    "Sao Paulo": "/static/logos/sao_paulo.png",
    "Sapporo 1972": "/static/logos/events/sapporo_1972.png",
    "Sarajevo 1984": "/static/logos/events/sarajevo_1984.png",
    "Schalke 04": "/static/logos/schalke_04.png",
    "Seoul 1988": "/static/logos/events/seoul_1988.png",
    "Sevilla": "/static/logos/sevilla.png",
    "Shakhtar Donetsk": "/static/logos/shakhtar_donetsk.png",
    "Slavia Prague": "/static/logos/slavia_prague.png",
    "Sochi 2014": "/static/logos/events/sochi_2014.png",
    "South Africa 2010": "/static/logos/events/south_africa_2010.png",
    "South Korea/Japan 2002": "/static/logos/events/south_korea_japan_2002.png",
    "Southampton": "/static/logos/southampton.png",
    "Spain 1964": "/static/logos/events/spain_1964.png",
    "Spain 1982": "/static/logos/events/spain_1982.png",
    "Sparta Prague": "/static/logos/sparta_prague.png",
    "Spartak Moscow": "/static/logos/spartak_moscow.png",
    "Sporting CP": "/static/logos/sporting_cp.png",
    "Squaw Valley 1960": "/static/logos/events/squaw_valley_1960.png",
    "St. Louis 1904": "/static/logos/events/st_louis_1904.png",
    "St. Moritz 1928": "/static/logos/events/st_moritz_1928.png",
    "Steaua Bucharest": "/static/logos/steaua_bucharest.png",
    "Stockholm 1912": "/static/logos/events/stockholm_1912.png",
    "Sweden 1958": "/static/logos/events/sweden_1958.png",
    "Sweden 1992": "/static/logos/events/sweden_1992.png",
    "Sydney 2000": "/static/logos/events/sydney_2000.png",
    "Tokyo 1964": "/static/logos/events/tokyo_1964.png",
    "Tokyo 2020": "/static/logos/events/tokyo_2020.png",
    "Toronto Raptors": "/static/logos/toronto_raptors.png",
    "Tottenham Hotspur": "/static/logos/tottenham_hotspur.png",
    "Turin 2006": "/static/logos/events/turin_2006.png",
    "USA 1994": "/static/logos/events/usa_1994.png",
    "Uruguay 1930": "/static/logos/events/uruguay_1930.png",
    "Utah Jazz": "/static/logos/utah_jazz.png",
    "Valencia": "/static/logos/valencia.png",
    "Vancouver 2010": "/static/logos/events/vancouver_2010.png",
    "VfB Stuttgart": "/static/logos/vfb_stuttgart.png",
    "Villarreal": "/static/logos/villarreal.png",
    "Vitoria Guimaraes": "/static/logos/vitoria_guimaraes.png",
    "Washington Wizards": "/static/logos/washington_wizards.png",
    "Werder Bremen": "/static/logos/werder_bremen.png",
    "West Germany 1974": "/static/logos/events/west_germany_1974.png",
    "West Germany 1988": "/static/logos/events/west_germany_1988.png",
    "West Ham United": "/static/logos/west_ham_united.png",
    "Wolverhampton": "/static/logos/wolverhampton.png",
    "Young Boys": "/static/logos/young_boys.png",
    "Yugoslavia 1976": "/static/logos/events/yugoslavia_1976.png",
    "Zenit St Petersburg": "/static/logos/zenit_st_petersburg.png",
}
