LOCATIONS = {
    # Europe
    "Eiffel Tower": "France",
    "Colosseum": "Italy",
    "Parthenon": "Greece",
    "Sagrada Família": "Spain",
    "Big Ben": "England",
    "Tower of London": "England",
    "Stonehenge": "England",
    "Buckingham Palace": "England",
    "Palace of Versailles": "France",
    "Notre-Dame de Paris": "France",
    "Mont-Saint-Michel": "France",
    "Leaning Tower of Pisa": "Italy",
    "St. Peter's Basilica": "Vatican City",
    "Sistine Chapel": "Vatican City",
    "Trevi Fountain": "Italy",
    "Pantheon, Rome": "Italy",
    "Pompeii": "Italy",
    "Alhambra": "Spain",
    "Park Güell": "Spain",
    "Casa Milà": "Spain",
    "Acropolis of Athens": "Greece",
    "Brandenburg Gate": "Germany",
    "Neuschwanstein Castle": "Germany",
    "Cologne Cathedral": "Germany",
    "Prague Castle": "Czech Republic",
    "Charles Bridge": "Czech Republic",
    "Hagia Sophia": "Turkey",
    "Blue Mosque": "Turkey",
    "Topkapi Palace": "Turkey",
    "Kremlin": "Russia",
    "Saint Basil's Cathedral": "Russia",
    "Winter Palace": "Russia",
    "Edinburgh Castle": "Scotland",
    "Tower Bridge": "England",
    "Westminster Abbey": "England",
    "Houses of Parliament": "England",
    "St Paul's Cathedral": "England",
    "Louvre": "France",
    "Arc de Triomphe": "France",
    "Sacré-Cœur, Paris": "France",
    "Château de Chambord": "France",
    "Pont du Gard": "France",
    "Rijksmuseum": "Netherlands",
    "Anne Frank House": "Netherlands",
    "La Scala": "Italy",
    "Doge's Palace": "Italy",
    "Rialto Bridge": "Italy",
    "Florence Cathedral": "Italy",
    "Uffizi Gallery": "Italy",
    "Royal Palace of Madrid": "Spain",
    "Plaza de España, Seville": "Spain",
    "Belém Tower": "Portugal",
    "Jerónimos Monastery": "Portugal",
    "Hallgrímskirkja": "Iceland",
    "Little Mermaid (statue)": "Denmark",
    "Schönbrunn Palace": "Austria",
    "Hungarian Parliament Building": "Hungary",
    # Asia
    "Great Wall of China": "China",
    "Forbidden City": "China",
    "Terracotta Army": "China",
    "Temple of Heaven": "China",
    "Summer Palace": "China",
    "Taj Mahal": "India",
    "Red Fort": "India",
    "Lotus Temple": "India",
    "Gateway of India": "India",
    "Hawa Mahal": "India",
    "Qutub Minar": "India",
    "Khajuraho temples": "India",
    "Angkor Wat": "Cambodia",
    "Borobudur": "Indonesia",
    "Prambanan": "Indonesia",
    "Shwedagon Pagoda": "Myanmar",
    "Bagan": "Myanmar",
    "Fushimi Inari-taisha": "Japan",
    "Kinkaku-ji": "Japan",
    "Itsukushima Shrine": "Japan",
    "Himeji Castle": "Japan",
    "Senso-ji": "Japan",
    "Gyeongbokgung": "South Korea",
    "Petronas Towers": "Malaysia",
    "Marina Bay Sands": "Singapore",
    "Burj Khalifa": "UAE",
    "Burj Al Arab": "UAE",
    "Sheikh Zayed Grand Mosque": "UAE",
    "Petra": "Jordan",
    "Dome of the Rock": "Jerusalem",
    "Western Wall": "Jerusalem",
    "Persepolis": "Iran",
    "Samarkand": "Uzbekistan",
    "Bukhara": "Uzbekistan",
    "Sigiriya": "Sri Lanka",
    "Hampi": "India",
    "Konark Sun Temple": "India",
    "Mysore Palace": "India",
    "Meenakshi Temple": "India",
    "Ajanta Caves": "India",
    "Ellora Caves": "India",
    # Africa
    "Great Pyramid of Giza": "Egypt",
    "Great Sphinx of Giza": "Egypt",
    "Abu Simbel temples": "Egypt",
    "Valley of the Kings": "Egypt",
    "Karnak": "Egypt",
    "Luxor Temple": "Egypt",
    "Great Zimbabwe": "Zimbabwe",
    "Church of Saint George, Lalibela": "Ethiopia",
    "Mosque of Djenné": "Mali",
    "Great Mosque of Kairouan": "Tunisia",
    "Ruins of Aksum": "Ethiopia",
    "Fasil Ghebbi": "Ethiopia",
    "Timbuktu": "Mali",
    "Robben Island": "South Africa",
    "Cape Coast Castle": "Ghana",
    "Stone Town": "Tanzania",
    # Americas
    "Statue of Liberty": "USA",
    "Golden Gate Bridge": "USA",
    "Empire State Building": "USA",
    "White House": "USA",
    "Mount Rushmore": "USA",
    "Lincoln Memorial": "USA",
    "Hoover Dam": "USA",
    "Brooklyn Bridge": "USA",
    "Chrysler Building": "USA",
    "One World Trade Center": "USA",
    "Space Needle": "USA",
    "Hollywood Sign": "USA",
    "Chichen Itza": "Mexico",
    "Teotihuacan": "Mexico",
    "Machu Picchu": "Peru",
    "Christ the Redeemer (statue)": "Brazil",
    "Moai": "Easter Island",
    "Tikal": "Guatemala",
    "Copán": "Honduras",
    "Tulum": "Mexico",
    "Ollantaytambo": "Peru",
    "Nazca Lines": "Peru",
    "Chan Chan": "Peru",
    "Cartagena Walls": "Colombia",
    "Havana Cathedral": "Cuba",
    "CN Tower": "Canada",
    # Oceania
    "Sydney Opera House": "Australia",
    "Sydney Harbour Bridge": "Australia",
    "Te Papa": "New Zealand",
    "Sky Tower Auckland": "New Zealand",
    # Modern
    "Guggenheim Museum Bilbao": "Spain",
    "Gardens by the Bay": "Singapore",
    "Palm Jumeirah": "UAE",
    "The Shard": "England",
    "Millau Viaduct": "France",
    "Channel Tunnel": "France/England",
    "Panama Canal": "Panama",
    "Suez Canal": "Egypt",
    "International Space Station": "Space",
}

ALL = [
    # Europe
    "Eiffel Tower", "Colosseum", "Parthenon", "Sagrada Família",
    "Big Ben", "Tower of London", "Stonehenge", "Buckingham Palace",
    "Palace of Versailles", "Notre-Dame de Paris", "Mont-Saint-Michel",
    "Leaning Tower of Pisa", "St. Peter's Basilica", "Sistine Chapel",
    "Trevi Fountain", "Pantheon, Rome", "Pompeii",
    "Alhambra", "Park Güell", "Casa Milà",
    "Acropolis of Athens", "Brandenburg Gate", "Neuschwanstein Castle",
    "Cologne Cathedral", "Prague Castle", "Charles Bridge",
    "Hagia Sophia", "Blue Mosque", "Topkapi Palace",
    "Kremlin", "Saint Basil's Cathedral", "Winter Palace",
    "Edinburgh Castle", "Tower Bridge", "Westminster Abbey",
    "Houses of Parliament", "St Paul's Cathedral",
    "Louvre", "Arc de Triomphe", "Sacré-Cœur, Paris",
    "Château de Chambord", "Pont du Gard",
    "Rijksmuseum", "Anne Frank House",
    "La Scala", "Doge's Palace", "Rialto Bridge",
    "Florence Cathedral", "Uffizi Gallery",
    "Royal Palace of Madrid", "Plaza de España, Seville",
    "Belém Tower", "Jerónimos Monastery",
    "Hallgrímskirkja", "Little Mermaid (statue)",
    "Schönbrunn Palace", "Hungarian Parliament Building",
    # Asia
    "Great Wall of China", "Forbidden City", "Terracotta Army",
    "Temple of Heaven", "Summer Palace",
    "Taj Mahal", "Red Fort", "Lotus Temple", "Gateway of India",
    "Hawa Mahal", "Qutub Minar", "Khajuraho temples",
    "Angkor Wat", "Borobudur", "Prambanan",
    "Shwedagon Pagoda", "Bagan",
    "Fushimi Inari-taisha", "Kinkaku-ji", "Itsukushima Shrine",
    "Himeji Castle", "Senso-ji",
    "Gyeongbokgung", "Petronas Towers",
    "Marina Bay Sands", "Burj Khalifa", "Burj Al Arab",
    "Sheikh Zayed Grand Mosque", "Petra",
    "Dome of the Rock", "Western Wall",
    "Persepolis", "Samarkand", "Bukhara",
    "Sigiriya",
    "Hampi", "Konark Sun Temple", "Mysore Palace",
    "Meenakshi Temple", "Ajanta Caves", "Ellora Caves",
    # Africa
    "Great Pyramid of Giza", "Great Sphinx of Giza",
    "Abu Simbel temples", "Valley of the Kings",
    "Karnak", "Luxor Temple",
    "Great Zimbabwe",
    "Church of Saint George, Lalibela",
    "Mosque of Djenné",
    "Great Mosque of Kairouan", "Ruins of Aksum", "Fasil Ghebbi",
    "Timbuktu", "Robben Island", "Cape Coast Castle", "Stone Town",
    # Americas
    "Statue of Liberty", "Golden Gate Bridge",
    "Empire State Building", "White House",
    "Mount Rushmore", "Lincoln Memorial",
    "Hoover Dam", "Brooklyn Bridge",
    "Chrysler Building", "One World Trade Center",
    "Space Needle", "Hollywood Sign",
    "Chichen Itza", "Teotihuacan",
    "Machu Picchu", "Christ the Redeemer (statue)",
    "Moai",
    "Tikal", "Copán", "Tulum", "Ollantaytambo",
    "Nazca Lines", "Chan Chan",
    "Cartagena Walls", "Havana Cathedral",
    "CN Tower",
    # Oceania
    "Sydney Opera House", "Sydney Harbour Bridge",
    "Te Papa", "Sky Tower Auckland",
    # Modern & iconic structures
    "Guggenheim Museum Bilbao", "Sydney Opera House",
    "Lotus Temple", "Gardens by the Bay",
    "Palm Jumeirah", "The Shard",
    "Millau Viaduct", "Channel Tunnel",
    "Panama Canal", "Suez Canal",
    "International Space Station",
]
