LOCATIONS = {
    # Europe
    "Eiffel Tower": "Paris, France",
    "Colosseum": "Rome, Italy",
    "Parthenon": "Athens, Greece",
    "Sagrada Família": "Barcelona, Spain",
    "Big Ben": "London, England",
    "Tower of London": "London, England",
    "Stonehenge": "Wiltshire, England",
    "Buckingham Palace": "London, England",
    "Palace of Versailles": "Versailles, France",
    "Notre-Dame de Paris": "Paris, France",
    "Mont-Saint-Michel": "Normandy, France",
    "Leaning Tower of Pisa": "Pisa, Italy",
    "St. Peter's Basilica": "Vatican City",
    "Sistine Chapel": "Vatican City",
    "Trevi Fountain": "Rome, Italy",
    "Pantheon, Rome": "Rome, Italy",
    "Pompeii": "Naples, Italy",
    "Alhambra": "Granada, Spain",
    "Park Güell": "Barcelona, Spain",
    "Casa Milà": "Barcelona, Spain",
    "Acropolis of Athens": "Athens, Greece",
    "Brandenburg Gate": "Berlin, Germany",
    "Neuschwanstein Castle": "Bavaria, Germany",
    "Cologne Cathedral": "Cologne, Germany",
    "Prague Castle": "Prague, Czech Republic",
    "Charles Bridge": "Prague, Czech Republic",
    "Hagia Sophia": "Istanbul, Turkey",
    "Blue Mosque": "Istanbul, Turkey",
    "Topkapi Palace": "Istanbul, Turkey",
    "Kremlin": "Moscow, Russia",
    "Saint Basil's Cathedral": "Moscow, Russia",
    "Winter Palace": "St Petersburg, Russia",
    "Edinburgh Castle": "Edinburgh, Scotland",
    "Tower Bridge": "London, England",
    "Westminster Abbey": "London, England",
    "Houses of Parliament": "London, England",
    "St Paul's Cathedral": "London, England",
    "Louvre": "Paris, France",
    "Arc de Triomphe": "Paris, France",
    "Sacré-Cœur, Paris": "Paris, France",
    "Château de Chambord": "Loire Valley, France",
    "Pont du Gard": "Provence, France",
    "Rijksmuseum": "Amsterdam, Netherlands",
    "Anne Frank House": "Amsterdam, Netherlands",
    "La Scala": "Milan, Italy",
    "Doge's Palace": "Venice, Italy",
    "Rialto Bridge": "Venice, Italy",
    "Florence Cathedral": "Florence, Italy",
    "Uffizi Gallery": "Florence, Italy",
    "Royal Palace of Madrid": "Madrid, Spain",
    "Plaza de España, Seville": "Seville, Spain",
    "Belém Tower": "Lisbon, Portugal",
    "Jerónimos Monastery": "Lisbon, Portugal",
    "Hallgrímskirkja": "Reykjavik, Iceland",
    "Little Mermaid (statue)": "Copenhagen, Denmark",
    "Schönbrunn Palace": "Vienna, Austria",
    "Hungarian Parliament Building": "Budapest, Hungary",
    # Asia
    "Great Wall of China": "Beijing, China",
    "Forbidden City": "Beijing, China",
    "Terracotta Army": "Xi'an, China",
    "Temple of Heaven": "Beijing, China",
    "Summer Palace": "Beijing, China",
    "Taj Mahal": "Agra, India",
    "Red Fort": "Delhi, India",
    "Lotus Temple": "Delhi, India",
    "Gateway of India": "Mumbai, India",
    "Hawa Mahal": "Jaipur, India",
    "Qutub Minar": "Delhi, India",
    "Khajuraho temples": "Khajuraho, India",
    "Angkor Wat": "Siem Reap, Cambodia",
    "Borobudur": "Java, Indonesia",
    "Prambanan": "Java, Indonesia",
    "Shwedagon Pagoda": "Yangon, Myanmar",
    "Bagan": "Mandalay, Myanmar",
    "Fushimi Inari-taisha": "Kyoto, Japan",
    "Kinkaku-ji": "Kyoto, Japan",
    "Itsukushima Shrine": "Hiroshima, Japan",
    "Himeji Castle": "Himeji, Japan",
    "Senso-ji": "Tokyo, Japan",
    "Gyeongbokgung": "Seoul, South Korea",
    "Petronas Towers": "Kuala Lumpur, Malaysia",
    "Marina Bay Sands": "Singapore",
    "Burj Khalifa": "Dubai, UAE",
    "Burj Al Arab": "Dubai, UAE",
    "Sheikh Zayed Grand Mosque": "Abu Dhabi, UAE",
    "Petra": "Ma'an, Jordan",
    "Dome of the Rock": "Jerusalem",
    "Western Wall": "Jerusalem",
    "Persepolis": "Shiraz, Iran",
    "Samarkand": "Samarkand, Uzbekistan",
    "Bukhara": "Bukhara, Uzbekistan",
    "Sigiriya": "Central Province, Sri Lanka",
    "Hampi": "Karnataka, India",
    "Konark Sun Temple": "Odisha, India",
    "Mysore Palace": "Mysore, India",
    "Meenakshi Temple": "Madurai, India",
    "Ajanta Caves": "Maharashtra, India",
    "Ellora Caves": "Maharashtra, India",
    # Africa
    "Great Pyramid of Giza": "Giza, Egypt",
    "Great Sphinx of Giza": "Giza, Egypt",
    "Abu Simbel temples": "Aswan, Egypt",
    "Valley of the Kings": "Luxor, Egypt",
    "Karnak": "Luxor, Egypt",
    "Luxor Temple": "Luxor, Egypt",
    "Great Zimbabwe": "Masvingo, Zimbabwe",
    "Church of Saint George, Lalibela": "Lalibela, Ethiopia",
    "Mosque of Djenné": "Djenné, Mali",
    "Great Mosque of Kairouan": "Kairouan, Tunisia",
    "Ruins of Aksum": "Aksum, Ethiopia",
    "Fasil Ghebbi": "Gondar, Ethiopia",
    "Timbuktu": "Timbuktu, Mali",
    "Robben Island": "Cape Town, South Africa",
    "Cape Coast Castle": "Cape Coast, Ghana",
    "Stone Town": "Zanzibar, Tanzania",
    # Americas
    "Statue of Liberty": "New York, USA",
    "Golden Gate Bridge": "San Francisco, USA",
    "Empire State Building": "New York, USA",
    "White House": "Washington D.C., USA",
    "Mount Rushmore": "South Dakota, USA",
    "Lincoln Memorial": "Washington D.C., USA",
    "Hoover Dam": "Nevada, USA",
    "Brooklyn Bridge": "New York, USA",
    "Chrysler Building": "New York, USA",
    "One World Trade Center": "New York, USA",
    "Space Needle": "Seattle, USA",
    "Hollywood Sign": "Los Angeles, USA",
    "Chichen Itza": "Yucatán, Mexico",
    "Teotihuacan": "Mexico City, Mexico",
    "Machu Picchu": "Cusco, Peru",
    "Christ the Redeemer (statue)": "Rio de Janeiro, Brazil",
    "Moai": "Easter Island",
    "Tikal": "Petén, Guatemala",
    "Copán": "Copán, Honduras",
    "Tulum": "Quintana Roo, Mexico",
    "Ollantaytambo": "Cusco, Peru",
    "Nazca Lines": "Nazca, Peru",
    "Chan Chan": "Trujillo, Peru",
    "Cartagena Walls": "Cartagena, Colombia",
    "Havana Cathedral": "Havana, Cuba",
    "CN Tower": "Toronto, Canada",
    # Oceania
    "Sydney Opera House": "Sydney, Australia",
    "Sydney Harbour Bridge": "Sydney, Australia",
    "Te Papa": "Wellington, New Zealand",
    "Sky Tower Auckland": "Auckland, New Zealand",
    # Modern
    "Guggenheim Museum Bilbao": "Bilbao, Spain",
    "Gardens by the Bay": "Singapore",
    "Palm Jumeirah": "Dubai, UAE",
    "The Shard": "London, England",
    "Millau Viaduct": "Aveyron, France",
    "Channel Tunnel": "Calais/Dover",
    "Panama Canal": "Panama",
    "Suez Canal": "Egypt",
    "International Space Station": "Space",
}

CONTINENTS = {
    "africa": [
        "Abu Simbel temples",
        "Cape Coast Castle",
        "Church of Saint George, Lalibela",
        "Fasil Ghebbi",
        "Great Mosque of Kairouan",
        "Great Pyramid of Giza",
        "Great Sphinx of Giza",
        "Great Zimbabwe",
        "Karnak",
        "Luxor Temple",
        "Mosque of Djenné",
        "Robben Island",
        "Ruins of Aksum",
        "Stone Town",
        "Timbuktu",
        "Valley of the Kings",
        "Suez Canal",
    ],
    "america": [
        "Brooklyn Bridge",
        "Cartagena Walls",
        "Chan Chan",
        "Chichen Itza",
        "Christ the Redeemer (statue)",
        "Chrysler Building",
        "CN Tower",
        "Copán",
        "Empire State Building",
        "Golden Gate Bridge",
        "Havana Cathedral",
        "Hollywood Sign",
        "Hoover Dam",
        "Lincoln Memorial",
        "Machu Picchu",
        "Moai",
        "Mount Rushmore",
        "Nazca Lines",
        "Ollantaytambo",
        "One World Trade Center",
        "Space Needle",
        "Statue of Liberty",
        "Teotihuacan",
        "Tikal",
        "Tulum",
        "White House",
        "Panama Canal",
    ],
    "asia": [
        "Ajanta Caves",
        "Angkor Wat",
        "Bagan",
        "Borobudur",
        "Bukhara",
        "Burj Al Arab",
        "Burj Khalifa",
        "Dome of the Rock",
        "Ellora Caves",
        "Forbidden City",
        "Fushimi Inari-taisha",
        "Gateway of India",
        "Great Wall of China",
        "Gyeongbokgung",
        "Hampi",
        "Hawa Mahal",
        "Himeji Castle",
        "Itsukushima Shrine",
        "Khajuraho temples",
        "Kinkaku-ji",
        "Konark Sun Temple",
        "Lotus Temple",
        "Marina Bay Sands",
        "Meenakshi Temple",
        "Mysore Palace",
        "Persepolis",
        "Petra",
        "Petronas Towers",
        "Prambanan",
        "Qutub Minar",
        "Red Fort",
        "Samarkand",
        "Senso-ji",
        "Sheikh Zayed Grand Mosque",
        "Shwedagon Pagoda",
        "Sigiriya",
        "Summer Palace",
        "Taj Mahal",
        "Temple of Heaven",
        "Terracotta Army",
        "Western Wall",
        "Gardens by the Bay",
        "Palm Jumeirah",
    ],
    "europe": [
        "Acropolis of Athens",
        "Alhambra",
        "Anne Frank House",
        "Arc de Triomphe",
        "Belém Tower",
        "Big Ben",
        "Blue Mosque",
        "Brandenburg Gate",
        "Buckingham Palace",
        "Casa Milà",
        "Charles Bridge",
        "Château de Chambord",
        "Cologne Cathedral",
        "Colosseum",
        "Doge's Palace",
        "Edinburgh Castle",
        "Eiffel Tower",
        "Florence Cathedral",
        "Hagia Sophia",
        "Hallgrímskirkja",
        "Houses of Parliament",
        "Hungarian Parliament Building",
        "Jerónimos Monastery",
        "Kremlin",
        "La Scala",
        "Leaning Tower of Pisa",
        "Little Mermaid (statue)",
        "Louvre",
        "Mont-Saint-Michel",
        "Neuschwanstein Castle",
        "Notre-Dame de Paris",
        "Palace of Versailles",
        "Pantheon, Rome",
        "Park Güell",
        "Parthenon",
        "Plaza de España, Seville",
        "Pompeii",
        "Pont du Gard",
        "Prague Castle",
        "Rialto Bridge",
        "Rijksmuseum",
        "Royal Palace of Madrid",
        "Sacré-Cœur, Paris",
        "Sagrada Família",
        "Saint Basil's Cathedral",
        "Schönbrunn Palace",
        "Sistine Chapel",
        "St Paul's Cathedral",
        "St. Peter's Basilica",
        "Stonehenge",
        "Topkapi Palace",
        "Tower Bridge",
        "Tower of London",
        "Trevi Fountain",
        "Uffizi Gallery",
        "Westminster Abbey",
        "Winter Palace",
        "Guggenheim Museum Bilbao",
        "The Shard",
        "Millau Viaduct",
        "Channel Tunnel",
    ],
    "oceania": [
        "Sky Tower Auckland",
        "Sydney Harbour Bridge",
        "Sydney Opera House",
        "Te Papa",
    ],
}

ALL = [
    # Europe
    "Acropolis of Athens",
    "Alhambra",
    "Anne Frank House",
    "Arc de Triomphe",
    "Belém Tower",
    "Big Ben",
    "Blue Mosque",
    "Brandenburg Gate",
    "Buckingham Palace",
    "Casa Milà",
    "Charles Bridge",
    "Château de Chambord",
    "Cologne Cathedral",
    "Colosseum",
    "Doge's Palace",
    "Edinburgh Castle",
    "Eiffel Tower",
    "Florence Cathedral",
    "Hagia Sophia",
    "Hallgrímskirkja",
    "Houses of Parliament",
    "Hungarian Parliament Building",
    "Jerónimos Monastery",
    "Kremlin",
    "La Scala",
    "Leaning Tower of Pisa",
    "Little Mermaid (statue)",
    "Louvre",
    "Mont-Saint-Michel",
    "Neuschwanstein Castle",
    "Notre-Dame de Paris",
    "Palace of Versailles",
    "Pantheon, Rome",
    "Park Güell",
    "Parthenon",
    "Plaza de España, Seville",
    "Pompeii",
    "Pont du Gard",
    "Prague Castle",
    "Rialto Bridge",
    "Rijksmuseum",
    "Royal Palace of Madrid",
    "Sacré-Cœur, Paris",
    "Sagrada Família",
    "Saint Basil's Cathedral",
    "Schönbrunn Palace",
    "Sistine Chapel",
    "St Paul's Cathedral",
    "St. Peter's Basilica",
    "Stonehenge",
    "Topkapi Palace",
    "Tower Bridge",
    "Tower of London",
    "Trevi Fountain",
    "Uffizi Gallery",
    "Westminster Abbey",
    "Winter Palace",
    # Asia
    "Ajanta Caves",
    "Angkor Wat",
    "Bagan",
    "Borobudur",
    "Bukhara",
    "Burj Al Arab",
    "Burj Khalifa",
    "Dome of the Rock",
    "Ellora Caves",
    "Forbidden City",
    "Fushimi Inari-taisha",
    "Gateway of India",
    "Great Wall of China",
    "Gyeongbokgung",
    "Hampi",
    "Hawa Mahal",
    "Himeji Castle",
    "Itsukushima Shrine",
    "Khajuraho temples",
    "Kinkaku-ji",
    "Konark Sun Temple",
    "Lotus Temple",
    "Marina Bay Sands",
    "Meenakshi Temple",
    "Mysore Palace",
    "Persepolis",
    "Petra",
    "Petronas Towers",
    "Prambanan",
    "Qutub Minar",
    "Red Fort",
    "Samarkand",
    "Senso-ji",
    "Sheikh Zayed Grand Mosque",
    "Shwedagon Pagoda",
    "Sigiriya",
    "Summer Palace",
    "Taj Mahal",
    "Temple of Heaven",
    "Terracotta Army",
    "Western Wall",
    # Africa
    "Abu Simbel temples",
    "Cape Coast Castle",
    "Church of Saint George, Lalibela",
    "Fasil Ghebbi",
    "Great Mosque of Kairouan",
    "Great Pyramid of Giza",
    "Great Sphinx of Giza",
    "Great Zimbabwe",
    "Karnak",
    "Luxor Temple",
    "Mosque of Djenné",
    "Robben Island",
    "Ruins of Aksum",
    "Stone Town",
    "Timbuktu",
    "Valley of the Kings",
    # Americas
    "Brooklyn Bridge",
    "Cartagena Walls",
    "Chan Chan",
    "Chichen Itza",
    "Christ the Redeemer (statue)",
    "Chrysler Building",
    "CN Tower",
    "Copán",
    "Empire State Building",
    "Golden Gate Bridge",
    "Havana Cathedral",
    "Hollywood Sign",
    "Hoover Dam",
    "Lincoln Memorial",
    "Machu Picchu",
    "Moai",
    "Mount Rushmore",
    "Nazca Lines",
    "Ollantaytambo",
    "One World Trade Center",
    "Space Needle",
    "Statue of Liberty",
    "Teotihuacan",
    "Tikal",
    "Tulum",
    "White House",
    # Oceania
    "Sky Tower Auckland",
    "Sydney Harbour Bridge",
    "Sydney Opera House",
    "Te Papa",
    # Modern & iconic structures
    "Channel Tunnel",
    "Gardens by the Bay",
    "Guggenheim Museum Bilbao",
    "International Space Station",
    "Lotus Temple",
    "Millau Viaduct",
    "Palm Jumeirah",
    "Panama Canal",
    "Suez Canal",
    "Sydney Opera House",
    "The Shard",
]

DIFFICULTY = {
    "easy": [
        "Big Ben",
        "Buckingham Palace",
        "Colosseum",
        "Eiffel Tower",
        "Statue of Liberty",
        "Taj Mahal",
        "Great Wall of China",
        "Machu Picchu",
        "Great Pyramid of Giza",
        "Great Sphinx of Giza",
        "Chichen Itza",
        "Christ the Redeemer (statue)",
        "Stonehenge",
        "Sydney Opera House",
        "Golden Gate Bridge",
        "Empire State Building",
        "Leaning Tower of Pisa",
        "Parthenon",
        "Mount Rushmore",
        "Notre-Dame de Paris",
        "Sagrada Família",
        "Tower of London",
        "White House",
        "Forbidden City",
        "Angkor Wat",
        "Petra",
        "Burj Khalifa",
        "Tower Bridge",
        "Arc de Triomphe",
        "Louvre",
        "Hagia Sophia",
        "Acropolis of Athens",
        "Hollywood Sign",
        "Brandenburg Gate",
        "Neuschwanstein Castle",
        "Kremlin",
        "Trevi Fountain",
        "Palace of Versailles",
    ],
}
DIFFICULTY["hard"] = [m for m in ALL if m not in set(DIFFICULTY["easy"])]
