ALL = [
    # Europe
    "Eiffel Tower", "Colosseum", "Parthenon", "Sagrada Família",
    "Big Ben", "Tower of London", "Stonehenge", "Buckingham Palace",
    "Palace of Versailles", "Notre-Dame de Paris", "Mont-Saint-Michel",
    "Leaning Tower of Pisa", "St. Peter's Basilica", "Sistine Chapel",
    "Trevi Fountain", "Pantheon, Rome", "Pompeii",
    "Alhambra", "Park Güell", "Casa Milà",
    "Acropolis of Athens", "Brandenburg Gate", "Neuschwanstein Castle",
    "Cologne Cathedral", "Prague Castle", "Charles Bridge",
    "Hagia Sophia", "Blue Mosque", "Topkapi Palace",
    "Kremlin", "Saint Basil's Cathedral", "Winter Palace",
    "Edinburgh Castle", "Tower Bridge", "Westminster Abbey",
    "Houses of Parliament", "St Paul's Cathedral",
    "Louvre", "Arc de Triomphe", "Sacré-Cœur, Paris",
    "Château de Chambord", "Pont du Gard",
    "Rijksmuseum", "Anne Frank House",
    "La Scala", "Doge's Palace", "Rialto Bridge",
    "Florence Cathedral", "Uffizi Gallery",
    "Royal Palace of Madrid", "Plaza de España, Seville",
    "Belém Tower", "Jerónimos Monastery",
    "Hallgrímskirkja", "Little Mermaid (statue)",
    "Schönbrunn Palace", "Hungarian Parliament Building",
    # Asia
    "Great Wall of China", "Forbidden City", "Terracotta Army",
    "Temple of Heaven", "Summer Palace",
    "Taj Mahal", "Red Fort", "Lotus Temple", "Gateway of India",
    "Hawa Mahal", "Qutub Minar", "Khajuraho temples",
    "Angkor Wat", "Borobudur", "Prambanan",
    "Shwedagon Pagoda", "Bagan",
    "Fushimi Inari-taisha", "Kinkaku-ji", "Itsukushima Shrine",
    "Mount Fuji", "Himeji Castle", "Senso-ji",
    "Gyeongbokgung", "Petronas Towers",
    "Marina Bay Sands", "Burj Khalifa", "Burj Al Arab",
    "Sheikh Zayed Grand Mosque", "Petra",
    "Dome of the Rock", "Western Wall",
    "Persepolis", "Sigiriya",
    # Africa
    "Great Pyramid of Giza", "Great Sphinx of Giza",
    "Abu Simbel temples", "Valley of the Kings",
    "Karnak", "Luxor Temple",
    "Table Mountain", "Great Zimbabwe",
    "Church of Saint George, Lalibela",
    "Mosque of Djenné",
    # Americas
    "Statue of Liberty", "Golden Gate Bridge",
    "Empire State Building", "White House",
    "Mount Rushmore", "Lincoln Memorial",
    "Hoover Dam", "Brooklyn Bridge",
    "Chrysler Building", "One World Trade Center",
    "Space Needle", "Hollywood Sign",
    "Chichen Itza", "Teotihuacan",
    "Machu Picchu", "Christ the Redeemer (statue)",
    "Iguazu Falls", "Moai",
    "CN Tower", "Niagara Falls",
    # Oceania
    "Sydney Opera House", "Sydney Harbour Bridge",
    "Uluru",
    # Modern & iconic structures
    "Guggenheim Museum Bilbao", "Sydney Opera House",
    "Lotus Temple", "Gardens by the Bay",
    "Palm Jumeirah", "The Shard",
    "Millau Viaduct", "Channel Tunnel",
    "Panama Canal", "Suez Canal",
    "International Space Station",
]
