YEARS = {
    "Metropolis (1927 film)": "1927",
    "Nosferatu": "1922",
    "The Wizard of Oz (1939 film)": "1939",
    "Gone with the Wind (film)": "1939",
    "Citizen Kane": "1941",
    "Casablanca (film)": "1942",
    "It's a Wonderful Life": "1946",
    "Bambi": "1942",
    "Fantasia (1940 film)": "1940",
    "Singin' in the Rain": "1952",
    "Rear Window": "1954",
    "Vertigo (film)": "1958",
    "12 Angry Men (1957 film)": "1957",
    "Ben-Hur (1959 film)": "1959",
    "The Bridge on the River Kwai": "1957",
    "Some Like It Hot": "1959",
    "Roman Holiday": "1953",
    "Sunset Boulevard (film)": "1950",
    "Psycho (1960 film)": "1960",
    "Lawrence of Arabia (film)": "1962",
    "The Good, the Bad and the Ugly": "1966",
    "2001: A Space Odyssey (film)": "1968",
    "Doctor Zhivago (film)": "1965",
    "The Sound of Music (film)": "1965",
    "West Side Story (1961 film)": "1961",
    "Breakfast at Tiffany's (film)": "1961",
    "The Birds (film)": "1963",
    "The Godfather": "1972",
    "The Godfather Part II": "1974",
    "Jaws (film)": "1975",
    "Star Wars (film)": "1977",
    "Apocalypse Now": "1979",
    "A Clockwork Orange (film)": "1971",
    "The Exorcist": "1973",
    "Taxi Driver": "1976",
    "Rocky (1976 film)": "1976",
    "One Flew Over the Cuckoo's Nest (film)": "1975",
    "Chinatown (1974 film)": "1974",
    "The Sting (film)": "1973",
    "Grease (film)": "1978",
    "Alien (film)": "1979",
    "Monty Python and the Holy Grail": "1975",
    "Annie Hall": "1977",
    "The Empire Strikes Back": "1980",
    "Return of the Jedi": "1983",
    "Raiders of the Lost Ark": "1981",
    "E.T. the Extra-Terrestrial": "1982",
    "Blade Runner": "1982",
    "The Shining (film)": "1980",
    "Back to the Future": "1985",
    "The Breakfast Club": "1985",
    "Ghostbusters (1984 film)": "1984",
    "Die Hard": "1988",
    "Full Metal Jacket": "1987",
    "Scarface (1983 film)": "1983",
    "Raging Bull": "1980",
    "Platoon (film)": "1986",
    "Rain Man": "1988",
    "Amadeus (film)": "1984",
    "The Princess Bride (film)": "1987",
    "Batman (1989 film)": "1989",
    "Ferris Bueller's Day Off": "1986",
    "Top Gun": "1986",
    "Dirty Dancing": "1987",
    "Pulp Fiction": "1994",
    "The Shawshank Redemption": "1994",
    "Schindler's List": "1993",
    "Forrest Gump": "1994",
    "Goodfellas": "1990",
    "The Silence of the Lambs (film)": "1991",
    "Fight Club (film)": "1999",
    "The Matrix": "1999",
    "Titanic (1997 film)": "1997",
    "Jurassic Park (film)": "1993",
    "Saving Private Ryan": "1998",
    "The Lion King": "1994",
    "Braveheart (film)": "1995",
    "Fargo (1996 film)": "1996",
    "Se7en": "1995",
    "The Big Lebowski": "1998",
    "American Beauty (1999 film)": "1999",
    "The Sixth Sense": "1999",
    "The Truman Show": "1998",
    "Good Will Hunting": "1997",
    "Trainspotting (film)": "1996",
    "The Usual Suspects": "1995",
    "Heat (1995 film)": "1995",
    "Toy Story": "1995",
    "Edward Scissorhands": "1990",
    "The Lord of the Rings: The Fellowship of the Ring": "2001",
    "The Lord of the Rings: The Two Towers": "2002",
    "The Lord of the Rings: The Return of the King": "2003",
    "Gladiator (2000 film)": "2000",
    "Memento (film)": "2000",
    "Spirited Away": "2001",
    "Amélie": "2001",
    "City of God (2002 film)": "2002",
    "Kill Bill: Volume 1": "2003",
    "Eternal Sunshine of the Spotless Mind": "2004",
    "The Dark Knight": "2008",
    "No Country for Old Men (film)": "2007",
    "There Will Be Blood": "2007",
    "WALL-E": "2008",
    "Ratatouille": "2007",
    "Harry Potter and the Philosopher's Stone (film)": "2001",
    "Pirates of the Caribbean: The Curse of the Black Pearl": "2003",
    "Finding Nemo": "2003",
    "The Departed": "2006",
    "Inglourious Basterds": "2009",
    "Slumdog Millionaire": "2008",
    "Pan's Labyrinth": "2006",
    "Avatar (2009 film)": "2009",
    "Up (2009 film)": "2009",
    "Inception": "2010",
    "The Social Network": "2010",
    "Black Swan (film)": "2010",
    "Django Unchained": "2012",
    "Interstellar (film)": "2014",
    "Mad Max: Fury Road": "2015",
    "Whiplash (2014 film)": "2014",
    "Birdman (film)": "2014",
    "The Grand Budapest Hotel": "2014",
    "La La Land": "2016",
    "Get Out": "2017",
    "Moonlight (2016 film)": "2016",
    "Parasite (2019 film)": "2019",
    "1917 (film)": "2019",
    "Joker (2019 film)": "2019",
    "Coco (film)": "2017",
    "Inside Out (film)": "2015",
    "The Revenant (2015 film)": "2015",
    "Dunkirk (2017 film)": "2017",
    "Bohemian Rhapsody (film)": "2018",
    "A Star Is Born (2018 film)": "2018",
    "Spider-Man: Into the Spider-Verse": "2018",
    "Dune (2021 film)": "2021",
    "Everything Everywhere All at Once": "2022",
    "Oppenheimer (film)": "2023",
    "Top Gun: Maverick": "2022",
    "Seven Samurai": "1954",
    "Rashomon": "1950",
    "Tokyo Story": "1953",
    "In the Mood for Love": "2000",
    "Crouching Tiger, Hidden Dragon": "2000",
    "Oldboy (2003 film)": "2003",
    "Pather Panchali": "1955",
    "The 400 Blows": "1959",
    "Breathless (1960 film)": "1960",
    "8½": "1963",
    "Cinema Paradiso": "1988",
    "Life Is Beautiful (film)": "1997",
    "Y Tu Mamá También": "2001",
    "Roma (2018 film)": "2018",
    "Bicycle Thieves": "1948",
    "Stalker (1979 film)": "1979",
    "The Battle of Algiers": "1966",
    "Aguirre, the Wrath of God": "1972",
    "Wings of Desire": "1987",
    "Amores Perros": "2000",
    "The Handmaiden": "2016",
    "Shoplifters (film)": "2018",
    "Drive My Car (film)": "2021",
    # Horror
    "The Texas Chain Saw Massacre": "1974",
    "Halloween (1978 film)": "1978",
    "A Nightmare on Elm Street": "1984",
    "Rosemary's Baby (film)": "1968",
    "The Omen": "1976",
    "Hereditary (film)": "2018",
    "Midsommar": "2019",
    "The Babadook": "2014",
    "It Follows": "2014",
    "The Conjuring": "2013",
    "Suspiria (1977 film)": "1977",
    # Action/Adventure
    "John Wick (film)": "2014",
    "Mission: Impossible (film)": "1996",
    "The Bourne Identity (2002 film)": "2002",
    "Hero (2002 film)": "2002",
    "House of Flying Daggers": "2004",
    "Terminator 2: Judgment Day": "1991",
    "RoboCop (1987 film)": "1987",
    # War
    "The Thin Red Line (1998 film)": "1998",
    "Come and See": "1985",
    "Paths of Glory": "1957",
    "The Deer Hunter": "1978",
    "The Pianist (2002 film)": "2002",
    "Downfall (2004 film)": "2004",
    "Letters from Iwo Jima": "2006",
    "Hacksaw Ridge": "2016",
    # Musical
    "Cabaret (1972 film)": "1972",
    "Chicago (2002 film)": "2002",
    "Moulin Rouge!": "2001",
    "Mary Poppins (film)": "1964",
    "Les Misérables (2012 film)": "2012",
    # International - India
    "Lagaan": "2001",
    "Dangal (film)": "2016",
    "3 Idiots": "2009",
    "Dil Se..": "1998",
    "Sholay": "1975",
    # International - Iran
    "A Separation": "2011",
    "Close-Up (1990 film)": "1990",
    "Taste of Cherry": "1997",
    # International - Africa
    "Timbuktu (2014 film)": "2014",
    "Atlantics": "2019",
    # International - East Asia
    "Chungking Express": "1994",
    "Infernal Affairs": "2002",
    "Memories of Murder": "2003",
    "A Brighter Summer Day": "1991",
    "Yi Yi": "2000",
    # International - Latin America
    "The Secret in Their Eyes": "2009",
    "Central Station (film)": "1998",
    "Wild Tales (film)": "2014",
    # 2020s
    "Nomadland": "2020",
    "The Power of the Dog (film)": "2021",
    "CODA (2021 film)": "2021",
    "Minari (film)": "2020",
    "The Banshees of Inisherin": "2022",
    "Triangle of Sadness": "2022",
    "Anatomy of a Fall": "2023",
    "Past Lives (film)": "2023",
    "The Zone of Interest (film)": "2023",
    "Killers of the Flower Moon (film)": "2023",
    "Poor Things (film)": "2023",
    "All Quiet on the Western Front (2022 film)": "2022",
    # Documentaries
    "March of the Penguins": "2005",
    "An Inconvenient Truth": "2006",
    "Won't You Be My Neighbor?": "2018",
    "Free Solo": "2018",
    "My Octopus Teacher": "2020",
    # Animated (non-Disney)
    "Akira (1988 film)": "1988",
    "Ghost in the Shell (1995 film)": "1995",
    "Princess Mononoke": "1997",
    "Howl's Moving Castle (film)": "2004",
    "Your Name": "2016",
    "Persepolis (film)": "2007",
    "The Triplets of Belleville": "2003",
    "Waltz with Bashir": "2008",
    # Comedy
    "The Apartment (1960 film)": "1960",
    "Dr. Strangelove": "1964",
    "Young Frankenstein": "1974",
    "Airplane!": "1980",
    "This Is Spinal Tap": "1984",
    "When Harry Met Sally...": "1989",
    "Groundhog Day": "1993",
    "Clueless": "1995",
    "In Bruges": "2008",
    "Superbad": "2007",
    "Shaun of the Dead": "2004",
    "The Royal Tenenbaums": "2001",
    "Lost in Translation (film)": "2003",
    "Little Miss Sunshine": "2006",
    "Juno (film)": "2007",
    "The Hangover": "2009",
    "Bridesmaids (2011 film)": "2011",
    # Thriller
    "North by Northwest": "1959",
    "The French Connection": "1971",
    "Marathon Man (film)": "1976",
    "Zodiac (film)": "2007",
    "Gone Girl (film)": "2014",
    "Nightcrawler (film)": "2014",
    "Sicario (2015 film)": "2015",
    "Prisoners (2013 film)": "2013",
    "Shutter Island": "2010",
    "The Prestige (film)": "2006",
    # Sci-fi
    "Solaris (1972 film)": "1972",
    "Close Encounters of the Third Kind": "1977",
    "The Thing (1982 film)": "1982",
    "Total Recall (1990 film)": "1990",
    "The Fifth Element": "1997",
    "District 9": "2009",
    "Arrival (2016 film)": "2016",
    "Ex Machina (film)": "2014",
    "Annihilation (film)": "2018",
    "Her (film)": "2013",
    "Blade Runner 2049": "2017",
    "Gravity (2013 film)": "2013",
    "The Martian (film)": "2015",
    # Romance/Drama
    "Brief Encounter": "1945",
    "An Affair to Remember": "1957",
    "The Graduate": "1967",
    "Love Story (1970 film)": "1970",
    "Out of Africa (film)": "1985",
    "The English Patient (film)": "1996",
    "Before Sunrise": "1995",
    "Atonement (2007 film)": "2007",
    "The Notebook (film)": "2004",
    "Call Me by Your Name (film)": "2017",
    "Carol (film)": "2015",
    "Portrait of a Lady on Fire": "2019",
    "Phantom Thread": "2017",
    # Western
    "The Searchers": "1956",
    "Unforgiven": "1992",
    "Butch Cassidy and the Sundance Kid": "1969",
    "Once Upon a Time in the West": "1968",
    "True Grit (2010 film)": "2010",
    "Hell or High Water (film)": "2016",
    # Crime
    "Double Indemnity": "1944",
    "The Third Man": "1949",
    "Touch of Evil": "1958",
    "Bonnie and Clyde (film)": "1967",
    "The Conversation": "1974",
    "Dog Day Afternoon": "1975",
    "Casino (1995 film)": "1995",
    "L.A. Confidential (film)": "1997",
    "The Town (2010 film)": "2010",
    "Uncut Gems": "2019",
    # Disney/Pixar
    "Snow White and the Seven Dwarfs (1937 film)": "1937",
    "Pinocchio (1940 film)": "1940",
    "Sleeping Beauty (1959 film)": "1959",
    "The Little Mermaid (1989 film)": "1989",
    "Beauty and the Beast (1991 film)": "1991",
    "Aladdin (1992 film)": "1992",
    "Monsters, Inc.": "2001",
    "The Incredibles": "2004",
    "Inside Out 2": "2024",
    "Soul (2020 film)": "2020",
    "Turning Red": "2022",
    "Encanto": "2021",
    # 2020s additions
    "The Father (2020 film)": "2020",
    "Promising Young Woman": "2020",
    "Dune: Part Two": "2024",
    "The Holdovers": "2023",
    "American Fiction (film)": "2023",
    "Saltburn (film)": "2023",
    "Barbie (film)": "2023",
    "The Batman (film)": "2022",
    "Nope (film)": "2022",
    "Tár": "2022",
    "Decision to Leave": "2022",
    "RRR (film)": "2022",
    "The Fabelmans": "2022",
    "Aftersun": "2022",
    "The Whale (2022 film)": "2022",
    "Women Talking (film)": "2022",
    "Anora (film)": "2024",
    "The Brutalist": "2024",
    "Conclave (film)": "2024",
    "Emilia Pérez": "2024",
    "The Substance (film)": "2024",
    "Flow (2024 film)": "2024",
}

ALL = [
    # 1920s-1940s
    "Metropolis (1927 film)",
    "Nosferatu",
    "The Wizard of Oz (1939 film)",
    "Gone with the Wind (film)",
    "Citizen Kane",
    "Casablanca (film)",
    "It's a Wonderful Life",
    "Bambi",
    "Fantasia (1940 film)",
    # 1950s
    "Singin' in the Rain",
    "Rear Window",
    "Vertigo (film)",
    "12 Angry Men (1957 film)",
    "Ben-Hur (1959 film)",
    "The Bridge on the River Kwai",
    "Some Like It Hot",
    "Roman Holiday",
    "Sunset Boulevard (film)",
    "Paths of Glory",
    # 1960s
    "Psycho (1960 film)",
    "Lawrence of Arabia (film)",
    "The Good, the Bad and the Ugly",
    "2001: A Space Odyssey (film)",
    "Doctor Zhivago (film)",
    "The Sound of Music (film)",
    "West Side Story (1961 film)",
    "Breakfast at Tiffany's (film)",
    "The Birds (film)",
    "Mary Poppins (film)",
    "Rosemary's Baby (film)",
    # 1970s
    "The Godfather",
    "The Godfather Part II",
    "Jaws (film)",
    "Star Wars (film)",
    "Apocalypse Now",
    "A Clockwork Orange (film)",
    "The Exorcist",
    "Taxi Driver",
    "Rocky (1976 film)",
    "One Flew Over the Cuckoo's Nest (film)",
    "Chinatown (1974 film)",
    "The Sting (film)",
    "Grease (film)",
    "Alien (film)",
    "Monty Python and the Holy Grail",
    "Annie Hall",
    "The Texas Chain Saw Massacre",
    "The Omen",
    "Cabaret (1972 film)",
    "Suspiria (1977 film)",
    "The Deer Hunter",
    "Halloween (1978 film)",
    # 1980s
    "The Empire Strikes Back",
    "Return of the Jedi",
    "Raiders of the Lost Ark",
    "E.T. the Extra-Terrestrial",
    "Blade Runner",
    "The Shining (film)",
    "Back to the Future",
    "The Breakfast Club",
    "Ghostbusters (1984 film)",
    "Die Hard",
    "Full Metal Jacket",
    "Scarface (1983 film)",
    "Raging Bull",
    "Platoon (film)",
    "Rain Man",
    "Amadeus (film)",
    "The Princess Bride (film)",
    "Batman (1989 film)",
    "Ferris Bueller's Day Off",
    "Top Gun",
    "Dirty Dancing",
    "A Nightmare on Elm Street",
    "Come and See",
    "RoboCop (1987 film)",
    "Akira (1988 film)",
    # 1990s
    "Pulp Fiction",
    "The Shawshank Redemption",
    "Schindler's List",
    "Forrest Gump",
    "Goodfellas",
    "The Silence of the Lambs (film)",
    "Fight Club (film)",
    "The Matrix",
    "Titanic (1997 film)",
    "Jurassic Park (film)",
    "Saving Private Ryan",
    "The Lion King",
    "Braveheart (film)",
    "Fargo (1996 film)",
    "Se7en",
    "The Big Lebowski",
    "American Beauty (1999 film)",
    "The Sixth Sense",
    "The Truman Show",
    "Good Will Hunting",
    "Trainspotting (film)",
    "The Usual Suspects",
    "Heat (1995 film)",
    "Toy Story",
    "Edward Scissorhands",
    "Terminator 2: Judgment Day",
    "Mission: Impossible (film)",
    "The Thin Red Line (1998 film)",
    "Ghost in the Shell (1995 film)",
    "Princess Mononoke",
    "Chungking Express",
    # 2000s
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Gladiator (2000 film)",
    "Memento (film)",
    "Spirited Away",
    "Amélie",
    "City of God (2002 film)",
    "Kill Bill: Volume 1",
    "Eternal Sunshine of the Spotless Mind",
    "The Dark Knight",
    "No Country for Old Men (film)",
    "There Will Be Blood",
    "WALL-E",
    "Ratatouille",
    "Harry Potter and the Philosopher's Stone (film)",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Finding Nemo",
    "The Departed",
    "Inglourious Basterds",
    "Slumdog Millionaire",
    "Pan's Labyrinth",
    "Avatar (2009 film)",
    "Up (2009 film)",
    "The Bourne Identity (2002 film)",
    "Hero (2002 film)",
    "House of Flying Daggers",
    "The Pianist (2002 film)",
    "Downfall (2004 film)",
    "Letters from Iwo Jima",
    "Chicago (2002 film)",
    "Moulin Rouge!",
    "Lagaan",
    "Infernal Affairs",
    "Memories of Murder",
    "The Triplets of Belleville",
    "Howl's Moving Castle (film)",
    "March of the Penguins",
    "An Inconvenient Truth",
    "Persepolis (film)",
    "Waltz with Bashir",
    "The Secret in Their Eyes",
    "3 Idiots",
    "Taste of Cherry",
    "Central Station (film)",
    # 2010s
    "Inception",
    "The Social Network",
    "Black Swan (film)",
    "Django Unchained",
    "Interstellar (film)",
    "Mad Max: Fury Road",
    "Whiplash (2014 film)",
    "Birdman (film)",
    "The Grand Budapest Hotel",
    "La La Land",
    "Get Out",
    "Moonlight (2016 film)",
    "Parasite (2019 film)",
    "1917 (film)",
    "Joker (2019 film)",
    "Coco (film)",
    "Inside Out (film)",
    "The Revenant (2015 film)",
    "Dunkirk (2017 film)",
    "Bohemian Rhapsody (film)",
    "A Star Is Born (2018 film)",
    "Spider-Man: Into the Spider-Verse",
    "The Conjuring",
    "The Babadook",
    "It Follows",
    "Hereditary (film)",
    "Midsommar",
    "John Wick (film)",
    "Hacksaw Ridge",
    "Les Misérables (2012 film)",
    "A Separation",
    "Timbuktu (2014 film)",
    "Atlantics",
    "Dangal (film)",
    "Your Name",
    "Wild Tales (film)",
    "Dil Se..",
    "Won't You Be My Neighbor?",
    "Free Solo",
    "Close-Up (1990 film)",
    "A Brighter Summer Day",
    # 2020s
    "Dune (2021 film)",
    "Everything Everywhere All at Once",
    "Oppenheimer (film)",
    "Top Gun: Maverick",
    "Nomadland",
    "The Power of the Dog (film)",
    "CODA (2021 film)",
    "Minari (film)",
    "The Banshees of Inisherin",
    "Triangle of Sadness",
    "Anatomy of a Fall",
    "Past Lives (film)",
    "The Zone of Interest (film)",
    "Killers of the Flower Moon (film)",
    "Poor Things (film)",
    "All Quiet on the Western Front (2022 film)",
    "My Octopus Teacher",
    # International cinema
    "Seven Samurai",
    "Rashomon",
    "Tokyo Story",
    "In the Mood for Love",
    "Crouching Tiger, Hidden Dragon",
    "Oldboy (2003 film)",
    "Pather Panchali",
    "The 400 Blows",
    "Breathless (1960 film)",
    "8½",
    "Cinema Paradiso",
    "Life Is Beautiful (film)",
    "Y Tu Mamá También",
    "Roma (2018 film)",
    "Bicycle Thieves",
    "Stalker (1979 film)",
    "The Battle of Algiers",
    "Aguirre, the Wrath of God",
    "Wings of Desire",
    "Amores Perros",
    "The Handmaiden",
    "Shoplifters (film)",
    "Drive My Car (film)",
    "Sholay",
    "Yi Yi",
    # Comedy
    "The Apartment (1960 film)",
    "Dr. Strangelove",
    "Young Frankenstein",
    "Airplane!",
    "This Is Spinal Tap",
    "When Harry Met Sally...",
    "Groundhog Day",
    "Clueless",
    "In Bruges",
    "Superbad",
    "Shaun of the Dead",
    "The Royal Tenenbaums",
    "Lost in Translation (film)",
    "Little Miss Sunshine",
    "Juno (film)",
    "The Hangover",
    "Bridesmaids (2011 film)",
    # Thriller
    "North by Northwest",
    "The French Connection",
    "Marathon Man (film)",
    "Zodiac (film)",
    "Gone Girl (film)",
    "Nightcrawler (film)",
    "Sicario (2015 film)",
    "Prisoners (2013 film)",
    "Shutter Island",
    "The Prestige (film)",
    # Sci-fi
    "Solaris (1972 film)",
    "Close Encounters of the Third Kind",
    "The Thing (1982 film)",
    "Total Recall (1990 film)",
    "The Fifth Element",
    "District 9",
    "Arrival (2016 film)",
    "Ex Machina (film)",
    "Annihilation (film)",
    "Her (film)",
    "Blade Runner 2049",
    "Gravity (2013 film)",
    "The Martian (film)",
    # Romance/Drama
    "Brief Encounter",
    "An Affair to Remember",
    "The Graduate",
    "Love Story (1970 film)",
    "Out of Africa (film)",
    "The English Patient (film)",
    "Before Sunrise",
    "Atonement (2007 film)",
    "The Notebook (film)",
    "Call Me by Your Name (film)",
    "Carol (film)",
    "Portrait of a Lady on Fire",
    "Phantom Thread",
    # Western
    "The Searchers",
    "Unforgiven",
    "Butch Cassidy and the Sundance Kid",
    "Once Upon a Time in the West",
    "True Grit (2010 film)",
    "Hell or High Water (film)",
    # Crime
    "Double Indemnity",
    "The Third Man",
    "Touch of Evil",
    "Bonnie and Clyde (film)",
    "The Conversation",
    "Dog Day Afternoon",
    "Casino (1995 film)",
    "L.A. Confidential (film)",
    "The Town (2010 film)",
    "Uncut Gems",
    # Disney/Pixar
    "Snow White and the Seven Dwarfs (1937 film)",
    "Pinocchio (1940 film)",
    "Sleeping Beauty (1959 film)",
    "The Little Mermaid (1989 film)",
    "Beauty and the Beast (1991 film)",
    "Aladdin (1992 film)",
    "Monsters, Inc.",
    "The Incredibles",
    "Inside Out 2",
    "Soul (2020 film)",
    "Turning Red",
    "Encanto",
    # 2020s additions
    "The Father (2020 film)",
    "Promising Young Woman",
    "Dune: Part Two",
    "The Holdovers",
    "American Fiction (film)",
    "Saltburn (film)",
    "Barbie (film)",
    "The Batman (film)",
    "Nope (film)",
    "Tár",
    "Decision to Leave",
    "RRR (film)",
    "The Fabelmans",
    "Aftersun",
    "The Whale (2022 film)",
    "Women Talking (film)",
    "Anora (film)",
    "The Brutalist",
    "Conclave (film)",
    "Emilia Pérez",
    "The Substance (film)",
    "Flow (2024 film)",
]
