ALL = [
    # 1920s-1940s
    "Metropolis (1927 film)", "Nosferatu", "The Wizard of Oz (1939 film)",
    "Gone with the Wind (film)", "Citizen Kane", "Casablanca (film)",
    "It's a Wonderful Life", "Bambi", "Fantasia (1940 film)",
    # 1950s
    "Singin' in the Rain", "Rear Window", "Vertigo (film)",
    "12 Angry Men (1957 film)", "Ben-Hur (1959 film)",
    "The Bridge on the River Kwai", "Some Like It Hot",
    "Roman Holiday", "Sunset Boulevard (film)",
    # 1960s
    "Psycho (1960 film)", "Lawrence of Arabia (film)",
    "The Good, the Bad and the Ugly", "2001: A Space Odyssey (film)",
    "Doctor Zhivago (film)", "The Sound of Music (film)",
    "West Side Story (1961 film)", "Breakfast at Tiffany's (film)",
    "The Birds (film)",
    # 1970s
    "The Godfather", "The Godfather Part II", "Jaws (film)",
    "Star Wars (film)", "Apocalypse Now", "A Clockwork Orange (film)",
    "The Exorcist", "Taxi Driver", "Rocky (1976 film)",
    "One Flew Over the Cuckoo's Nest (film)", "Chinatown (1974 film)",
    "The Sting (film)", "Grease (film)", "Alien (film)",
    "Monty Python and the Holy Grail", "Annie Hall",
    # 1980s
    "The Empire Strikes Back", "Return of the Jedi",
    "Raiders of the Lost Ark", "E.T. the Extra-Terrestrial",
    "Blade Runner", "The Shining (film)", "Back to the Future",
    "The Breakfast Club", "Ghostbusters (1984 film)",
    "Die Hard", "Full Metal Jacket", "Scarface (1983 film)",
    "Raging Bull", "Platoon (film)", "Rain Man",
    "Amadeus (film)", "The Princess Bride (film)",
    "Batman (1989 film)", "Ferris Bueller's Day Off",
    "Top Gun", "Dirty Dancing",
    # 1990s
    "Pulp Fiction", "The Shawshank Redemption", "Schindler's List",
    "Forrest Gump", "Goodfellas", "The Silence of the Lambs (film)",
    "Fight Club (film)", "The Matrix", "Titanic (1997 film)",
    "Jurassic Park (film)", "Saving Private Ryan", "The Lion King",
    "Braveheart (film)", "Fargo (1996 film)", "Se7en",
    "The Big Lebowski", "American Beauty (1999 film)",
    "The Sixth Sense", "The Truman Show",
    "Good Will Hunting", "Trainspotting (film)",
    "The Usual Suspects", "Heat (1995 film)",
    "Toy Story", "Edward Scissorhands",
    # 2000s
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Gladiator (2000 film)", "Memento (film)",
    "Spirited Away", "Amélie", "City of God (2002 film)",
    "Kill Bill: Volume 1", "Eternal Sunshine of the Spotless Mind",
    "The Dark Knight", "No Country for Old Men (film)",
    "There Will Be Blood", "WALL-E", "Ratatouille",
    "Harry Potter and the Philosopher's Stone (film)",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Finding Nemo", "The Departed", "Inglourious Basterds",
    "Slumdog Millionaire", "Pan's Labyrinth",
    "Avatar (2009 film)", "Up (2009 film)",
    # 2010s
    "Inception", "The Social Network", "Black Swan (film)",
    "Django Unchained", "Interstellar (film)", "Mad Max: Fury Road",
    "Whiplash (2014 film)", "Birdman (film)",
    "The Grand Budapest Hotel", "La La Land",
    "Get Out", "Moonlight (2016 film)", "Parasite (2019 film)",
    "1917 (film)", "Joker (2019 film)",
    "Coco (film)", "Inside Out (film)",
    "The Revenant (2015 film)", "Dunkirk (2017 film)",
    "Bohemian Rhapsody (film)", "A Star Is Born (2018 film)",
    "Spider-Man: Into the Spider-Verse",
    # 2020s
    "Dune (2021 film)", "Everything Everywhere All at Once",
    "Oppenheimer (film)", "Top Gun: Maverick",
    # International cinema
    "Seven Samurai", "Rashomon", "Tokyo Story",
    "In the Mood for Love", "Crouching Tiger, Hidden Dragon",
    "Oldboy (2003 film)", "Pather Panchali", "The 400 Blows",
    "Breathless (1960 film)", "8½", "Cinema Paradiso",
    "Life Is Beautiful (film)", "Y Tu Mamá También",
    "Roma (2018 film)", "Bicycle Thieves",
    "Stalker (1979 film)", "The Battle of Algiers",
    "Aguirre, the Wrath of God", "Wings of Desire",
    "Amores Perros", "The Handmaiden",
    "Shoplifters (film)", "Drive My Car (film)",
]
