ALL = [
    # Waterfalls
    "Angel Falls", "Ban Gioc–Detian Falls", "Dettifoss", "Epupa Falls",
    "Gullfoss", "Havasu Falls", "Iguazu Falls", "Kaieteur Falls",
    "Murchison Falls", "Niagara Falls", "Plitvice Lakes National Park", "Seljalandsfoss",
    "Skógafoss", "Sutherland Falls", "Tegenungan Waterfall", "Thi Lo Su Waterfall",
    "Tugela Falls", "Victoria Falls", "Yosemite Falls",
    # Mountains & peaks
    "Annapurna", "Cerro Torre", "Denali", "Dhaulagiri",
    "Dolomites", "Drakensberg", "El Capitan", "Fitz Roy",
    "Half Dome", "Jaya Peak", "Jebel Shams", "K2",
    "Kangchenjunga", "Kirkjufell", "Lhotse", "Makalu",
    "Manaslu", "Matterhorn", "Mont Blanc", "Mount Apo",
    "Mount Ararat", "Mount Cameroon", "Mount Cook", "Mount Damavand",
    "Mount Elbrus", "Mount Everest", "Mount Fuji", "Mount Kenya",
    "Mount Kilimanjaro", "Mount Kinabalu", "Mount Olympus", "Mount Rainier",
    "Mount Rinjani", "Nanda Devi", "Nanga Parbat", "Pikes Peak",
    "Rwenzori Mountains", "Simien Mountains", "Sugarloaf Mountain", "Table Mountain",
    "Torres del Paine",
    # Volcanoes
    "Arenal Volcano", "Cotopaxi", "Erta Ale", "Eyjafjallajökull",
    "Kilauea", "Krakatoa", "Mauna Loa", "Mount Agung",
    "Mount Bromo", "Mount Etna", "Mount Fuji", "Mount Merapi",
    "Mount Nyiragongo", "Mount Pinatubo", "Mount St. Helens", "Mount Vesuvius",
    "Ol Doinyo Lengai", "Popocatépetl", "Stromboli", "Taal Volcano",
    "Teide",
    # Canyons & gorges
    "Antelope Canyon", "Blyde River Canyon", "Bryce Canyon", "Colca Canyon",
    "Fish River Canyon", "Grand Canyon", "Tara River Canyon", "Tiger Leaping Gorge",
    "Todra Gorge", "Verdon Gorge", "Waimea Canyon", "Zion National Park",
    # Deserts
    "Atacama Desert", "Chalbi Desert", "Danakil Desert", "Dasht-e Lut",
    "Death Valley", "Gobi Desert", "Kalahari Desert", "Mojave Desert",
    "Namib Desert", "Rub' al Khali (Empty Quarter)", "Sahara", "Salar de Uyuni",
    "Simpson Desert", "Sossusvlei", "Thar Desert", "Wadi Rum",
    "Wahiba Sands", "White Sands National Park",
    # Caves
    "Amboni Caves", "Batu Caves", "Blue Grotto (Capri)", "Cango Caves",
    "Carlsbad Caverns", "Deer Cave", "Eisriesenwelt", "Hang Sơn Đoòng",
    "Mammoth Cave National Park", "Phong Nha Cave", "Puerto Princesa Underground River", "Reed Flute Cave",
    "Waitomo Glowworm Caves", "Škocjan Caves",
    # Lakes
    "Crater Lake", "Dal Lake", "Dead Sea", "Great Salt Lake",
    "Lake Atitlán", "Lake Baikal", "Lake Bled", "Lake Chad",
    "Lake Como", "Lake Garda", "Lake Inle", "Lake Kivu",
    "Lake Louise", "Lake Malawi", "Lake Nakuru", "Lake Ohrid",
    "Lake Tanganyika", "Lake Titicaca", "Lake Toba", "Lake Turkana",
    "Lake Victoria", "Loch Ness", "Moraine Lake", "Pangong Lake",
    "Plitvice Lakes National Park",
    # Forests & jungles
    "Amazon rainforest", "Bamboo forest", "Białowieża Forest", "Black Forest",
    "Borneo rainforest", "Bwindi Impenetrable Forest", "Congo rainforest", "Daintree Rainforest",
    "Khao Sok National Park", "Monteverde Cloud Forest Reserve", "Nyungwe Forest", "Redwood National and State Parks",
    "Sherwood Forest", "Sinharaja Forest Reserve", "Sundarbans", "Taman Negara",
    "Tongass National Forest", "Western Ghats", "Yakushima",
    # Glaciers & ice
    "Aletsch Glacier", "Baltoro Glacier", "Fox Glacier", "Glacier Bay",
    "Jökulsárlón", "Mendenhall Glacier", "Perito Moreno Glacier", "Siachen Glacier",
    "Vatnajökull",
    # Reefs & marine
    "Aldabra Atoll", "Belize Barrier Reef", "Blue Hole (Belize)", "Galápagos Islands",
    "Great Barrier Reef", "Maldives", "Ningaloo Reef", "Raja Ampat Islands",
    "Tubbataha Reefs", "Wakatobi National Park",
    # Rock formations
    "Al Ula", "Arches National Park", "Bungle Bungle Range", "Cappadocia",
    "Chocolate Hills", "Devil's Tower", "Fairy Chimneys", "Giant's Causeway",
    "Ha Long Bay", "Meteora", "Moab, Utah", "Monument Valley",
    "Phang Nga Bay", "Pinnacles (Western Australia)", "Tsingy de Bemaraha", "Twelve Apostles (Victoria)",
    "Uluru", "Wave (Arizona)", "Zhangjiajie",
    # National parks & reserves (Africa)
    "Bwindi Impenetrable National Park", "Chobe National Park", "Etosha National Park", "Hwange National Park",
    "Kruger National Park", "Lower Zambezi National Park", "Masai Mara National Reserve", "Ngorongoro Crater",
    "Okavango Delta", "Serengeti National Park", "South Luangwa National Park", "Virunga National Park",
    # National parks & reserves (Asia)
    "Cat Tien National Park", "Chitwan National Park", "Gunung Mulu National Park", "Jim Corbett National Park",
    "Kaziranga National Park", "Khao Sok National Park", "Kinabalu National Park", "Komodo National Park",
    "Ranthambore National Park",
    # Islands & coastlines
    "Amalfi Coast", "Andaman Islands", "Bora Bora", "Cliffs of Moher",
    "Cook Islands", "Faroe Islands", "Fernando de Noronha", "Fiji",
    "Galápagos Islands", "Great Ocean Road", "Lamu Island", "Langkawi",
    "Lofoten", "Madagascar", "Maldives", "Na Pali Coast",
    "Nusa Penida", "Palau", "Palawan", "Phi Phi Islands",
    "Samoa", "Santorini", "Seychelles", "Socotra",
    "São Tomé", "Tonga", "Vanuatu", "White Cliffs of Dover",
    "Zanzibar",
    # Geothermal & unique
    "Blue Lagoon (geothermal spa)", "Chocolate Hills", "Dallol", "Danakil Depression",
    "Geysir", "Jeju Island", "Lake Natron", "Northern Lights",
    "Pamukkale", "Salar de Uyuni", "Socotra", "Waitomo Glowworm Caves",
    "Yellowstone National Park", "Zhangye Danxia",
]

LOCATIONS = {
    # Waterfalls
    "Niagara Falls": "USA/Canada",
    "Iguazu Falls": "Argentina/Brazil",
    "Victoria Falls": "Zambia/Zimbabwe",
    "Angel Falls": "Venezuela",
    "Yosemite Falls": "USA",
    "Gullfoss": "Iceland",
    "Dettifoss": "Iceland",
    "Plitvice Lakes National Park": "Croatia",
    "Kaieteur Falls": "Guyana",
    "Havasu Falls": "USA",
    "Seljalandsfoss": "Iceland",
    "Skógafoss": "Iceland",
    "Sutherland Falls": "New Zealand",
    "Ban Gioc–Detian Falls": "Vietnam/China",
    "Tugela Falls": "South Africa",
    "Epupa Falls": "Namibia/Angola",
    "Murchison Falls": "Uganda",
    "Thi Lo Su Waterfall": "Thailand",
    "Tegenungan Waterfall": "Indonesia",
    # Mountains
    "Mount Everest": "Nepal/China",
    "K2": "Pakistan/China",
    "Matterhorn": "Switzerland/Italy",
    "Mont Blanc": "France/Italy",
    "Mount Kilimanjaro": "Tanzania",
    "Denali": "USA",
    "Mount Fuji": "Japan",
    "Table Mountain": "South Africa",
    "Kirkjufell": "Iceland",
    "Mount Rainier": "USA",
    "Mount Elbrus": "Russia",
    "Mount Olympus": "Greece",
    "Dolomites": "Italy",
    "Torres del Paine": "Chile",
    "Cerro Torre": "Argentina",
    "Fitz Roy": "Argentina",
    "Mount Cook": "New Zealand",
    "Mount Kenya": "Kenya",
    "Mount Ararat": "Turkey",
    "Annapurna": "Nepal",
    "Kangchenjunga": "Nepal/India",
    "Makalu": "Nepal/China",
    "Nanga Parbat": "Pakistan",
    "Pikes Peak": "USA",
    "Half Dome": "USA",
    "El Capitan": "USA",
    "Sugarloaf Mountain": "Brazil",
    "Mount Cameroon": "Cameroon",
    "Rwenzori Mountains": "Uganda/DR Congo",
    "Simien Mountains": "Ethiopia",
    "Drakensberg": "South Africa/Lesotho",
    "Mount Kinabalu": "Malaysia",
    "Mount Apo": "Philippines",
    "Mount Damavand": "Iran",
    "Jebel Shams": "Oman",
    "Nanda Devi": "India",
    "Manaslu": "Nepal",
    "Dhaulagiri": "Nepal",
    "Lhotse": "Nepal/China",
    "Mount Rinjani": "Indonesia",
    "Jaya Peak": "Indonesia",
    # Volcanoes
    "Mount Vesuvius": "Italy",
    "Mount Etna": "Italy",
    "Mount St. Helens": "USA",
    "Krakatoa": "Indonesia",
    "Eyjafjallajökull": "Iceland",
    "Kilauea": "USA",
    "Mauna Loa": "USA",
    "Mount Pinatubo": "Philippines",
    "Cotopaxi": "Ecuador",
    "Mount Bromo": "Indonesia",
    "Arenal Volcano": "Costa Rica",
    "Stromboli": "Italy",
    "Popocatépetl": "Mexico",
    "Teide": "Spain",
    "Ol Doinyo Lengai": "Tanzania",
    "Mount Nyiragongo": "DR Congo",
    "Erta Ale": "Ethiopia",
    "Mount Merapi": "Indonesia",
    "Taal Volcano": "Philippines",
    "Mount Agung": "Indonesia",
    # Canyons
    "Grand Canyon": "USA",
    "Antelope Canyon": "USA",
    "Bryce Canyon": "USA",
    "Zion National Park": "USA",
    "Fish River Canyon": "Namibia",
    "Colca Canyon": "Peru",
    "Verdon Gorge": "France",
    "Tiger Leaping Gorge": "China",
    "Waimea Canyon": "USA",
    "Blyde River Canyon": "South Africa",
    "Todra Gorge": "Morocco",
    "Tara River Canyon": "Montenegro",
    # Deserts
    "Sahara": "North Africa",
    "Gobi Desert": "Mongolia/China",
    "Atacama Desert": "Chile",
    "Namib Desert": "Namibia",
    "Kalahari Desert": "Southern Africa",
    "Mojave Desert": "USA",
    "Wadi Rum": "Jordan",
    "White Sands National Park": "USA",
    "Salar de Uyuni": "Bolivia",
    "Sossusvlei": "Namibia",
    "Death Valley": "USA",
    "Thar Desert": "India/Pakistan",
    "Simpson Desert": "Australia",
    "Rub' al Khali (Empty Quarter)": "Saudi Arabia/Oman/UAE/Yemen",
    "Dasht-e Lut": "Iran",
    "Wahiba Sands": "Oman",
    "Danakil Desert": "Ethiopia/Eritrea",
    "Chalbi Desert": "Kenya",
    # Caves
    "Mammoth Cave National Park": "USA",
    "Carlsbad Caverns": "USA",
    "Waitomo Glowworm Caves": "New Zealand",
    "Hang Sơn Đoòng": "Vietnam",
    "Škocjan Caves": "Slovenia",
    "Blue Grotto (Capri)": "Italy",
    "Reed Flute Cave": "China",
    "Eisriesenwelt": "Austria",
    "Puerto Princesa Underground River": "Philippines",
    "Deer Cave": "Malaysia",
    "Phong Nha Cave": "Vietnam",
    "Batu Caves": "Malaysia",
    "Cango Caves": "South Africa",
    "Amboni Caves": "Tanzania",
    # Lakes
    "Lake Baikal": "Russia",
    "Lake Titicaca": "Peru/Bolivia",
    "Lake Victoria": "East Africa",
    "Lake Como": "Italy",
    "Lake Bled": "Slovenia",
    "Crater Lake": "USA",
    "Dead Sea": "Israel/Jordan",
    "Lake Louise": "Canada",
    "Moraine Lake": "Canada",
    "Lake Malawi": "Malawi",
    "Great Salt Lake": "USA",
    "Loch Ness": "Scotland",
    "Lake Garda": "Italy",
    "Lake Atitlán": "Guatemala",
    "Lake Ohrid": "North Macedonia",
    "Lake Tanganyika": "Tanzania/DR Congo/Burundi/Zambia",
    "Lake Turkana": "Kenya/Ethiopia",
    "Lake Nakuru": "Kenya",
    "Lake Toba": "Indonesia",
    "Lake Inle": "Myanmar",
    "Pangong Lake": "India/China",
    "Dal Lake": "India",
    "Lake Kivu": "Rwanda/DR Congo",
    "Lake Chad": "Chad/Cameroon/Nigeria/Niger",
    # Forests
    "Amazon rainforest": "South America",
    "Black Forest": "Germany",
    "Redwood National and State Parks": "USA",
    "Białowieża Forest": "Poland/Belarus",
    "Daintree Rainforest": "Australia",
    "Tongass National Forest": "USA",
    "Yakushima": "Japan",
    "Monteverde Cloud Forest Reserve": "Costa Rica",
    "Borneo rainforest": "Borneo",
    "Sherwood Forest": "England",
    "Congo rainforest": "Central Africa",
    "Sinharaja Forest Reserve": "Sri Lanka",
    "Taman Negara": "Malaysia",
    "Khao Sok National Park": "Thailand",
    "Western Ghats": "India",
    "Sundarbans": "Bangladesh/India",
    "Nyungwe Forest": "Rwanda",
    "Bwindi Impenetrable Forest": "Uganda",
    # Glaciers
    "Perito Moreno Glacier": "Argentina",
    "Vatnajökull": "Iceland",
    "Fox Glacier": "New Zealand",
    "Jökulsárlón": "Iceland",
    "Glacier Bay": "USA",
    "Mendenhall Glacier": "USA",
    "Aletsch Glacier": "Switzerland",
    "Siachen Glacier": "India/Pakistan",
    "Baltoro Glacier": "Pakistan",
    # Reefs & marine
    "Great Barrier Reef": "Australia",
    "Belize Barrier Reef": "Belize",
    "Blue Hole (Belize)": "Belize",
    "Maldives": "Maldives",
    "Galápagos Islands": "Ecuador",
    "Raja Ampat Islands": "Indonesia",
    "Tubbataha Reefs": "Philippines",
    "Aldabra Atoll": "Seychelles",
    "Ningaloo Reef": "Australia",
    "Wakatobi National Park": "Indonesia",
    # Rock formations
    "Uluru": "Australia",
    "Giant's Causeway": "Northern Ireland",
    "Cappadocia": "Turkey",
    "Monument Valley": "USA",
    "Twelve Apostles (Victoria)": "Australia",
    "Zhangjiajie": "China",
    "Ha Long Bay": "Vietnam",
    "Meteora": "Greece",
    "Devil's Tower": "USA",
    "Arches National Park": "USA",
    "Tsingy de Bemaraha": "Madagascar",
    "Phang Nga Bay": "Thailand",
    "Al Ula": "Saudi Arabia",
    "Bungle Bungle Range": "Australia",
    # National parks & reserves (Africa)
    "Serengeti National Park": "Tanzania",
    "Okavango Delta": "Botswana",
    "Kruger National Park": "South Africa",
    "Etosha National Park": "Namibia",
    "Masai Mara National Reserve": "Kenya",
    "Bwindi Impenetrable National Park": "Uganda",
    "Ngorongoro Crater": "Tanzania",
    "Virunga National Park": "DR Congo",
    "Hwange National Park": "Zimbabwe",
    "South Luangwa National Park": "Zambia",
    "Chobe National Park": "Botswana",
    "Lower Zambezi National Park": "Zambia",
    # National parks & reserves (Asia)
    "Komodo National Park": "Indonesia",
    "Jim Corbett National Park": "India",
    "Ranthambore National Park": "India",
    "Kaziranga National Park": "India",
    "Chitwan National Park": "Nepal",
    "Gunung Mulu National Park": "Malaysia",
    "Cat Tien National Park": "Vietnam",
    "Kinabalu National Park": "Malaysia",
    # Islands & coastlines
    "Bora Bora": "French Polynesia",
    "Santorini": "Greece",
    "Seychelles": "Seychelles",
    "Phi Phi Islands": "Thailand",
    "Fernando de Noronha": "Brazil",
    "Socotra": "Yemen",
    "Madagascar": "Madagascar",
    "Faroe Islands": "Denmark",
    "Lofoten": "Norway",
    "Na Pali Coast": "USA",
    "Cliffs of Moher": "Ireland",
    "White Cliffs of Dover": "England",
    "Amalfi Coast": "Italy",
    "Great Ocean Road": "Australia",
    "Palau": "Palau",
    "Fiji": "Fiji",
    "Vanuatu": "Vanuatu",
    "Samoa": "Samoa",
    "Tonga": "Tonga",
    "Cook Islands": "Cook Islands",
    "Zanzibar": "Tanzania",
    "Lamu Island": "Kenya",
    "São Tomé": "São Tomé and Príncipe",
    "Andaman Islands": "India",
    "Palawan": "Philippines",
    "Nusa Penida": "Indonesia",
    "Langkawi": "Malaysia",
    # Geothermal & unique
    "Yellowstone National Park": "USA",
    "Geysir": "Iceland",
    "Pamukkale": "Turkey",
    "Blue Lagoon (geothermal spa)": "Iceland",
    "Jeju Island": "South Korea",
    "Danakil Depression": "Ethiopia",
    "Chocolate Hills": "Philippines",
    "Northern Lights": "Arctic",
    "Zhangye Danxia": "China",
    "Lake Natron": "Tanzania",
    "Dallol": "Ethiopia",
}
