ALL = [
    # Waterfalls
    "Niagara Falls", "Iguazu Falls", "Victoria Falls",
    "Angel Falls", "Yosemite Falls", "Gullfoss",
    "Dettifoss", "Plitvice Lakes National Park", "Kaieteur Falls",
    "Havasu Falls", "Seljalandsfoss", "Skógafoss",
    "Sutherland Falls", "Ban Gioc–Detian Falls",
    "Tugela Falls", "Epupa Falls", "Murchison Falls",
    "Thi Lo Su Waterfall", "Tegenungan Waterfall",
    # Mountains & peaks
    "Mount Everest", "K2", "Matterhorn", "Mont Blanc",
    "Mount Kilimanjaro", "Denali", "Mount Fuji",
    "Table Mountain", "Kirkjufell", "Mount Rainier",
    "Mount Elbrus", "Mount Olympus", "Dolomites",
    "Torres del Paine", "Cerro Torre", "Fitz Roy",
    "Mount Cook", "Mount Kenya", "Mount Ararat",
    "Annapurna", "Kangchenjunga", "Makalu",
    "Nanga Parbat", "Pikes Peak", "Half Dome",
    "El Capitan", "Sugarloaf Mountain",
    "Mount Cameroon", "Rwenzori Mountains", "Simien Mountains",
    "Drakensberg", "Mount Kinabalu", "Mount Apo",
    "Mount Damavand", "Jebel Shams", "Nanda Devi",
    "Manaslu", "Dhaulagiri", "Lhotse",
    "Mount Rinjani", "Jaya Peak",
    # Volcanoes
    "Mount Vesuvius", "Mount Etna", "Mount St. Helens",
    "Krakatoa", "Eyjafjallajökull", "Kilauea",
    "Mauna Loa", "Mount Pinatubo", "Cotopaxi",
    "Mount Bromo", "Arenal Volcano", "Stromboli",
    "Mount Fuji", "Popocatépetl", "Teide",
    "Ol Doinyo Lengai", "Mount Nyiragongo", "Erta Ale",
    "Mount Merapi", "Taal Volcano", "Mount Agung",
    # Canyons & gorges
    "Grand Canyon", "Antelope Canyon", "Bryce Canyon",
    "Zion National Park", "Fish River Canyon",
    "Colca Canyon", "Verdon Gorge", "Tiger Leaping Gorge",
    "Waimea Canyon", "Blyde River Canyon",
    "Todra Gorge", "Tara River Canyon",
    # Deserts
    "Sahara", "Gobi Desert", "Atacama Desert",
    "Namib Desert", "Kalahari Desert", "Mojave Desert",
    "Wadi Rum", "White Sands National Park",
    "Salar de Uyuni", "Sossusvlei", "Death Valley",
    "Thar Desert", "Simpson Desert",
    "Rub' al Khali (Empty Quarter)", "Dasht-e Lut",
    "Wahiba Sands", "Danakil Desert", "Chalbi Desert",
    # Caves
    "Mammoth Cave National Park", "Carlsbad Caverns",
    "Waitomo Glowworm Caves", "Hang Sơn Đoòng",
    "Škocjan Caves", "Blue Grotto (Capri)",
    "Reed Flute Cave", "Eisriesenwelt",
    "Puerto Princesa Underground River", "Deer Cave",
    "Phong Nha Cave", "Batu Caves",
    "Cango Caves", "Amboni Caves",
    # Lakes
    "Lake Baikal", "Lake Titicaca", "Lake Victoria",
    "Lake Como", "Lake Bled", "Crater Lake",
    "Dead Sea", "Plitvice Lakes National Park",
    "Lake Louise", "Moraine Lake", "Lake Malawi",
    "Great Salt Lake", "Loch Ness", "Lake Garda",
    "Lake Atitlán", "Lake Ohrid",
    "Lake Tanganyika", "Lake Turkana", "Lake Nakuru",
    "Lake Toba", "Lake Inle", "Pangong Lake",
    "Dal Lake", "Lake Kivu", "Lake Chad",
    # Forests & jungles
    "Amazon rainforest", "Black Forest", "Redwood National and State Parks",
    "Białowieża Forest", "Daintree Rainforest",
    "Tongass National Forest", "Yakushima",
    "Monteverde Cloud Forest Reserve", "Borneo rainforest",
    "Sherwood Forest", "Bamboo forest",
    "Congo rainforest", "Sinharaja Forest Reserve",
    "Taman Negara", "Khao Sok National Park",
    "Western Ghats", "Sundarbans",
    "Nyungwe Forest", "Bwindi Impenetrable Forest",
    # Glaciers & ice
    "Perito Moreno Glacier", "Vatnajökull",
    "Fox Glacier", "Jökulsárlón", "Glacier Bay",
    "Mendenhall Glacier", "Aletsch Glacier",
    "Siachen Glacier", "Baltoro Glacier",
    # Reefs & marine
    "Great Barrier Reef", "Belize Barrier Reef",
    "Blue Hole (Belize)", "Maldives",
    "Galápagos Islands", "Raja Ampat Islands",
    "Tubbataha Reefs", "Aldabra Atoll",
    "Ningaloo Reef", "Wakatobi National Park",
    # Rock formations
    "Uluru", "Giant's Causeway", "Cappadocia",
    "Moab, Utah", "Monument Valley", "Wave (Arizona)",
    "Twelve Apostles (Victoria)", "Zhangjiajie",
    "Ha Long Bay", "Meteora", "Fairy Chimneys",
    "Devil's Tower", "Arches National Park",
    "Pinnacles (Western Australia)", "Tsingy de Bemaraha",
    "Phang Nga Bay", "Al Ula", "Chocolate Hills",
    "Bungle Bungle Range",
    # National parks & reserves (Africa)
    "Serengeti National Park", "Okavango Delta",
    "Kruger National Park", "Etosha National Park",
    "Masai Mara National Reserve", "Bwindi Impenetrable National Park",
    "Ngorongoro Crater", "Virunga National Park",
    "Hwange National Park", "South Luangwa National Park",
    "Chobe National Park", "Lower Zambezi National Park",
    # National parks & reserves (Asia)
    "Komodo National Park", "Khao Sok National Park",
    "Jim Corbett National Park", "Ranthambore National Park",
    "Kaziranga National Park", "Chitwan National Park",
    "Gunung Mulu National Park", "Cat Tien National Park",
    "Kinabalu National Park",
    # Islands & coastlines
    "Galápagos Islands", "Bora Bora", "Maldives",
    "Santorini", "Seychelles", "Phi Phi Islands",
    "Fernando de Noronha", "Socotra", "Madagascar",
    "Faroe Islands", "Lofoten", "Na Pali Coast",
    "Cliffs of Moher", "White Cliffs of Dover",
    "Amalfi Coast", "Great Ocean Road",
    "Palau", "Fiji", "Vanuatu",
    "Samoa", "Tonga", "Cook Islands",
    "Zanzibar", "Lamu Island", "São Tomé",
    "Andaman Islands", "Palawan",
    "Nusa Penida", "Langkawi",
    # Geothermal & unique
    "Yellowstone National Park", "Geysir",
    "Pamukkale", "Blue Lagoon (geothermal spa)",
    "Jeju Island", "Danakil Depression",
    "Chocolate Hills", "Waitomo Glowworm Caves",
    "Northern Lights", "Zhangye Danxia",
    "Socotra", "Salar de Uyuni",
    "Lake Natron", "Dallol",
]

LOCATIONS = {
    # Waterfalls
    "Niagara Falls": "USA/Canada",
    "Iguazu Falls": "Argentina/Brazil",
    "Victoria Falls": "Zambia/Zimbabwe",
    "Angel Falls": "Venezuela",
    "Yosemite Falls": "USA",
    "Gullfoss": "Iceland",
    "Dettifoss": "Iceland",
    "Plitvice Lakes National Park": "Croatia",
    "Kaieteur Falls": "Guyana",
    "Havasu Falls": "USA",
    "Seljalandsfoss": "Iceland",
    "Skógafoss": "Iceland",
    "Sutherland Falls": "New Zealand",
    "Ban Gioc–Detian Falls": "Vietnam/China",
    "Tugela Falls": "South Africa",
    "Epupa Falls": "Namibia/Angola",
    "Murchison Falls": "Uganda",
    "Thi Lo Su Waterfall": "Thailand",
    "Tegenungan Waterfall": "Indonesia",
    # Mountains
    "Mount Everest": "Nepal/China",
    "K2": "Pakistan/China",
    "Matterhorn": "Switzerland/Italy",
    "Mont Blanc": "France/Italy",
    "Mount Kilimanjaro": "Tanzania",
    "Denali": "USA",
    "Mount Fuji": "Japan",
    "Table Mountain": "South Africa",
    "Kirkjufell": "Iceland",
    "Mount Rainier": "USA",
    "Mount Elbrus": "Russia",
    "Mount Olympus": "Greece",
    "Dolomites": "Italy",
    "Torres del Paine": "Chile",
    "Cerro Torre": "Argentina",
    "Fitz Roy": "Argentina",
    "Mount Cook": "New Zealand",
    "Mount Kenya": "Kenya",
    "Mount Ararat": "Turkey",
    "Annapurna": "Nepal",
    "Kangchenjunga": "Nepal/India",
    "Makalu": "Nepal/China",
    "Nanga Parbat": "Pakistan",
    "Pikes Peak": "USA",
    "Half Dome": "USA",
    "El Capitan": "USA",
    "Sugarloaf Mountain": "Brazil",
    "Mount Cameroon": "Cameroon",
    "Rwenzori Mountains": "Uganda/DR Congo",
    "Simien Mountains": "Ethiopia",
    "Drakensberg": "South Africa/Lesotho",
    "Mount Kinabalu": "Malaysia",
    "Mount Apo": "Philippines",
    "Mount Damavand": "Iran",
    "Jebel Shams": "Oman",
    "Nanda Devi": "India",
    "Manaslu": "Nepal",
    "Dhaulagiri": "Nepal",
    "Lhotse": "Nepal/China",
    "Mount Rinjani": "Indonesia",
    "Jaya Peak": "Indonesia",
    # Volcanoes
    "Mount Vesuvius": "Italy",
    "Mount Etna": "Italy",
    "Mount St. Helens": "USA",
    "Krakatoa": "Indonesia",
    "Eyjafjallajökull": "Iceland",
    "Kilauea": "USA",
    "Mauna Loa": "USA",
    "Mount Pinatubo": "Philippines",
    "Cotopaxi": "Ecuador",
    "Mount Bromo": "Indonesia",
    "Arenal Volcano": "Costa Rica",
    "Stromboli": "Italy",
    "Popocatépetl": "Mexico",
    "Teide": "Spain",
    "Ol Doinyo Lengai": "Tanzania",
    "Mount Nyiragongo": "DR Congo",
    "Erta Ale": "Ethiopia",
    "Mount Merapi": "Indonesia",
    "Taal Volcano": "Philippines",
    "Mount Agung": "Indonesia",
    # Canyons
    "Grand Canyon": "USA",
    "Antelope Canyon": "USA",
    "Bryce Canyon": "USA",
    "Zion National Park": "USA",
    "Fish River Canyon": "Namibia",
    "Colca Canyon": "Peru",
    "Verdon Gorge": "France",
    "Tiger Leaping Gorge": "China",
    "Waimea Canyon": "USA",
    "Blyde River Canyon": "South Africa",
    "Todra Gorge": "Morocco",
    "Tara River Canyon": "Montenegro",
    # Deserts
    "Sahara": "North Africa",
    "Gobi Desert": "Mongolia/China",
    "Atacama Desert": "Chile",
    "Namib Desert": "Namibia",
    "Kalahari Desert": "Southern Africa",
    "Mojave Desert": "USA",
    "Wadi Rum": "Jordan",
    "White Sands National Park": "USA",
    "Salar de Uyuni": "Bolivia",
    "Sossusvlei": "Namibia",
    "Death Valley": "USA",
    "Thar Desert": "India/Pakistan",
    "Simpson Desert": "Australia",
    "Rub' al Khali (Empty Quarter)": "Saudi Arabia/Oman/UAE/Yemen",
    "Dasht-e Lut": "Iran",
    "Wahiba Sands": "Oman",
    "Danakil Desert": "Ethiopia/Eritrea",
    "Chalbi Desert": "Kenya",
    # Caves
    "Mammoth Cave National Park": "USA",
    "Carlsbad Caverns": "USA",
    "Waitomo Glowworm Caves": "New Zealand",
    "Hang Sơn Đoòng": "Vietnam",
    "Škocjan Caves": "Slovenia",
    "Blue Grotto (Capri)": "Italy",
    "Reed Flute Cave": "China",
    "Eisriesenwelt": "Austria",
    "Puerto Princesa Underground River": "Philippines",
    "Deer Cave": "Malaysia",
    "Phong Nha Cave": "Vietnam",
    "Batu Caves": "Malaysia",
    "Cango Caves": "South Africa",
    "Amboni Caves": "Tanzania",
    # Lakes
    "Lake Baikal": "Russia",
    "Lake Titicaca": "Peru/Bolivia",
    "Lake Victoria": "East Africa",
    "Lake Como": "Italy",
    "Lake Bled": "Slovenia",
    "Crater Lake": "USA",
    "Dead Sea": "Israel/Jordan",
    "Lake Louise": "Canada",
    "Moraine Lake": "Canada",
    "Lake Malawi": "Malawi",
    "Great Salt Lake": "USA",
    "Loch Ness": "Scotland",
    "Lake Garda": "Italy",
    "Lake Atitlán": "Guatemala",
    "Lake Ohrid": "North Macedonia",
    "Lake Tanganyika": "Tanzania/DR Congo/Burundi/Zambia",
    "Lake Turkana": "Kenya/Ethiopia",
    "Lake Nakuru": "Kenya",
    "Lake Toba": "Indonesia",
    "Lake Inle": "Myanmar",
    "Pangong Lake": "India/China",
    "Dal Lake": "India",
    "Lake Kivu": "Rwanda/DR Congo",
    "Lake Chad": "Chad/Cameroon/Nigeria/Niger",
    # Forests
    "Amazon rainforest": "South America",
    "Black Forest": "Germany",
    "Redwood National and State Parks": "USA",
    "Białowieża Forest": "Poland/Belarus",
    "Daintree Rainforest": "Australia",
    "Tongass National Forest": "USA",
    "Yakushima": "Japan",
    "Monteverde Cloud Forest Reserve": "Costa Rica",
    "Borneo rainforest": "Borneo",
    "Sherwood Forest": "England",
    "Congo rainforest": "Central Africa",
    "Sinharaja Forest Reserve": "Sri Lanka",
    "Taman Negara": "Malaysia",
    "Khao Sok National Park": "Thailand",
    "Western Ghats": "India",
    "Sundarbans": "Bangladesh/India",
    "Nyungwe Forest": "Rwanda",
    "Bwindi Impenetrable Forest": "Uganda",
    # Glaciers
    "Perito Moreno Glacier": "Argentina",
    "Vatnajökull": "Iceland",
    "Fox Glacier": "New Zealand",
    "Jökulsárlón": "Iceland",
    "Glacier Bay": "USA",
    "Mendenhall Glacier": "USA",
    "Aletsch Glacier": "Switzerland",
    "Siachen Glacier": "India/Pakistan",
    "Baltoro Glacier": "Pakistan",
    # Reefs & marine
    "Great Barrier Reef": "Australia",
    "Belize Barrier Reef": "Belize",
    "Blue Hole (Belize)": "Belize",
    "Maldives": "Maldives",
    "Galápagos Islands": "Ecuador",
    "Raja Ampat Islands": "Indonesia",
    "Tubbataha Reefs": "Philippines",
    "Aldabra Atoll": "Seychelles",
    "Ningaloo Reef": "Australia",
    "Wakatobi National Park": "Indonesia",
    # Rock formations
    "Uluru": "Australia",
    "Giant's Causeway": "Northern Ireland",
    "Cappadocia": "Turkey",
    "Monument Valley": "USA",
    "Twelve Apostles (Victoria)": "Australia",
    "Zhangjiajie": "China",
    "Ha Long Bay": "Vietnam",
    "Meteora": "Greece",
    "Devil's Tower": "USA",
    "Arches National Park": "USA",
    "Tsingy de Bemaraha": "Madagascar",
    "Phang Nga Bay": "Thailand",
    "Al Ula": "Saudi Arabia",
    "Bungle Bungle Range": "Australia",
    # National parks & reserves (Africa)
    "Serengeti National Park": "Tanzania",
    "Okavango Delta": "Botswana",
    "Kruger National Park": "South Africa",
    "Etosha National Park": "Namibia",
    "Masai Mara National Reserve": "Kenya",
    "Bwindi Impenetrable National Park": "Uganda",
    "Ngorongoro Crater": "Tanzania",
    "Virunga National Park": "DR Congo",
    "Hwange National Park": "Zimbabwe",
    "South Luangwa National Park": "Zambia",
    "Chobe National Park": "Botswana",
    "Lower Zambezi National Park": "Zambia",
    # National parks & reserves (Asia)
    "Komodo National Park": "Indonesia",
    "Jim Corbett National Park": "India",
    "Ranthambore National Park": "India",
    "Kaziranga National Park": "India",
    "Chitwan National Park": "Nepal",
    "Gunung Mulu National Park": "Malaysia",
    "Cat Tien National Park": "Vietnam",
    "Kinabalu National Park": "Malaysia",
    # Islands & coastlines
    "Bora Bora": "French Polynesia",
    "Santorini": "Greece",
    "Seychelles": "Seychelles",
    "Phi Phi Islands": "Thailand",
    "Fernando de Noronha": "Brazil",
    "Socotra": "Yemen",
    "Madagascar": "Madagascar",
    "Faroe Islands": "Denmark",
    "Lofoten": "Norway",
    "Na Pali Coast": "USA",
    "Cliffs of Moher": "Ireland",
    "White Cliffs of Dover": "England",
    "Amalfi Coast": "Italy",
    "Great Ocean Road": "Australia",
    "Palau": "Palau",
    "Fiji": "Fiji",
    "Vanuatu": "Vanuatu",
    "Samoa": "Samoa",
    "Tonga": "Tonga",
    "Cook Islands": "Cook Islands",
    "Zanzibar": "Tanzania",
    "Lamu Island": "Kenya",
    "São Tomé": "São Tomé and Príncipe",
    "Andaman Islands": "India",
    "Palawan": "Philippines",
    "Nusa Penida": "Indonesia",
    "Langkawi": "Malaysia",
    # Geothermal & unique
    "Yellowstone National Park": "USA",
    "Geysir": "Iceland",
    "Pamukkale": "Turkey",
    "Blue Lagoon (geothermal spa)": "Iceland",
    "Jeju Island": "South Korea",
    "Danakil Depression": "Ethiopia",
    "Chocolate Hills": "Philippines",
    "Northern Lights": "Arctic",
    "Zhangye Danxia": "China",
    "Lake Natron": "Tanzania",
    "Dallol": "Ethiopia",
}
