ALL = [
    # Waterfalls
    "Niagara Falls", "Iguazu Falls", "Victoria Falls",
    "Angel Falls", "Yosemite Falls", "Gullfoss",
    "Dettifoss", "Plitvice Lakes National Park", "Kaieteur Falls",
    "Havasu Falls", "Seljalandsfoss", "Skógafoss",
    "Sutherland Falls", "Ban Gioc–Detian Falls",
    # Mountains & peaks
    "Mount Everest", "K2", "Matterhorn", "Mont Blanc",
    "Mount Kilimanjaro", "Denali", "Mount Fuji",
    "Table Mountain", "Kirkjufell", "Mount Rainier",
    "Mount Elbrus", "Mount Olympus", "Dolomites",
    "Torres del Paine", "Cerro Torre", "Fitz Roy",
    "Mount Cook", "Mount Kenya", "Mount Ararat",
    "Annapurna", "Kangchenjunga", "Makalu",
    "Nanga Parbat", "Pikes Peak", "Half Dome",
    "El Capitan", "Sugarloaf Mountain",
    # Volcanoes
    "Mount Vesuvius", "Mount Etna", "Mount St. Helens",
    "Krakatoa", "Eyjafjallajökull", "Kilauea",
    "Mauna Loa", "Mount Pinatubo", "Cotopaxi",
    "Mount Bromo", "Arenal Volcano", "Stromboli",
    "Mount Fuji", "Popocatépetl", "Teide",
    # Canyons & gorges
    "Grand Canyon", "Antelope Canyon", "Bryce Canyon",
    "Zion National Park", "Fish River Canyon",
    "Colca Canyon", "Verdon Gorge", "Tiger Leaping Gorge",
    "Waimea Canyon", "Blyde River Canyon",
    # Deserts
    "Sahara", "Gobi Desert", "Atacama Desert",
    "Namib Desert", "Kalahari Desert", "Mojave Desert",
    "Wadi Rum", "White Sands National Park",
    "Salar de Uyuni", "Sossusvlei", "Death Valley",
    "Thar Desert", "Simpson Desert",
    # Caves
    "Mammoth Cave National Park", "Carlsbad Caverns",
    "Waitomo Glowworm Caves", "Hang Sơn Đoòng",
    "Škocjan Caves", "Blue Grotto (Capri)",
    "Reed Flute Cave", "Eisriesenwelt",
    # Lakes
    "Lake Baikal", "Lake Titicaca", "Lake Victoria",
    "Lake Como", "Lake Bled", "Crater Lake",
    "Dead Sea", "Plitvice Lakes National Park",
    "Lake Louise", "Moraine Lake", "Lake Malawi",
    "Great Salt Lake", "Loch Ness", "Lake Garda",
    "Lake Atitlán", "Lake Ohrid",
    # Forests & jungles
    "Amazon rainforest", "Black Forest", "Redwood National and State Parks",
    "Białowieża Forest", "Daintree Rainforest",
    "Tongass National Forest", "Yakushima",
    "Monteverde Cloud Forest Reserve", "Borneo rainforest",
    "Sherwood Forest", "Bamboo forest",
    # Glaciers & ice
    "Perito Moreno Glacier", "Vatnajökull",
    "Fox Glacier", "Jökulsárlón", "Glacier Bay",
    "Mendenhall Glacier", "Aletsch Glacier",
    # Reefs & marine
    "Great Barrier Reef", "Belize Barrier Reef",
    "Blue Hole (Belize)", "Maldives",
    "Galápagos Islands", "Raja Ampat Islands",
    # Rock formations
    "Uluru", "Giant's Causeway", "Cappadocia",
    "Moab, Utah", "Monument Valley", "Wave (Arizona)",
    "Twelve Apostles (Victoria)", "Zhangjiajie",
    "Ha Long Bay", "Meteora", "Fairy Chimneys",
    "Devil's Tower", "Arches National Park",
    "Pinnacles (Western Australia)", "Tsingy de Bemaraha",
    # Islands & coastlines
    "Galápagos Islands", "Bora Bora", "Maldives",
    "Santorini", "Seychelles", "Phi Phi Islands",
    "Fernando de Noronha", "Socotra", "Madagascar",
    "Faroe Islands", "Lofoten", "Na Pali Coast",
    "Cliffs of Moher", "White Cliffs of Dover",
    "Amalfi Coast", "Great Ocean Road",
    # Geothermal & unique
    "Yellowstone National Park", "Geysir",
    "Pamukkale", "Blue Lagoon (geothermal spa)",
    "Jeju Island", "Danakil Depression",
    "Chocolate Hills", "Waitomo Glowworm Caves",
    "Northern Lights", "Zhangye Danxia",
    "Socotra", "Salar de Uyuni",
]

LOCATIONS = {
    # Waterfalls
    "Niagara Falls": "USA/Canada",
    "Iguazu Falls": "Argentina/Brazil",
    "Victoria Falls": "Zambia/Zimbabwe",
    "Angel Falls": "Venezuela",
    "Yosemite Falls": "USA",
    "Gullfoss": "Iceland",
    "Dettifoss": "Iceland",
    "Plitvice Lakes National Park": "Croatia",
    "Kaieteur Falls": "Guyana",
    "Havasu Falls": "USA",
    "Seljalandsfoss": "Iceland",
    "Skógafoss": "Iceland",
    "Sutherland Falls": "New Zealand",
    "Ban Gioc–Detian Falls": "Vietnam/China",
    # Mountains
    "Mount Everest": "Nepal/China",
    "K2": "Pakistan/China",
    "Matterhorn": "Switzerland/Italy",
    "Mont Blanc": "France/Italy",
    "Mount Kilimanjaro": "Tanzania",
    "Denali": "USA",
    "Mount Fuji": "Japan",
    "Table Mountain": "South Africa",
    "Kirkjufell": "Iceland",
    "Mount Rainier": "USA",
    "Mount Elbrus": "Russia",
    "Mount Olympus": "Greece",
    "Dolomites": "Italy",
    "Torres del Paine": "Chile",
    "Cerro Torre": "Argentina",
    "Fitz Roy": "Argentina",
    "Mount Cook": "New Zealand",
    "Mount Kenya": "Kenya",
    "Mount Ararat": "Turkey",
    "Annapurna": "Nepal",
    "Kangchenjunga": "Nepal/India",
    "Makalu": "Nepal/China",
    "Nanga Parbat": "Pakistan",
    "Pikes Peak": "USA",
    "Half Dome": "USA",
    "El Capitan": "USA",
    "Sugarloaf Mountain": "Brazil",
    # Volcanoes
    "Mount Vesuvius": "Italy",
    "Mount Etna": "Italy",
    "Mount St. Helens": "USA",
    "Krakatoa": "Indonesia",
    "Eyjafjallajökull": "Iceland",
    "Kilauea": "USA",
    "Mauna Loa": "USA",
    "Mount Pinatubo": "Philippines",
    "Cotopaxi": "Ecuador",
    "Mount Bromo": "Indonesia",
    "Arenal Volcano": "Costa Rica",
    "Stromboli": "Italy",
    "Popocatépetl": "Mexico",
    "Teide": "Spain",
    # Canyons
    "Grand Canyon": "USA",
    "Antelope Canyon": "USA",
    "Bryce Canyon": "USA",
    "Zion National Park": "USA",
    "Fish River Canyon": "Namibia",
    "Colca Canyon": "Peru",
    "Verdon Gorge": "France",
    "Tiger Leaping Gorge": "China",
    "Waimea Canyon": "USA",
    "Blyde River Canyon": "South Africa",
    # Deserts
    "Sahara": "North Africa",
    "Gobi Desert": "Mongolia/China",
    "Atacama Desert": "Chile",
    "Namib Desert": "Namibia",
    "Kalahari Desert": "Southern Africa",
    "Mojave Desert": "USA",
    "Wadi Rum": "Jordan",
    "White Sands National Park": "USA",
    "Salar de Uyuni": "Bolivia",
    "Sossusvlei": "Namibia",
    "Death Valley": "USA",
    "Thar Desert": "India/Pakistan",
    "Simpson Desert": "Australia",
    # Caves
    "Mammoth Cave National Park": "USA",
    "Carlsbad Caverns": "USA",
    "Waitomo Glowworm Caves": "New Zealand",
    "Hang Sơn Đoòng": "Vietnam",
    "Škocjan Caves": "Slovenia",
    "Blue Grotto (Capri)": "Italy",
    "Reed Flute Cave": "China",
    "Eisriesenwelt": "Austria",
    # Lakes
    "Lake Baikal": "Russia",
    "Lake Titicaca": "Peru/Bolivia",
    "Lake Victoria": "East Africa",
    "Lake Como": "Italy",
    "Lake Bled": "Slovenia",
    "Crater Lake": "USA",
    "Dead Sea": "Israel/Jordan",
    "Lake Louise": "Canada",
    "Moraine Lake": "Canada",
    "Lake Malawi": "Malawi",
    "Great Salt Lake": "USA",
    "Loch Ness": "Scotland",
    "Lake Garda": "Italy",
    "Lake Atitlán": "Guatemala",
    "Lake Ohrid": "North Macedonia",
    # Forests
    "Amazon rainforest": "South America",
    "Black Forest": "Germany",
    "Redwood National and State Parks": "USA",
    "Białowieża Forest": "Poland/Belarus",
    "Daintree Rainforest": "Australia",
    "Tongass National Forest": "USA",
    "Yakushima": "Japan",
    "Monteverde Cloud Forest Reserve": "Costa Rica",
    "Borneo rainforest": "Borneo",
    "Sherwood Forest": "England",
    # Glaciers
    "Perito Moreno Glacier": "Argentina",
    "Vatnajökull": "Iceland",
    "Fox Glacier": "New Zealand",
    "Jökulsárlón": "Iceland",
    "Glacier Bay": "USA",
    "Mendenhall Glacier": "USA",
    "Aletsch Glacier": "Switzerland",
    # Reefs
    "Great Barrier Reef": "Australia",
    "Belize Barrier Reef": "Belize",
    "Blue Hole (Belize)": "Belize",
    "Maldives": "Maldives",
    "Galápagos Islands": "Ecuador",
    "Raja Ampat Islands": "Indonesia",
    # Rock formations
    "Uluru": "Australia",
    "Giant's Causeway": "Northern Ireland",
    "Cappadocia": "Turkey",
    "Monument Valley": "USA",
    "Twelve Apostles (Victoria)": "Australia",
    "Zhangjiajie": "China",
    "Ha Long Bay": "Vietnam",
    "Meteora": "Greece",
    "Devil's Tower": "USA",
    "Arches National Park": "USA",
    "Tsingy de Bemaraha": "Madagascar",
    # Islands & coastlines
    "Bora Bora": "French Polynesia",
    "Santorini": "Greece",
    "Seychelles": "Seychelles",
    "Phi Phi Islands": "Thailand",
    "Fernando de Noronha": "Brazil",
    "Socotra": "Yemen",
    "Faroe Islands": "Denmark",
    "Lofoten": "Norway",
    "Na Pali Coast": "USA",
    "Cliffs of Moher": "Ireland",
    "White Cliffs of Dover": "England",
    "Amalfi Coast": "Italy",
    "Great Ocean Road": "Australia",
    # Geothermal
    "Yellowstone National Park": "USA",
    "Geysir": "Iceland",
    "Pamukkale": "Turkey",
    "Blue Lagoon (geothermal spa)": "Iceland",
    "Jeju Island": "South Korea",
    "Danakil Depression": "Ethiopia",
    "Chocolate Hills": "Philippines",
    "Northern Lights": "Arctic",
    "Zhangye Danxia": "China",
}
