PAINTING_INFO = {
    # Renaissance
    "Mona Lisa": "Leonardo da Vinci, 1503",
    "The Last Supper (Leonardo)": "Leonardo da Vinci, 1498",
    "Annunciation (Leonardo)": "Leonardo da Vinci, 1475",
    "The Birth of Venus": "Sandro Botticelli, 1485",
    "Primavera (Botticelli)": "Sandro Botticelli, 1482",
    "The Creation of Adam": "Michelangelo, 1512",
    "The School of Athens": "Raphael, 1511",
    "Girl with a Pearl Earring": "Johannes Vermeer, 1665",
    "The Arnolfini Portrait": "Jan van Eyck, 1434",
    "The Garden of Earthly Delights": "Hieronymus Bosch, 1510",
    "The Sistine Madonna": "Raphael, 1512",
    "Venus of Urbino": "Titian, 1538",
    "Assumption of the Virgin (Titian)": "Titian, 1518",
    "The Tempest (Giorgione)": "Giorgione, 1508",
    "Self-Portrait (Albrecht Dürer, 1500)": "Albrecht Dürer, 1500",
    "Melencolia I": "Albrecht Dürer, 1514",
    "The Ambassadors (Holbein)": "Hans Holbein the Younger, 1533",
    "Sofonisba Anguissola Self-Portrait": "Sofonisba Anguissola, 1556",
    "The Chess Game (Sofonisba Anguissola)": "Sofonisba Anguissola, 1555",
    # Baroque
    "The Night Watch": "Rembrandt, 1642",
    "Las Meninas": "Diego Velázquez, 1656",
    "The Art of Painting": "Johannes Vermeer, 1668",
    "Judith Slaying Holofernes (Artemisia Gentileschi)": "Artemisia Gentileschi, 1620",
    "The Calling of Saint Matthew (Caravaggio)": "Caravaggio, 1600",
    "The Milkmaid (Vermeer)": "Johannes Vermeer, 1658",
    "Self-Portrait with Two Circles": "Rembrandt, 1665",
    "The Laughing Cavalier": "Frans Hals, 1624",
    "The Merry Drinker (Frans Hals)": "Frans Hals, 1628",
    "View of Haarlem (Jacob van Ruisdael)": "Jacob van Ruisdael, 1670",
    "The Jewish Cemetery (Jacob van Ruisdael)": "Jacob van Ruisdael, 1657",
    "The Courtyard of a House in Delft": "Pieter de Hooch, 1658",
    "A Woman Drinking with Two Men": "Pieter de Hooch, 1658",
    "Massacre of the Innocents (Rubens)": "Peter Paul Rubens, 1612",
    "The Elevation of the Cross (Rubens)": "Peter Paul Rubens, 1611",
    "Bacchus and Ariadne": "Titian, 1523",
    "Self-Portrait as the Allegory of Painting": "Artemisia Gentileschi, 1639",
    "Marie Antoinette with a Rose": "Élisabeth Vigée Le Brun, 1783",
    "Self-Portrait in a Straw Hat (Vigée Le Brun)": "Élisabeth Vigée Le Brun, 1782",
    # Neoclassicism
    "Napoleon Crossing the Alps": "Jacques-Louis David, 1801",
    "The Death of Marat": "Jacques-Louis David, 1793",
    "The Oath of the Horatii": "Jacques-Louis David, 1784",
    "The Coronation of Napoleon": "Jacques-Louis David, 1807",
    "The Grande Odalisque": "Jean-Auguste-Dominique Ingres, 1814",
    "The Turkish Bath (Ingres)": "Jean-Auguste-Dominique Ingres, 1862",
    # Romanticism
    "Liberty Leading the People": "Eugène Delacroix, 1830",
    "Wanderer above the Sea of Fog": "Caspar David Friedrich, 1818",
    "The Raft of the Medusa": "Théodore Géricault, 1819",
    "Rain, Steam and Speed": "J. M. W. Turner, 1844",
    "The Hay Wain": "John Constable, 1821",
    "Saturn Devouring His Son": "Francisco Goya, 1823",
    "The Third of May 1808": "Francisco Goya, 1814",
    "The Ninth Wave": "Ivan Aivazovsky, 1850",
    "The Fighting Temeraire": "J. M. W. Turner, 1839",
    "The Slave Ship (Turner)": "J. M. W. Turner, 1840",
    "The Abbey in the Oakwood": "Caspar David Friedrich, 1810",
    "The Nude Maja": "Francisco Goya, 1800",
    "Washington Crossing the Delaware": "Emanuel Leutze, 1851",
    # Pre-Raphaelite & Victorian
    "Ophelia (Millais)": "John Everett Millais, 1852",
    "The Lady of Shalott (Waterhouse)": "John William Waterhouse, 1888",
    "Beata Beatrix": "Dante Gabriel Rossetti, 1870",
    "Proserpine (Rossetti)": "Dante Gabriel Rossetti, 1874",
    "The Order of Release, 1746": "John Everett Millais, 1853",
    "Hylas and the Nymphs (Waterhouse)": "John William Waterhouse, 1896",
    "Flaming June": "Frederic Leighton, 1895",
    # British
    "A Rake's Progress": "William Hogarth, 1735",
    "Marriage A-la-Mode": "William Hogarth, 1743",
    "Mr and Mrs Andrews": "Thomas Gainsborough, 1750",
    "The Blue Boy": "Thomas Gainsborough, 1770",
    "Colonel Tarleton (Reynolds)": "Joshua Reynolds, 1782",
    "Whistler's Mother": "James Abbott McNeill Whistler, 1871",
    "Nocturne in Black and Gold": "James Abbott McNeill Whistler, 1875",
    "Carnation, Lily, Lily, Rose": "John Singer Sargent, 1886",
    "Madame X (Sargent)": "John Singer Sargent, 1884",
    "El Jaleo (Sargent)": "John Singer Sargent, 1882",
    # Russian
    "Reply of the Zaporozhian Cossacks": "Ilya Repin, 1891",
    "Barge Haulers on the Volga": "Ilya Repin, 1873",
    "Ivan the Terrible and His Son": "Ilya Repin, 1885",
    "The Rainbow (Aivazovsky)": "Ivan Aivazovsky, 1873",
    "Storm on the Sea at Night": "Ivan Aivazovsky, 1849",
    "The Rooks Have Returned": "Alexei Savrasov, 1871",
    "Morning in a Pine Forest": "Ivan Shishkin, 1889",
    # Impressionism
    "Impression, Sunrise": "Claude Monet, 1872",
    "Water Lilies (Monet series)": "Claude Monet, 1906",
    "A Sunday Afternoon on the Island of La Grande Jatte": "Georges Seurat, 1886",
    "Bal du moulin de la Galette": "Pierre-Auguste Renoir, 1876",
    "Luncheon of the Boating Party": "Pierre-Auguste Renoir, 1881",
    "Dance at Le Moulin de la Galette": "Pierre-Auguste Renoir, 1876",
    "The Dance Class (Degas)": "Edgar Degas, 1874",
    "A Bar at the Folies-Bergère": "Édouard Manet, 1882",
    "The Cradle (Berthe Morisot)": "Berthe Morisot, 1872",
    "Summer's Day (Berthe Morisot)": "Berthe Morisot, 1879",
    "The Boating Party (Mary Cassatt)": "Mary Cassatt, 1893",
    "The Child's Bath (Mary Cassatt)": "Mary Cassatt, 1893",
    "Rouen Cathedral (Monet series)": "Claude Monet, 1894",
    "Le Déjeuner sur l'herbe": "Édouard Manet, 1863",
    "Olympia (Manet)": "Édouard Manet, 1863",
    "The Floor Scrapers": "Gustave Caillebotte, 1875",
    "Paris Street; Rainy Day": "Gustave Caillebotte, 1877",
    # Post-Impressionism
    "The Starry Night": "Vincent van Gogh, 1889",
    "Sunflowers (Van Gogh series)": "Vincent van Gogh, 1888",
    "The Bedroom (Van Gogh)": "Vincent van Gogh, 1888",
    "Café Terrace at Night": "Vincent van Gogh, 1888",
    "The Card Players": "Paul Cézanne, 1895",
    "Mont Sainte-Victoire (Cézanne)": "Paul Cézanne, 1904",
    "Where Do We Come From? What Are We? Where Are We Going?": "Paul Gauguin, 1897",
    "The Yellow Christ": "Paul Gauguin, 1889",
    "The Joy of Life (Matisse)": "Henri Matisse, 1906",
    "The Dance (Matisse)": "Henri Matisse, 1910",
    "The Blue Room (Suzanne Valadon)": "Suzanne Valadon, 1923",
    "Adam and Eve (Suzanne Valadon)": "Suzanne Valadon, 1909",
    "Self-Portrait on the Sixth Wedding Anniversary": "Paula Modersohn-Becker, 1906",
    "Mother and Child (Paula Modersohn-Becker)": "Paula Modersohn-Becker, 1907",
    # Expressionism & Symbolism
    "The Scream": "Edvard Munch, 1893",
    "The Kiss (Klimt)": "Gustav Klimt, 1908",
    "The Persistence of Memory": "Salvador Dalí, 1931",
    "Guernica (Picasso)": "Pablo Picasso, 1937",
    "Les Demoiselles d'Avignon": "Pablo Picasso, 1907",
    "Portrait of Adele Bloch-Bauer I": "Gustav Klimt, 1907",
    "The Tree of Life (Klimt)": "Gustav Klimt, 1909",
    "The Blue Rider": "Wassily Kandinsky, 1903",
    "Composition VII (Kandinsky)": "Wassily Kandinsky, 1913",
    "Several Circles (Kandinsky)": "Wassily Kandinsky, 1926",
    "The Large Bathers (Cézanne)": "Paul Cézanne, 1906",
    "The Dream (Henri Rousseau)": "Henri Rousseau, 1910",
    "The Sleeping Gypsy": "Henri Rousseau, 1897",
    # Spanish modern
    "Walk on the Beach (Sorolla)": "Joaquín Sorolla, 1909",
    "Sad Inheritance (Sorolla)": "Joaquín Sorolla, 1899",
    "Boys on the Beach (Sorolla)": "Joaquín Sorolla, 1910",
    # Modern
    "American Gothic": "Grant Wood, 1930",
    "Nighthawks": "Edward Hopper, 1942",
    "Christina's World": "Andrew Wyeth, 1948",
    "Campbell's Soup Cans": "Andy Warhol, 1962",
    "Marilyn Diptych": "Andy Warhol, 1962",
    "No. 5, 1948": "Jackson Pollock, 1948",
    "Composition with Red Blue and Yellow": "Piet Mondrian, 1930",
    "Black Square (Malevich)": "Kazimir Malevich, 1915",
    "Broadway Boogie Woogie": "Piet Mondrian, 1943",
    "The Son of Man (Magritte)": "René Magritte, 1964",
    "The Treachery of Images": "René Magritte, 1929",
    "The Lovers (Magritte)": "René Magritte, 1928",
    "The Two Fridas": "Frida Kahlo, 1939",
    "The Broken Column": "Frida Kahlo, 1944",
    "Self-Portrait with Thorn Necklace and Hummingbird": "Frida Kahlo, 1940",
    "Dog Barking at the Moon": "Joan Miró, 1926",
    "Nude Descending a Staircase, No. 2": "Marcel Duchamp, 1912",
    "I and the Village": "Marc Chagall, 1911",
    "White on White (Malevich)": "Kazimir Malevich, 1918",
    "Suprematist Composition (Malevich)": "Kazimir Malevich, 1916",
    "No. 61 (Rust and Blue)": "Mark Rothko, 1953",
    "Orange, Red, Yellow": "Mark Rothko, 1961",
    "Woman I (de Kooning)": "Willem de Kooning, 1952",
    "Mountains and Sea": "Helen Frankenthaler, 1952",
    "Who's Afraid of Red, Yellow and Blue": "Barnett Newman, 1966",
    "Flag (Jasper Johns)": "Jasper Johns, 1955",
    "Whaam!": "Roy Lichtenstein, 1963",
    "Drowning Girl (Lichtenstein)": "Roy Lichtenstein, 1963",
    # American realism
    "Breezing Up (Winslow Homer)": "Winslow Homer, 1876",
    "The Gulf Stream (Winslow Homer)": "Winslow Homer, 1899",
    "Snap the Whip (Winslow Homer)": "Winslow Homer, 1872",
    "Freedom from Want (Norman Rockwell)": "Norman Rockwell, 1943",
    "Triple Self-Portrait (Norman Rockwell)": "Norman Rockwell, 1960",
    "Jimson Weed/White Flower No. 1": "Georgia O'Keeffe, 1932",
    "Black Iris (O'Keeffe)": "Georgia O'Keeffe, 1926",
    # Contemporary
    "Infinity Mirror Rooms": "Yayoi Kusama, 1965",
    "Girl with a Balloon": "Banksy, 2002",
    "Shot Sage Blue Marilyn": "Andy Warhol, 1964",
    "A Bigger Splash": "David Hockney, 1967",
    "Portrait of an Artist (Pool with Two Figures)": "David Hockney, 1972",
    "Untitled (Skull) (Basquiat)": "Jean-Michel Basquiat, 1981",
    "Untitled (1982) (Basquiat)": "Jean-Michel Basquiat, 1982",
    "Three Studies of Lucian Freud": "Francis Bacon, 1969",
    "Study after Velázquez's Portrait of Pope Innocent X": "Francis Bacon, 1953",
    "Benefits Supervisor Sleeping": "Lucian Freud, 1995",
    # Asian
    "Along the River During the Qingming Festival": "Zhang Zeduan, 1120",
    "The Great Wave off Kanagawa": "Hokusai, 1831",
    "Red Fuji": "Hokusai, 1831",
    "Pine Trees (Hasegawa Tōhaku)": "Hasegawa Tōhaku, 1595",
    "Dwelling in the Fuchun Mountains": "Huang Gongwang, 1350",
    "Travelers Among Mountains and Streams": "Fan Kuan, 1000",
    "Early Spring (Guo Xi)": "Guo Xi, 1072",
    "Shrimps (Qi Baishi)": "Qi Baishi, 1945",
    "Galloping Horse (Xu Beihong)": "Xu Beihong, 1941",
    "Sudden Shower over Shin-Ōhashi Bridge": "Hiroshige, 1857",
    "Night Snow at Kambara": "Hiroshige, 1833",
    "Wind God and Thunder God (Tawaraya Sōtatsu)": "Tawaraya Sōtatsu, 1625",
    "Irises (Ogata Kōrin)": "Ogata Kōrin, 1702",
    # Indian
    "Bharat Mata (Abanindranath Tagore)": "Abanindranath Tagore, 1905",
    "Three Girls (Amrita Sher-Gil)": "Amrita Sher-Gil, 1935",
    "Brahmacharis (Amrita Sher-Gil)": "Amrita Sher-Gil, 1937",
    # Latin American
    "The Jungle (Wifredo Lam)": "Wifredo Lam, 1943",
    "Abaporu": "Tarsila do Amaral, 1928",
    "Man at the Crossroads": "Diego Rivera, 1934",
    "Dream of a Sunday Afternoon in Alameda Park": "Diego Rivera, 1947",
    "The Watermelons (Rufino Tamayo)": "Rufino Tamayo, 1968",
    "Animals (Rufino Tamayo)": "Rufino Tamayo, 1941",
    "Creation of the Birds (Remedios Varo)": "Remedios Varo, 1957",
    "Still Life Reviving (Remedios Varo)": "Remedios Varo, 1963",
    "The Earth Is a Man (Roberto Matta)": "Roberto Matta, 1942",
    "Invasion of the Night (Roberto Matta)": "Roberto Matta, 1941",
    # African
    "Congo (Irma Stern)": "Irma Stern, 1942",
    "Arab Priest (Irma Stern)": "Irma Stern, 1945",
    "Christine (Ben Enwonwu)": "Ben Enwonwu, 1971",
    "Tutu (Ben Enwonwu)": "Ben Enwonwu, 1974",
    "Negritude (Ben Enwonwu)": "Ben Enwonwu, 1950",
}

PAINTINGS = [
    # Renaissance
    "Mona Lisa", "The Last Supper (Leonardo)", "The Birth of Venus",
    "The Creation of Adam", "The School of Athens",
    "Primavera (Botticelli)", "Annunciation (Leonardo)",
    "Girl with a Pearl Earring", "The Arnolfini Portrait",
    "The Garden of Earthly Delights",
    "The Sistine Madonna", "Venus of Urbino",
    "Assumption of the Virgin (Titian)", "The Tempest (Giorgione)",
    "Self-Portrait (Albrecht Dürer, 1500)", "Melencolia I",
    "The Ambassadors (Holbein)",
    "Sofonisba Anguissola Self-Portrait",
    "The Chess Game (Sofonisba Anguissola)",
    # Baroque
    "The Night Watch", "Las Meninas", "Girl with a Pearl Earring",
    "The Art of Painting", "Judith Slaying Holofernes (Artemisia Gentileschi)",
    "The Calling of Saint Matthew (Caravaggio)", "The Milkmaid (Vermeer)",
    "Self-Portrait with Two Circles",
    "The Laughing Cavalier", "The Merry Drinker (Frans Hals)",
    "View of Haarlem (Jacob van Ruisdael)",
    "The Jewish Cemetery (Jacob van Ruisdael)",
    "The Courtyard of a House in Delft",
    "A Woman Drinking with Two Men",
    "Massacre of the Innocents (Rubens)",
    "The Elevation of the Cross (Rubens)",
    "Bacchus and Ariadne",
    "Self-Portrait as the Allegory of Painting",
    "Marie Antoinette with a Rose",
    "Self-Portrait in a Straw Hat (Vigée Le Brun)",
    # Neoclassicism
    "Napoleon Crossing the Alps", "The Death of Marat",
    "The Oath of the Horatii", "The Coronation of Napoleon",
    "The Grande Odalisque", "The Turkish Bath (Ingres)",
    # Romanticism
    "Liberty Leading the People", "The Great Wave off Kanagawa",
    "Wanderer above the Sea of Fog", "The Raft of the Medusa",
    "Rain, Steam and Speed", "The Hay Wain",
    "Saturn Devouring His Son", "The Third of May 1808",
    "The Ninth Wave", "The Fighting Temeraire",
    "The Slave Ship (Turner)", "The Abbey in the Oakwood",
    "The Nude Maja", "Washington Crossing the Delaware",
    # Pre-Raphaelite & Victorian
    "Ophelia (Millais)", "The Lady of Shalott (Waterhouse)",
    "Beata Beatrix", "Proserpine (Rossetti)",
    "The Order of Release, 1746",
    "Hylas and the Nymphs (Waterhouse)", "Flaming June",
    # British
    "A Rake's Progress", "Marriage A-la-Mode",
    "Mr and Mrs Andrews", "The Blue Boy",
    "Colonel Tarleton (Reynolds)",
    "Whistler's Mother", "Nocturne in Black and Gold",
    "Carnation, Lily, Lily, Rose", "Madame X (Sargent)",
    "El Jaleo (Sargent)",
    # Russian
    "Reply of the Zaporozhian Cossacks",
    "Barge Haulers on the Volga", "Ivan the Terrible and His Son",
    "The Rainbow (Aivazovsky)", "Storm on the Sea at Night",
    "The Rooks Have Returned", "Morning in a Pine Forest",
    # Impressionism
    "Impression, Sunrise", "Water Lilies (Monet series)",
    "A Sunday Afternoon on the Island of La Grande Jatte",
    "Bal du moulin de la Galette", "Luncheon of the Boating Party",
    "Dance at Le Moulin de la Galette", "The Dance Class (Degas)",
    "A Bar at the Folies-Bergère",
    "The Cradle (Berthe Morisot)", "Summer's Day (Berthe Morisot)",
    "The Boating Party (Mary Cassatt)", "The Child's Bath (Mary Cassatt)",
    "Rouen Cathedral (Monet series)",
    "Le Déjeuner sur l'herbe", "Olympia (Manet)",
    "The Floor Scrapers", "Paris Street; Rainy Day",
    # Post-Impressionism
    "The Starry Night", "Sunflowers (Van Gogh series)",
    "The Bedroom (Van Gogh)", "Café Terrace at Night",
    "A Sunday Afternoon on the Island of La Grande Jatte",
    "The Card Players", "Mont Sainte-Victoire (Cézanne)",
    "Where Do We Come From? What Are We? Where Are We Going?",
    "The Yellow Christ",
    "The Joy of Life (Matisse)", "The Dance (Matisse)",
    "The Blue Room (Suzanne Valadon)", "Adam and Eve (Suzanne Valadon)",
    "Self-Portrait on the Sixth Wedding Anniversary",
    "Mother and Child (Paula Modersohn-Becker)",
    # Expressionism & Symbolism
    "The Scream", "The Kiss (Klimt)", "The Persistence of Memory",
    "Guernica (Picasso)", "Les Demoiselles d'Avignon",
    "Portrait of Adele Bloch-Bauer I", "The Tree of Life (Klimt)",
    "The Blue Rider", "Composition VII (Kandinsky)",
    "Several Circles (Kandinsky)", "The Large Bathers (Cézanne)",
    "The Dream (Henri Rousseau)", "The Sleeping Gypsy",
    # Spanish modern
    "Walk on the Beach (Sorolla)", "Sad Inheritance (Sorolla)",
    "Boys on the Beach (Sorolla)",
    # Modern
    "American Gothic", "Nighthawks", "Christina's World",
    "Campbell's Soup Cans", "Marilyn Diptych",
    "No. 5, 1948", "Composition with Red Blue and Yellow",
    "Black Square (Malevich)", "Broadway Boogie Woogie",
    "The Son of Man (Magritte)", "The Treachery of Images",
    "The Two Fridas", "The Broken Column",
    "Self-Portrait with Thorn Necklace and Hummingbird",
    "Dog Barking at the Moon", "Nude Descending a Staircase, No. 2",
    "I and the Village", "The Lovers (Magritte)",
    "White on White (Malevich)", "Suprematist Composition (Malevich)",
    "No. 61 (Rust and Blue)", "Orange, Red, Yellow",
    "Woman I (de Kooning)", "Mountains and Sea",
    "Who's Afraid of Red, Yellow and Blue",
    "Flag (Jasper Johns)", "Whaam!",
    "Drowning Girl (Lichtenstein)",
    # American realism
    "Breezing Up (Winslow Homer)", "The Gulf Stream (Winslow Homer)",
    "Snap the Whip (Winslow Homer)",
    "Freedom from Want (Norman Rockwell)",
    "Triple Self-Portrait (Norman Rockwell)",
    "Jimson Weed/White Flower No. 1", "Black Iris (O'Keeffe)",
    # Contemporary
    "Infinity Mirror Rooms", "Girl with a Balloon",
    "Shot Sage Blue Marilyn",
    "A Bigger Splash", "Portrait of an Artist (Pool with Two Figures)",
    "Untitled (Skull) (Basquiat)", "Untitled (1982) (Basquiat)",
    "Three Studies of Lucian Freud",
    "Study after Velázquez's Portrait of Pope Innocent X",
    "Benefits Supervisor Sleeping",
    # Asian art
    "Along the River During the Qingming Festival",
    "The Great Wave off Kanagawa", "Red Fuji",
    "Pine Trees (Hasegawa Tōhaku)",
    "Dwelling in the Fuchun Mountains",
    "Travelers Among Mountains and Streams",
    "Early Spring (Guo Xi)",
    "Shrimps (Qi Baishi)", "Galloping Horse (Xu Beihong)",
    "Sudden Shower over Shin-Ōhashi Bridge",
    "Night Snow at Kambara",
    "Wind God and Thunder God (Tawaraya Sōtatsu)",
    "Irises (Ogata Kōrin)",
    # Indian art
    "Bharat Mata (Abanindranath Tagore)",
    "Three Girls (Amrita Sher-Gil)", "Brahmacharis (Amrita Sher-Gil)",
    # Latin American
    "The Jungle (Wifredo Lam)", "Abaporu",
    "Man at the Crossroads", "Dream of a Sunday Afternoon in Alameda Park",
    "The Watermelons (Rufino Tamayo)", "Animals (Rufino Tamayo)",
    "Creation of the Birds (Remedios Varo)",
    "Still Life Reviving (Remedios Varo)",
    "The Earth Is a Man (Roberto Matta)",
    "Invasion of the Night (Roberto Matta)",
    # African
    "Congo (Irma Stern)", "Arab Priest (Irma Stern)",
    "Christine (Ben Enwonwu)", "Tutu (Ben Enwonwu)",
    "Negritude (Ben Enwonwu)",
]

PAINTERS = [
    # Renaissance
    "Albrecht Dürer", "Caravaggio", "El Greco",
    "Hieronymus Bosch", "Jan van Eyck", "Leonardo da Vinci",
    "Michelangelo", "Raphael", "Sandro Botticelli",
    "Titian", "Giorgione", "Hans Holbein the Younger",
    "Sofonisba Anguissola",
    # Baroque & Dutch Golden Age
    "Artemisia Gentileschi", "Diego Velázquez",
    "Johannes Vermeer", "Peter Paul Rubens", "Rembrandt",
    "Frans Hals", "Jacob van Ruisdael", "Pieter de Hooch",
    "Élisabeth Vigée Le Brun",
    # Neoclassicism
    "Jacques-Louis David", "Jean-Auguste-Dominique Ingres",
    # Romanticism & Realism
    "Caspar David Friedrich", "Eugène Delacroix",
    "Francisco Goya", "Gustave Courbet", "J. M. W. Turner",
    "John Constable", "Théodore Géricault", "Emanuel Leutze",
    # Pre-Raphaelite & Victorian
    "Dante Gabriel Rossetti", "John Everett Millais",
    "John William Waterhouse", "Frederic Leighton",
    # British
    "William Hogarth", "Thomas Gainsborough", "Joshua Reynolds",
    "John Singer Sargent",
    # Russian
    "Ivan Aivazovsky", "Ilya Repin", "Alexei Savrasov",
    "Ivan Shishkin",
    # American
    "Winslow Homer", "James Abbott McNeill Whistler",
    # Impressionism
    "Alfred Sisley", "Berthe Morisot", "Camille Pissarro",
    "Claude Monet", "Edgar Degas", "Mary Cassatt",
    "Pierre-Auguste Renoir", "Gustave Caillebotte",
    # Post-Impressionism
    "Édouard Manet", "Georges Seurat",
    "Henri de Toulouse-Lautrec", "Paul Cézanne",
    "Paul Gauguin", "Vincent van Gogh",
    "Henri Matisse", "Henri Rousseau",
    "Suzanne Valadon", "Paula Modersohn-Becker",
    # Expressionism & early modern
    "Amedeo Modigliani", "Edvard Munch", "Egon Schiele",
    "Gustav Klimt", "Marc Chagall", "Wassily Kandinsky",
    # Spanish modern
    "Joaquín Sorolla",
    # Cubism & Surrealism
    "Frida Kahlo", "Joan Miró", "Marcel Duchamp",
    "Max Ernst", "Pablo Picasso", "René Magritte",
    "Salvador Dalí", "Remedios Varo", "Roberto Matta",
    # Abstract & modern
    "Edward Hopper", "Georgia O'Keeffe", "Grant Wood",
    "Jackson Pollock", "Kazimir Malevich", "Mark Rothko",
    "Norman Rockwell", "Paul Klee", "Piet Mondrian",
    "Tamara de Lempicka", "Willem de Kooning",
    "Helen Frankenthaler", "Barnett Newman",
    "Jasper Johns",
    # Pop art & contemporary
    "Andy Warhol", "Banksy", "Damien Hirst",
    "David Hockney", "Francis Bacon (artist)",
    "Gerhard Richter", "Jean-Michel Basquiat",
    "Jeff Koons", "Keith Haring", "Lucian Freud",
    "Roy Lichtenstein", "Takashi Murakami",
    "Yayoi Kusama",
    # Asian
    "Amrita Sher-Gil", "Hokusai", "Hiroshige",
    "Qi Baishi", "Xu Beihong", "Zhang Daqian",
    "Hasegawa Tōhaku", "Huang Gongwang", "Fan Kuan",
    "Guo Xi", "Tawaraya Sōtatsu", "Ogata Kōrin",
    # African & Latin American
    "Diego Rivera", "El Anatsui", "Fernando Botero",
    "Tarsila do Amaral", "Wifredo Lam", "William Kentridge",
    "Rufino Tamayo", "Irma Stern", "Ben Enwonwu",
]
