ALL = [
    # Scientists
    "Albert Einstein", "Marie Curie", "Nikola Tesla", "Charles Darwin",
    "Isaac Newton", "Galileo Galilei", "Copernicus", "Johannes Kepler",
    "Archimedes", "Ada Lovelace", "Alan Turing", "Rosalind Franklin",
    "Stephen Hawking", "Richard Feynman", "Niels Bohr", "Max Planck",
    "Michael Faraday", "Louis Pasteur", "Alexander Fleming",
    "Dmitri Mendeleev", "Carl Linnaeus", "Gregor Mendel",
    "Rachel Carson", "Barbara McClintock", "Dorothy Hodgkin",
    "Lise Meitner", "Emmy Noether", "Hypatia",
    "Carl Sagan", "Jane Goodall", "Dian Fossey",
    "Alfred Nobel", "Enrico Fermi", "Ernest Rutherford",
    "James Clerk Maxwell", "Heinrich Hertz", "Erwin Schrödinger",
    "Werner Heisenberg", "Paul Dirac", "Robert Oppenheimer",
    # Explorers & adventurers
    "Marco Polo", "Amelia Earhart", "Christopher Columbus",
    "Ferdinand Magellan", "Vasco da Gama", "James Cook",
    "Roald Amundsen", "Ernest Shackleton", "Edmund Hillary",
    "Tenzing Norgay", "Neil Armstrong", "Yuri Gagarin",
    "Valentina Tereshkova", "Ibn Battuta", "Zheng He",
    # Artists & musicians
    "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh",
    "Frida Kahlo", "Salvador Dalí", "Claude Monet",
    "Rembrandt", "Michelangelo", "Auguste Rodin", "Andy Warhol",
    "Gustav Klimt", "Edvard Munch", "Henri Matisse",
    "Wassily Kandinsky", "Jackson Pollock", "Georgia O'Keeffe",
    "Yayoi Kusama", "Banksy", "Ai Weiwei",
    "Wolfgang Amadeus Mozart", "Beethoven", "Johann Sebastian Bach",
    "Frédéric Chopin", "Franz Liszt", "Pyotr Ilyich Tchaikovsky",
    "Antonio Vivaldi", "Giuseppe Verdi", "Richard Wagner",
    "Claude Debussy", "Igor Stravinsky",
    # Writers & philosophers
    "William Shakespeare", "Jane Austen", "Leo Tolstoy",
    "Fyodor Dostoevsky", "Mark Twain", "Charles Dickens",
    "Virginia Woolf", "Franz Kafka", "Jorge Luis Borges",
    "Gabriel García Márquez", "Toni Morrison", "Maya Angelou",
    "Homer", "Dante Alighieri", "Miguel de Cervantes",
    "Aristotle", "Socrates", "Plato", "Confucius",
    "Sigmund Freud", "Carl Jung", "Friedrich Nietzsche",
    "Immanuel Kant", "René Descartes", "Jean-Paul Sartre",
    "Simone de Beauvoir",
    # Leaders & historical figures
    "Nelson Mandela", "Mahatma Gandhi", "Martin Luther King Jr.",
    "Abraham Lincoln", "Napoleon", "Julius Caesar",
    "Alexander the Great", "Genghis Khan", "Cleopatra",
    "Queen Victoria", "Elizabeth I", "Catherine the Great",
    "Joan of Arc", "Tutankhamun", "Nefertiti",
    "Rosa Parks", "Harriet Tubman", "Frederick Douglass",
    "Emmeline Pankhurst", "Florence Nightingale",
    "Simón Bolívar", "Che Guevara", "Winston Churchill",
    "Charles de Gaulle", "Jawaharlal Nehru", "Marie Antoinette",
    "Coco Chanel", "Thomas Edison", "Alexander Graham Bell",
    "Wright brothers", "James Watt", "Henry Ford",
    "Nikola Tesla", "Gutenberg",
]
