LOCATIONS = {
    # Europe
    "Arno": "Italy",
    "Clyde (river)": "Scotland",
    "Danube": "Germany → Austria → Slovakia → Hungary → Serbia → Romania",
    "Danube Delta": "Romania",
    "Dnieper": "Russia → Belarus → Ukraine",
    "Don (river)": "Russia",
    "Douro": "Spain → Portugal",
    "Ebro": "Spain",
    "Elbe": "Czech Republic → Germany",
    "Guadalquivir": "Spain",
    "Loire": "France",
    "Oder (river)": "Czech Republic → Poland → Germany",
    "Po (river)": "Italy",
    "Rhine": "Switzerland → Germany → Netherlands",
    "Rhône": "Switzerland → France",
    "Seine": "France",
    "Severn": "Wales → England",
    "Shannon (river)": "Ireland",
    "Tagus": "Spain → Portugal",
    "Thames": "England",
    "Tiber": "Italy",
    "Tisza": "Ukraine → Hungary → Serbia",
    "Ural (river)": "Russia → Kazakhstan",
    "Vistula": "Poland",
    "Volga": "Russia",
    # Asia
    "Amur River": "Russia → China",
    "Brahmaputra River": "China → India → Bangladesh",
    "Chao Phraya River": "Thailand",
    "Euphrates": "Turkey → Syria → Iraq",
    "Ganges": "India → Bangladesh",
    "Godavari": "India",
    "Indus River": "China → India → Pakistan",
    "Irrawaddy River": "Myanmar",
    "Jordan River": "Lebanon → Syria → Jordan → Israel",
    "Krishna River": "India",
    "Lena (river)": "Russia",
    "Mekong": "China → Myanmar → Laos → Thailand → Cambodia → Vietnam",
    "Ob River": "Russia",
    "Pearl River (China)": "China",
    "Red River (Asia)": "China → Vietnam",
    "Salween River": "China → Myanmar → Thailand",
    "Tigris": "Turkey → Iraq",
    "Yangtze": "China",
    "Yellow River": "China",
    "Yenisei": "Mongolia → Russia",
    # Africa
    "Blue Nile": "Ethiopia → Sudan",
    "Congo River": "DR Congo → Congo",
    "Limpopo River": "South Africa → Botswana → Mozambique",
    "Niger River": "Guinea → Mali → Niger → Nigeria",
    "Nile": "Uganda → Sudan → Egypt",
    "Okavango River": "Angola → Namibia → Botswana",
    "Orange River": "Lesotho → South Africa",
    "Senegal River": "Guinea → Mali → Senegal",
    "Ubangi River": "DR Congo → Central African Republic",
    "Volta River": "Burkina Faso → Ghana",
    "White Nile": "Uganda → South Sudan → Sudan",
    "Zambezi": "Zambia → Zimbabwe → Mozambique",
    # North America
    "Arkansas River": "USA",
    "Colorado River": "USA → Mexico",
    "Columbia River": "Canada → USA",
    "Connecticut River": "USA",
    "Delaware River": "USA",
    "Fraser River": "Canada",
    "Hudson River": "USA",
    "Mackenzie River": "Canada",
    "Mississippi River": "USA",
    "Missouri River": "USA",
    "Ohio River": "USA",
    "Potomac River": "USA",
    "Red River of the South": "USA",
    "Rio Grande": "USA → Mexico",
    "Saskatchewan River": "Canada",
    "Snake River": "USA",
    "St. Lawrence River": "Canada → USA",
    "Susquehanna River": "USA",
    "Tennessee River": "USA",
    "Yukon River": "Canada → USA",
    # South America
    "Amazon River": "Peru → Brazil",
    "Madeira River": "Bolivia → Brazil",
    "Magdalena River": "Colombia",
    "Negro River (Amazon)": "Colombia → Venezuela → Brazil",
    "Orinoco": "Venezuela → Colombia",
    "Paraná River": "Brazil → Paraguay → Argentina",
    "Putumayo River": "Colombia → Ecuador → Peru → Brazil",
    "São Francisco River": "Brazil",
    "Tocantins River": "Brazil",
    "Uruguay River": "Brazil → Argentina → Uruguay",
    "Xingu River": "Brazil",
    # Oceania
    "Darling River": "Australia",
    "Murray River": "Australia",
    "Waikato River": "New Zealand",
}

CONTINENTS = {
    "africa": [
        "Blue Nile",
        "Congo River",
        "Limpopo River",
        "Niger River",
        "Nile",
        "Okavango River",
        "Orange River",
        "Senegal River",
        "Ubangi River",
        "Volta River",
        "White Nile",
        "Zambezi",
    ],
    "america": [
        "Amazon River",
        "Arkansas River",
        "Colorado River",
        "Columbia River",
        "Connecticut River",
        "Delaware River",
        "Fraser River",
        "Hudson River",
        "Mackenzie River",
        "Madeira River",
        "Magdalena River",
        "Mississippi River",
        "Missouri River",
        "Negro River (Amazon)",
        "Ohio River",
        "Orinoco",
        "Paraná River",
        "Potomac River",
        "Putumayo River",
        "Red River of the South",
        "Rio Grande",
        "Saskatchewan River",
        "Snake River",
        "St. Lawrence River",
        "Susquehanna River",
        "São Francisco River",
        "Tennessee River",
        "Tocantins River",
        "Uruguay River",
        "Xingu River",
        "Yukon River",
    ],
    "asia": [
        "Amur River",
        "Brahmaputra River",
        "Chao Phraya River",
        "Euphrates",
        "Ganges",
        "Godavari",
        "Indus River",
        "Irrawaddy River",
        "Jordan River",
        "Krishna River",
        "Lena (river)",
        "Mekong",
        "Ob River",
        "Pearl River (China)",
        "Red River (Asia)",
        "Salween River",
        "Tigris",
        "Yangtze",
        "Yellow River",
        "Yenisei",
    ],
    "europe": [
        "Arno",
        "Clyde (river)",
        "Danube",
        "Danube Delta",
        "Dnieper",
        "Don (river)",
        "Douro",
        "Ebro",
        "Elbe",
        "Guadalquivir",
        "Loire",
        "Oder (river)",
        "Po (river)",
        "Rhine",
        "Rhône",
        "Seine",
        "Severn",
        "Shannon (river)",
        "Tagus",
        "Thames",
        "Tiber",
        "Tisza",
        "Ural (river)",
        "Vistula",
        "Volga",
    ],
    "oceania": [
        "Darling River",
        "Murray River",
        "Waikato River",
    ],
}

ALL = [
    # Europe
    "Arno",
    "Clyde (river)",
    "Danube",
    "Danube Delta",
    "Dnieper",
    "Don (river)",
    "Douro",
    "Ebro",
    "Elbe",
    "Guadalquivir",
    "Loire",
    "Oder (river)",
    "Po (river)",
    "Rhine",
    "Rhône",
    "Seine",
    "Severn",
    "Shannon (river)",
    "Tagus",
    "Thames",
    "Tiber",
    "Tisza",
    "Ural (river)",
    "Vistula",
    "Volga",
    # Asia
    "Amur River",
    "Brahmaputra River",
    "Chao Phraya River",
    "Euphrates",
    "Ganges",
    "Godavari",
    "Indus River",
    "Irrawaddy River",
    "Jordan River",
    "Krishna River",
    "Lena (river)",
    "Mekong",
    "Ob River",
    "Pearl River (China)",
    "Red River (Asia)",
    "Salween River",
    "Tigris",
    "Yangtze",
    "Yellow River",
    "Yenisei",
    # Africa
    "Blue Nile",
    "Congo River",
    "Limpopo River",
    "Niger River",
    "Nile",
    "Okavango River",
    "Orange River",
    "Senegal River",
    "Ubangi River",
    "Volta River",
    "White Nile",
    "Zambezi",
    # North America
    "Arkansas River",
    "Colorado River",
    "Columbia River",
    "Connecticut River",
    "Delaware River",
    "Fraser River",
    "Hudson River",
    "Mackenzie River",
    "Mississippi River",
    "Missouri River",
    "Ohio River",
    "Potomac River",
    "Red River of the South",
    "Rio Grande",
    "Saskatchewan River",
    "Snake River",
    "St. Lawrence River",
    "Susquehanna River",
    "Tennessee River",
    "Yukon River",
    # South America
    "Amazon River",
    "Madeira River",
    "Magdalena River",
    "Negro River (Amazon)",
    "Orinoco",
    "Paraná River",
    "Putumayo River",
    "São Francisco River",
    "Tocantins River",
    "Uruguay River",
    "Xingu River",
    # Oceania
    "Darling River",
    "Murray River",
    "Waikato River",
]
