SCIENTIFIC_NAMES = {
    "Aardvark": "Orycteropus afer",
    "Aardwolf": "Proteles cristata",
    "Acacia": "Acacia",
    "Adiantum": "Adiantum",
    "Adélie penguin": "Pygoscelis adeliae",
    "Aeonium": "Aeonium",
    "African bullfrog": "Pyxicephalus adspersus",
    "African elephant": "Loxodonta",
    "African wild dog": "Lycaon pictus",
    "Agapanthus": "Agapanthus",
    "Agave": "Agave",
    "Agouti": "Dasyprocta",
    "Albatross": "Diomedeidae",
    "Aldabra giant tortoise": "Aldabrachelys gigantea",
    "Alder": "Alnus",
    "Aldrovanda": "Aldrovanda",
    "Alligator": "Alligator",
    "Alligator snapping turtle": "Macrochelys temminckii",
    "Allium": "Allium",
    "Allosaurus": "Allosaurus",
    "Alocasia": "Alocasia",
    "Aloe vera": "Aloe vera",
    "Alpine newt": "Ichthyosaura alpestris",
    "Amargasaurus": "Amargasaurus cazaui",
    "Amaryllis": "Amaryllis",
    "Amazon parrot": "Amazona",
    "American alligator": "Alligator mississippiensis",
    "American black bear": "Ursus americanus",
    "American crocodile": "Crocodylus acutus",
    "Anaconda": "Eunectes",
    "Andean condor": "Vultur gryphus",
    "Anemone": "Anemone",
    "Anglerfish": "Lophiiformes",
    "Anhinga": "Anhinga anhinga",
    "Ankylosaurus": "Ankylosaurus",
    "Anteater": "Vermilingua",
    "Anthurium": "Anthurium",
    "Anubias": "Anubias",
    "Apatosaurus": "Apatosaurus",
    "Arapaima": "Arapaima",
    "Araucaria": "Araucaria",
    "Archaeopteryx": "Archaeopteryx",
    "Archerfish": "Toxotidae",
    "Arctic fox": "Vulpes lagopus",
    "Argentinosaurus": "Argentinosaurus",
    "Arizona bark scorpion": "Centruroides sculpturatus",
    "Armadillo girdled lizard": "Ouroborus cataphractus",
    "Asian black bear": "Ursus thibetanus",
    "Asian elephant": "Elephas maximus",
    "Asian giant hornet": "Vespa mandarinia",
    "Asparagus": "Asparagus officinalis",
    "Asplenium": "Asplenium",
    "Astrophytum": "Astrophytum",
    "Atemoya": "Annona × atemoya",
    "Atlas beetle": "Chalcosoma atlas",
    "Avocado": "Persea americana",
    "Avocet": "Recurvirostra",
    "Axolotl": "Ambystoma mexicanum",
    "Aye-aye": "Daubentonia madagascariensis",
    "Baboon": "Papio",
    "Bald eagle": "Haliaeetus leucocephalus",
    "Ball python": "Python regius",
    "Banded demoiselle": "Calopteryx splendens",
    "Barnacle": "Cirripedia",
    "Barracuda": "Sphyraena",
    "Barred owl": "Strix varia",
    "Baryonyx": "Baryonyx",
    "Basil": "Ocimum basilicum",
    "Basking shark": "Cetorhinus maximus",
    "Bat-eared fox": "Otocyon megalotis",
    "Bearded vulture": "Gypaetus barbatus",
    "Beaver": "Castor",
    "Bee-eater": "Meropidae",
    "Beech": "Fagus",
    "Beetroot": "Beta vulgaris subsp. vulgaris Conditiva Group",
    "Begonia": "Begonia",
    "Beluga whale": "Delphinapterus leucas",
    "Bergamot orange": "Citrus ×bergamia",
    "Betta": "Betta",
    "Binturong": "Arctictis binturong",
    "Birch": "Betula",
    "Bird-of-paradise": "Paradisaeidae",
    "Bison": "Bison",
    "Black caiman": "Melanosuchus niger",
    "Black kite": "Milvus migrans",
    "Black mamba": "Dendroaspis polylepis",
    "Black rhinoceros": "Diceros bicornis",
    "Black-eyed pea": "Vigna unguiculata subsp. unguiculata",
    "Black-footed cat": "Felis nigripes",
    "Blackcurrant": "Ribes nigrum",
    "Blacktip reef shark": "Carcharhinus melanopterus",
    "Blanket octopus": "Tremoctopus",
    "Blister beetle": "Meloidae",
    "Blue dasher": "Pachydiplax longipennis",
    "Blue jay": "Cyanocitta cristata",
    "Blue poison dart frog": "Dendrobates azureus",
    "Blue shark": "Prionace glauca",
    "Blue whale": "Balaenoptera musculus",
    "Blue-and-yellow macaw": "Ara ararauna",
    "Blue-ringed octopus": "Hapalochlaena",
    "Blue-tongued skink": "Tiliqua",
    "Blueberry": "Vaccinium sect. Cyanococcus",
    "Boa constrictor": "Boa constrictor",
    "Bobcat": "Lynx rufus",
    "Bok choy": "Brassica rapa subsp. chinensis",
    "Bonefish": "Albula vulpes",
    "Bongo (antelope)": "Tragelaphus eurycerus",
    "Bonobo": "Pan paniscus",
    "Booby": "Sula",
    "Boomslang": "Dispholidus typus",
    "Bougainvillea": "Bougainvillea",
    "Bowhead whale": "Balaena mysticetus",
    "Box jellyfish": "Cubozoa",
    "Brachiosaurus": "Brachiosaurus",
    "Bracken": "Pteridium",
    "Brahminy kite": "Haliastur indus",
    "Breadfruit": "Artocarpus altilis",
    "Bristlecone pine": "Pinus subsect. Balfourianae",
    "Brittle star": "Ophiuroidea",
    "Brocchinia reducta": "Brocchinia reducta",
    "Broccoli": "Brassica oleracea var. italica",
    "Brontosaurus": "Brontosaurus",
    "Brown bear": "Ursus arctos",
    "Brown recluse spider": "Loxosceles reclusa",
    "Brussels sprout": "Brassica oleracea var. gemmifera",
    "Buddha's hand": "Citrus medica var. sarcodactylis",
    "Budgerigar": "Melopsittacus undulatus",
    "Bull shark": "Carcharhinus leucas",
    "Bumblebee": "Bombus",
    "Burmese python": "Python bivittatus",
    "Burrowing owl": "Athene cunicularia",
    "Bush dog": "Speothos venaticus",
    "Butterflyfish": "Chaetodontidae",
    "Cabbage": "Brassica oleracea var. capitata",
    "Cacomistle": "Bassariscus sumichrasti",
    "Cactus": "Cactaceae",
    "Caecilian": "Gymnophiona",
    "Caiman": "Caima",
    "Caladium": "Caladium",
    "Calamansi": "×Citrofortunella microcarpa",
    "Calathea": "Calathea",
    "Calendula": "Calendula",
    "California condor": "Gymnogyps californianus",
    "Camarasaurus": "Camarasaurus",
    "Camellia": "Camellia",
    "Cane toad": "Rhinella marina",
    "Cantaloupe": "Cucumis melo var. cantalupensis",
    "Caper": "Capparis spinosa",
    "Capuchin monkey": "Cebinae",
    "Capybara": "Hydrochoerus hydrochaeris",
    "Caracal": "Caracal caracal",
    "Cardoon": "Cynara cardunculus",
    "Carnotaurus": "Carnotaurus",
    "Carolina Reaper": "Capsicum chinense 'Carolina Reaper'",
    "Carpenter ant": "Camponotus",
    "Carpenter bee": "Xylocopa",
    "Cassava": "Manihot esculenta",
    "Cassowary": "Casuarius",
    "Cauliflower": "Brassica oleracea var. botrytis",
    "Cayenne pepper": "Capsicum annuum var. acuminatum",
    "Celeriac": "Apium graveolens var. rapaceum",
    "Celosia": "Celosia",
    "Centipede": "Chilopoda",
    "Centrosaurus": "Centrosaurus",
    "Cephalotus": "Cephalotus",
    "Ceratosaurus": "Ceratosaurus",
    "Ceropegia": "Ceropegia",
    "Chambered nautilus": "Nautilus pompilius",
    "Chameleon": "Chamaeleonidae",
    "Chamois": "Rupicapra rupicapra",
    "Chasmosaurus": "Chasmosaurus",
    "Chayote": "Sicyos edulis",
    "Cheetah": "Acinonyx jubatus",
    "Cherimoya": "Annona cherimola",
    "Chervil": "Anthriscus cerefolium",
    "Chestnut": "Castanea",
    "Chickpea": "Cicer arietinum",
    "Chicory": "Cichorium intybus",
    "Chimpanzee": "Pan troglodytes",
    "Chinchilla": "Chinchilla",
    "Chinese alligator": "Alligator sinensis",
    "Chinese giant salamander": "Andrias davidianus",
    "Chinstrap penguin": "Pygoscelis antarcticus",
    "Chipmunk": "Tamiini",
    "Chrysanthemum": "Chrysanthemum",
    "Chuckwalla": "Sauromalus",
    "Cicada": "Cicadoidea",
    "Cinnabar moth": "Tyria jacobaeae",
    "Citrus": "Citrus",
    "Clematis": "Clematis",
    "Clementine": "Citrus ×clementina",
    "Click beetle": "Elateridae",
    "Clouded leopard": "Neofelis nebulosa",
    "Clover": "Trifolium",
    "Clownfish": "Amphiprioninae",
    "Cock-of-the-rock": "Rupicola",
    "Cockatiel": "Nymphicus hollandicus",
    "Cockatoo": "Cacatuidae",
    "Coconut": "Cocos nucifera",
    "Coconut crab": "Birgus latro",
    "Coelacanth": "Coelacanthiformes",
    "Coelophysis": "Coelophysis",
    "Coleus": "Coleus",
    "Colocasia": "Colocasia",
    "Colossal squid": "Mesonychoteuthis hamiltoni",
    "Comet moth": "Argema mittrei",
    "Common darter": "Sympetrum striolatum",
    "Common toad": "Bufo bufo",
    "Compsognathus": "Compsognathus",
    "Cone snail": "Conidae",
    "Cookiecutter shark": "Isistius brasiliensis",
    "Cooper's hawk": "Accipiter cooperii",
    "Cormorant": "Phalacrocoracidae",
    "Corn snake": "Pantherophis guttatus",
    "Corythosaurus": "Corythosaurus",
    "Cotinga": "Cotingidae",
    "Cougar": "Puma concolor",
    "Coyote": "Canis latrans",
    "Cranberry": "Vaccinium subg. Oxycoccus",
    "Crane (bird)": "Gruidae",
    "Crane fly": "Tipuloidea",
    "Crocodile": "Crocodylidae",
    "Crocosmia": "Crocosmia",
    "Crocus": "Crocus",
    "Crossbill": "Loxia",
    "Croton (plant)": "Croton",
    "Crown-of-thorns starfish": "Acanthaster planci",
    "Crowned eagle": "Stephanoaetus coronatus",
    "Cuckoo": "Cuculidae",
    "Cucumber": "Cucumis sativus",
    "Curlew": "Numenius",
    "Cuttlefish": "Sepiidae",
    "Cycad": "Cycadales",
    "Cyclamen": "Cyclamen",
    "Dahlia": "Dahlia",
    "Daikon": "Raphanus sativus subsp. acanthiformis",
    "Damselfly": "Zygoptera",
    "Darlingtonia californica": "Darlingtonia californica",
    "Darwin's frog": "Rhinoderma darwinii",
    "Date palm": "Phoenix dactylifera",
    "Death's-head hawkmoth": "Acherontia",
    "Deathstalker": "Leiurus quinquestriatus",
    "Deathwatch beetle": "Xestobium rufovillosum",
    "Deinonychus": "Deinonychus",
    "Delicata squash": "Cucurbita maxima ‘Delicata’",
    "Delphinium": "Delphinium",
    "Dhole": "Cuon alpinus",
    "Diamondback terrapin": "Malaclemys terrapin",
    "Dianthus": "Dianthus",
    "Dieffenbachia": "Dieffenbachia",
    "Dik-dik": "Madoqua",
    "Dill": "Anethum graveolens",
    "Dilophosaurus": "Dilophosaurus",
    "Dimetrodon": "Dimetrodon",
    "Dimorphodon": "Dimorphodon",
    "Dingo": "Canis familiaris dingo",
    "Diplodocus": "Diplodocus",
    "Dipper": "Cinclus",
    "Discus (fish)": "Symphysodon",
    "Dormouse": "Gliridae",
    "Douglas fir": "Pseudotsuga menziesii",
    "Dracorex": "Dracorex",
    "Dragonfly": "Anisoptera",
    "Drosophyllum": "Drosophyllum",
    "Dugong": "Dugong dugon",
    "Dwarf crocodile": "Osteolaemus tetraspis",
    "Eagle ray": "Myliobatidae",
    "Earwig": "Dermaptera",
    "Eastern brown snake": "Pseudonaja textilis",
    "Eastern newt": "Notophthalmus viridescens",
    "Ebony jewelwing": "Calopteryx maculata",
    "Echeveria": "Echeveria",
    "Echidna": "Tachyglossidae",
    "Echinacea": "Echinacea",
    "Echinopsis": "Echinopsis",
    "Edelweiss": "Leontopodium nivale",
    "Edmontosaurus": "Edmontosaurus",
    "Eggplant": "Solanum melongena",
    "Einiosaurus": "Einiosaurus",
    "Elasmosaurus": "Elasmosaurus",
    "Electric eel": "Electrophorus",
    "Electric ray": "Torpediniformes",
    "Elephant seal": "Mirounga",
    "Elf owl": "Micrathene whitneyi",
    "Elk": "Cervus canadensis",
    "Elm": "Ulmus",
    "Elodea": "Elodea",
    "Emerald tree boa": "Corallus caninus",
    "Emperor dragonfly": "Anax imperator",
    "Emperor penguin": "Aptenodytes forsteri",
    "Emperor scorpion": "Pandinus imperator",
    "Emu": "Dromaius novaehollandiae",
    "Eucalyptus": "Eucalyptus",
    "Euoplocephalus": "Euoplocephalus",
    "Euphorbia": "Euphorbia",
    "Eurasian lynx": "Lynx lynx",
    "Fallow deer": "Dama",
    "False gharial": "Tomistoma schlegelii",
    "Feijoa": "Feijoa",
    "Fennec fox": "Vulpes zerda",
    "Fennel": "Foeniculum vulgare",
    "Ferocactus": "Ferocactus",
    "Ferret": "Mustela furo",
    "Ficus": "Ficus",
    "Fiddler crab": "Uca",
    "Fig": "Ficus carica",
    "Fin whale": "Balaenoptera physalus",
    "Fir": "Abies",
    "Fire ant": "Solenopsis",
    "Fire salamander": "Salamandra salamandra",
    "Fire-bellied toad": "Bombina",
    "Firefly": "Lampyridae",
    "Firefly squid": "Watasenia scintillans",
    "Fishing cat": "Prionailurus viverrinus",
    "Flamingo": "Phoenicopteridae",
    "Flowerpecker": "Dicaeidae",
    "Flying fish": "Exocoetidae",
    "Flying squirrel": "Pteromyini",
    "Forsythia": "Forsythia",
    "Freesia": "Freesia",
    "Frigatebird": "Fregata",
    "Frogfish": "Antennariidae",
    "Fuchsia": "Fuchsia",
    "Fur seal": "Arctocephalinae",
    "Gaboon viper": "Bitis gabonica",
    "Galago": "Galagidae",
    "Galah": "Eolophus roseicapilla",
    "Gallimimus": "Gallimimus",
    "Gannet": "Morus",
    "Garden tiger moth": "Arctia caja",
    "Gardenia": "Gardenia",
    "Garlic": "Allium sativum",
    "Garter snake": "Thamnophis",
    "Gasteria": "Gasteria",
    "Gelada": "Theropithecus gelada",
    "Genlisea": "Genlisea",
    "Gentoo penguin": "Pygoscelis papua",
    "Geranium": "Geranium",
    "Gerenuk": "Litocranius walleri",
    "Gharial": "Gavialis gangeticus",
    "Ghost pepper": "Capsicum chinense ‘Bhut Jolokia’",
    "Giant Pacific octopus": "Enteroctopus dofleini",
    "Giant clam": "Tridacna gigas",
    "Giant cuttlefish": "Sepia apama",
    "Giant panda": "Ailuropoda melanoleuca",
    "Giant salamander": "Cryptobranchidae",
    "Giant squid": "Architeuthis dux",
    "Gibbon": "Hylobatidae",
    "Giganotosaurus": "Giganotosaurus",
    "Gila monster": "Heloderma suspectum",
    "Ginger": "Zingiber officinale",
    "Ginkgo": "Ginkgo",
    "Giraffe": "Giraffa",
    "Giraffe weevil": "Trachelophorus giraffa",
    "Gladiolus": "Gladiolus",
    "Glass frog": "Centrolenidae",
    "Goblin shark": "Mitsukurina owstoni",
    "Golden eagle": "Aquila chrysaetos",
    "Golden lion tamarin": "Leontopithecus rosalia",
    "Golden pheasant": "Chrysolophus pictus",
    "Golden poison frog": "Phyllobates terribilis",
    "Golden toad": "Incilius periglenes",
    "Goliath birdeater": "Theraphosa blondi",
    "Goliath frog": "Conraua goliath",
    "Gorilla": "Gorilla",
    "Grapefruit": "Citrus paradisi",
    "Gray fox": "Urocyon cinereoargenteus",
    "Gray whale": "Eschrichtius robustus",
    "Great blue heron": "Ardea herodias",
    "Great grey owl": "Strix nebulosa",
    "Great horned owl": "Bubo virginianus",
    "Great white shark": "Carcharodon carcharias",
    "Green anaconda": "Eunectes murinus",
    "Green iguana": "Iguana iguana",
    "Green sea turtle": "Chelonia mydas",
    "Green tree python": "Morelia viridis",
    "Greenland shark": "Somniosus microcephalus",
    "Ground beetle": "Carabidae",
    "Groundhog": "Marmota monax",
    "Grouper": "Epinephelinae",
    "Grouse": "Tetraoninae",
    "Guinea fowl": "Numididae",
    "Guitarfish": "Rhinobatidae",
    "Gull": "Larinae",
    "Guppy": "Poecilia reticulata",
    "Gymnocalycium": "Gymnocalycium",
    "Gyrfalcon": "Falco rusticolus",
    "Habanero": "Capsicum chinense ‘Habanero’",
    "Hadrosaurus": "Hadrosaurus",
    "Hammerhead shark": "Sphyrnidae",
    "Harbor seal": "Phoca vitulina",
    "Harpy eagle": "Harpia harpyja",
    "Harris's hawk": "Parabuteo unicinctus",
    "Hartebeest": "Alcelaphus buselaphus",
    "Hawksbill sea turtle": "Eretmochelys imbricata",
    "Haworthia": "Haworthia",
    "Hedgehog": "Erinaceinae",
    "Helenium": "Helenium",
    "Heliamphora": "Heliamphora",
    "Heliconia": "Heliconia",
    "Hellbender": "Cryptobranchus alleganiensis",
    "Hercules beetle": "Dynastes hercules",
    "Hermit crab": "Paguroidea",
    "Heron": "Ardeidae",
    "Herrerasaurus": "Herrerasaurus",
    "Hibiscus": "Hibiscus",
    "Hickory": "Carya",
    "Hippopotamus": "Hippopotamus amphibius",
    "Hoatzin": "Opisthocomus hoazin",
    "Holly": "Ilex",
    "Hoopoe": "Upupidae",
    "Hornbeam": "Carpinus",
    "Hornbill": "Bucerotidae",
    "Horned lizard": "Phrynosoma",
    "Hornet": "Vespa",
    "Horseradish": "Armoracia rusticana",
    "Horseshoe bat": "Rhinolophidae",
    "Horseshoe crab": "Limulidae",
    "Hoverfly": "Syrphidae",
    "Howler monkey": "Alouatta",
    "Huayangosaurus": "Huayangosaurus",
    "Humboldt squid": "Dosidicus gigas",
    "Hummingbird": "Trochilidae",
    "Hummingbird hawk-moth": "Macroglossum stellatarum",
    "Humpback whale": "Megaptera novaeangliae",
    "Huntsman spider": "Sparassidae",
    "Hyacinth": "Hyacinthus",
    "Hyacinth macaw": "Anodorhynchus hyacinthinus",
    "Hydrangea": "Hydrangea",
    "Hyena": "Hyaenidae",
    "Hypsilophodon": "Hypsilophodon",
    "Iberian lynx": "Lynx pardinus",
    "Ibis": "Threskiornithinae",
    "Iceberg lettuce": "Lactuca sativa var. capitata",
    "Ichthyosaurus": "Ichthyosaurus",
    "Iguana": "Iguana",
    "Iguanodon": "Iguanodon",
    "Impala": "Aepyceros melampus",
    "Impatiens": "Impatiens",
    "Indian rhinoceros": "Rhinoceros unicornis",
    "Indri": "Indri indri",
    "Iris (plant)": "Iris",
    "Ixora": "Ixora",
    "Jabuticaba": "Plinia cauliflora",
    "Jacamar": "Galbulidae",
    "Jacaranda": "Jacaranda",
    "Jackdaw": "Coloeus",
    "Jackfruit": "Artocarpus heterophyllus",
    "Jaguar": "Panthera onca",
    "Jaguarundi": "Puma yagouaroundi",
    "Jalapeño": "Capsicum annuum ‘Jalapeño’",
    "Japanese giant salamander": "Andrias japonicus",
    "Japanese macaque": "Macaca fuscata",
    "Japanese spider crab": "Macrocheira kaempferi",
    "Jasmine": "Jasminum",
    "Javan rhinoceros": "Rhinoceros sondaicus",
    "Jujube": "Ziziphus jujuba",
    "Jumping spider": "Salticidae",
    "Juniper": "Juniperus",
    "Kalanchoe": "Kalanchoe",
    "Kea": "Nestor notabilis",
    "Kelp": "Laminariales",
    "Kentrosaurus": "Kentrosaurus",
    "King cobra": "Ophiophagus hannah",
    "King crab": "Lithodidae",
    "King penguin": "Aptenodytes patagonicus",
    "King vulture": "Sarcoramphus papa",
    "Kingfisher": "Alcedinidae",
    "Kinkajou": "Potos flavus",
    "Kit fox": "Vulpes macrotis",
    "Kiwi (bird)": "Apteryx",
    "Koala": "Phascolarctos cinereus",
    "Kohlrabi": "Brassica oleracea var. gongylodes",
    "Komodo dragon": "Varanus komodoensis",
    "Kookaburra": "Dacelo",
    "Krill": "Euphausiacea",
    "Kronosaurus": "Kronosaurus",
    "Kumquat": "citrus fruit",
    "Lambeosaurus": "Lambeosaurus",
    "Lantana": "Lantana",
    "Lanternfish": "Myctophidae",
    "Larch": "Larix",
    "Leafhopper": "Cicadellidae",
    "Leafy seadragon": "Phycodurus eques",
    "Leatherback sea turtle": "Dermochelys coriacea",
    "Lemon": "Citrus × limon",
    "Lemur": "Lemuroidea",
    "Lentil": "Lens culinaris",
    "Leopard": "Panthera pardus",
    "Leopard gecko": "Eublepharis macularius",
    "Leopard seal": "Hydrurga leptonyx",
    "Leopard shark": "Triakis semifasciata",
    "Lettuce": "Lactuca sativa",
    "Lima bean": "Phaseolus lunatus",
    "Lion": "Panthera leo",
    "Lion's mane jellyfish": "Cyanea capillata",
    "Lionfish": "Pterois",
    "Liopleurodon": "Liopleurodon",
    "Lithops": "Lithops",
    "Liverwort": "Marchantiophyta",
    "Lobster": "Nephropidae",
    "Loggerhead sea turtle": "Caretta caretta",
    "Long-eared owl": "Asio otus",
    "Longan": "Dimocarpus longan",
    "Longhorn beetle": "Cerambycidae",
    "Loon": "Gavia",
    "Loquat": "Eriobotrya japonica",
    "Lovebird": "Agapornis",
    "Luffa": "Luffa",
    "Luna moth": "Actias luna",
    "Lupinus": "Lupinus",
    "Lychee": "Litchi chinensis",
    "Lynx": "Lynx",
    "Macaroni penguin": "Eudyptes chrysolophus",
    "Magnolia": "Magnolia",
    "Mahi-mahi": "Coryphaena hippurus",
    "Maiasaura": "Maiasaura",
    "Mamenchisaurus": "Mamenchisaurus",
    "Mammillaria": "Mammillaria",
    "Manakin": "Pipridae",
    "Manatee": "Trichechus",
    "Manchineel": "Hippomane mancinella",
    "Mandarin orange": "Citrus reticulata",
    "Mandrill": "Mandrillus sphinx",
    "Maned wolf": "Chrysocyon brachyurus",
    "Mangosteen": "Garcinia mangostana",
    "Manta ray": "Manta",
    "Mantella": "Mantella",
    "Mantis shrimp": "Stomatopoda",
    "Maple": "Acer",
    "Marbled newt": "Triturus marmoratus",
    "Margay": "Leopardus wiedii",
    "Marine iguana": "Amblyrhynchus cristatus",
    "Marjoram": "Origanum majorana",
    "Markhor": "Capra falconeri",
    "Marmot": "Marmota",
    "Martial eagle": "Polemaetus bellicosus",
    "Mason bee": "Osmia",
    "Mata mata": "Chelus fimbriatus",
    "Matsutake": "Tricholoma matsutake",
    "Meerkat": "Suricata suricatta",
    "Megalania": "Varanus priscus",
    "Megalodon": "Carcharocles megalodon",
    "Megalosaurus": "Megalosaurus",
    "Megamouth shark": "Megachasma pelagios",
    "Merlin (bird)": "Falco columbarius",
    "Mexican beaded lizard": "Heloderma horridum",
    "Microraptor": "Microraptor",
    "Midwife toad": "Alytes",
    "Milk snake": "Lampropeltis triangulum",
    "Millipede": "Diplopoda",
    "Mimic octopus": "Thaumoctopus mimicus",
    "Mimosa pudica": "Mimosa pudica",
    "Mink": "Lutreola",
    "Mizuna": "Brassica rapa subsp. nipposinica",
    "Mole cricket": "Gryllotalpidae",
    "Monarch butterfly": "Danaus plexippus",
    "Mongoose": "Herpestidae",
    "Monitor lizard": "Varanus",
    "Monstera": "Monstera",
    "Moose": "Alces alces",
    "Moray eel": "Muraenidae",
    "Mosasaurus": "Mosasaurus",
    "Motmot": "Momotidae",
    "Mouflon": "Ovis gmelini",
    "Mudskipper": "Oxudercinae",
    "Muntjac": "Muntiacus",
    "Muscari": "Muscari",
    "Muttaburrasaurus": "Muttaburrasaurus",
    "Narwhal": "Monodon monoceros",
    "Natterjack toad": "Epidalea calamita",
    "Nautilus": "Nautilidae",
    "Nepenthes": "Nepenthes",
    "Nigersaurus": "Nigersaurus taqueti",
    "Nile crocodile": "Crocodylus niloticus",
    "Nile monitor": "Varanus niloticus",
    "Nodosaurus": "Nodosaurus",
    "Northern saw-whet owl": "Aegolius acadicus",
    "Nudibranch": "Nudibranchia",
    "Numbat": "Myrmecobius fasciatus",
    "Nurse shark": "Ginglymostoma cirratum",
    "Nuthatch": "Sitta",
    "Nyala": "Tragelaphus angasii",
    "Oak": "Quercus",
    "Oarfish": "Regalecidae",
    "Ocelot": "Leopardus pardalis",
    "Octopus": "Octopoda",
    "Okapi": "Okapia johnstoni",
    "Okra": "Abelmoschus esculentus",
    "Olive": "Olea europaea",
    "Olm": "Proteus anguinus",
    "Onion": "Allium cepa",
    "Opossum": "Didelphidae",
    "Opuntia": "Opuntia",
    "Orangutan": "Pongo",
    "Orca": "Orcinus orca",
    "Orchid": "Orchidaceae",
    "Oregano": "Origanum vulgare",
    "Oriental fire-bellied toad": "Bombina orientalis",
    "Oryx": "Oryx",
    "Oscar (fish)": "Astronotus ocellatus",
    "Osprey": "Pandion haliaetus",
    "Ostrich": "Struthio",
    "Otter": "Lutrinae",
    "Oviraptor": "Oviraptor",
    "Owl butterfly": "Caligo",
    "Oystercatcher": "Haematopus",
    "Pachycephalosaurus": "Pachycephalosaurus",
    "Pachyphytum": "Pachyphytum",
    "Pachyrhinosaurus": "Pachyrhinosaurus",
    "Painted turtle": "Chrysemys picta",
    "Pallas's cat": "Otocolobus manul",
    "Palmate newt": "Lissotriton helveticus",
    "Pangolin": "Pholidota",
    "Pansy": "Viola ×wittrockiana",
    "Papaya": "Carica papaya",
    "Parasaurolophus": "Parasaurolophus",
    "Parrot": "Psittaciformes",
    "Parrotfish": "Scaridae",
    "Parsley": "Petroselinum crispum",
    "Parsnip": "Pastinaca sativa",
    "Patagotitan": "Patagotitan",
    "Pea": "Pisum sativum",
    "Peach": "Prunus persica",
    "Pear": "Pyrus",
    "Pelican": "Pelecanus",
    "Peony": "Paeonia",
    "Peperomia": "Peperomia",
    "Peppered moth": "Biston betularia",
    "Peregrine falcon": "Falco peregrinus",
    "Pereskia": "Pereskia",
    "Petunia": "Petunia",
    "Peyote": "Lophophora williamsii",
    "Philippine eagle": "Pithecophaga jefferyi",
    "Philodendron": "Philodendron",
    "Phlox": "Phlox",
    "Pika": "Ochotona",
    "Pilea peperomioides": "Pilea peperomioides",
    "Pill millipede": "Oniscomorpha",
    "Pilot whale": "Globicephala",
    "Pine": "Pinus",
    "Pineapple": "Ananas comosus",
    "Pipefish": "Syngnathinae",
    "Pipit": "Anthus",
    "Pit viper": "Crotalinae",
    "Planthopper": "Fulgoroidea",
    "Platypus": "Ornithorhynchus anatinus",
    "Plover": "Charadriinae",
    "Plumeria": "Plumeria",
    "Poison dart frog": "Dendrobatidae",
    "Polacanthus": "Polacanthus",
    "Polar bear": "Ursus maritimus",
    "Pomegranate": "Punica granatum",
    "Pomelo": "Citrus maxima",
    "Portuguese man o' war": "Physalia physalis",
    "Potato": "Solanum tuberosum",
    "Prairie dog": "Cynomys",
    "Proboscis monkey": "Nasalis larvatus",
    "Pronghorn": "Antilocapra americana",
    "Protea": "Protea",
    "Protoceratops": "Protoceratops",
    "Pseudoscorpion": "Pseudoscorpiones",
    "Psittacosaurus": "Psittacosaurus",
    "Pteranodon": "Pteranodon",
    "Pterodactylus": "Pterodactylus",
    "Pudu": "Pudu",
    "Puff adder": "Bitis arietans",
    "Puffin": "Fratercula",
    "Purple frog": "Nasikabatrachus sahyadrensis",
    "Quetzalcoatlus": "Quetzalcoatlus",
    "Quince": "Cydonia oblonga",
    "Quokka": "Setonix brachyurus",
    "Raccoon": "Procyon lotor",
    "Radish": "Raphanus sativus",
    "Rafflesia": "Rafflesia",
    "Rainbow boa": "Epicrates cenchria",
    "Rambutan": "Nephelium lappaceum",
    "Ranunculus": "Ranunculus",
    "Rapini": "Brassica rapa subsp. sylvestris",
    "Razorbill": "Alca torda",
    "Rebutia": "Rebutia",
    "Red deer": "Cervus elaphus",
    "Red fox": "Vulpes vulpes",
    "Red kite": "Milvus milvus",
    "Red panda": "Ailurus fulgens",
    "Red squirrel": "Sciurus vulgaris",
    "Red-backed salamander": "Plethodon cinereus",
    "Red-eared slider": "Trachemys scripta elegans",
    "Red-footed tortoise": "Chelonoidis carbonaria",
    "Red-tailed hawk": "Buteo jamaicensis",
    "Redcurrant": "Ribes rubrum",
    "Remora": "Echeneidae",
    "Reticulated python": "Python reticulatus",
    "Rhamphorhynchus": "Rhamphorhynchus",
    "Rhododendron": "Rhododendron",
    "Rhubarb": "Rheum rhabarbarum",
    "Right whale": "Eubalaena",
    "Ring-tailed lemur": "Lemur catta",
    "Roadrunner": "Geococcyx",
    "Roe deer": "Capreolus capreolus",
    "Romaine lettuce": "Lactuca sativa var. longifolia",
    "Roridula": "Roridula",
    "Rose": "Rosa",
    "Rosemary": "Salvia rosmarinus",
    "Rowan": "Sorbus subg. Sorbus",
    "Russell's viper": "Daboia russelii",
    "Rutabaga": "Brassica napus rapifera",
    "Sable antelope": "Hippotragus niger",
    "Saguaro": "Carnegiea gigantea",
    "Saiga antelope": "Saiga tatarica",
    "Sailfish": "Istiophorus",
    "Saltasaurus": "Saltasaurus",
    "Saltwater crocodile": "Crocodylus porosus",
    "Salvia": "Salvia",
    "Sambar deer": "Rusa unicolor",
    "Sand cat": "Felis margarita",
    "Sand dollar": "Clypeasteroida",
    "Sandpiper": "Scolopacidae",
    "Sarcosuchus": "Sarcosuchus",
    "Sargassum": "Sargassum",
    "Sarracenia": "Sarracenia",
    "Sassafras": "Sassafras",
    "Savoy cabbage": "Brassica oleracea var. sabauda",
    "Sawfish": "Pristidae",
    "Scallop": "Pectinidae",
    "Scarlet macaw": "Ara macao",
    "Schefflera": "Schefflera",
    "Scilla": "Scilla",
    "Scorpion": "Scorpiones",
    "Screech owl": "Megascops",
    "Sea anemone": "Actiniaria",
    "Sea buckthorn": "Hippophae rhamnoides",
    "Sea cucumber": "Holothuroidea",
    "Sea lion": "Otariinae",
    "Sea otter": "Enhydra lutris",
    "Sea pen": "Pennatulacea",
    "Sea turtle": "Chelonioidea",
    "Sea urchin": "Echinoidea",
    "Seahorse": "Hippocampus",
    "Sedum": "Sedum",
    "Sei whale": "Balaenoptera borealis",
    "Selaginella": "Selaginella",
    "Sempervivum": "Sempervivum",
    "Senecio": "Senecio",
    "Serval": "Leptailurus serval",
    "Shallot": "Allium ascalonicum",
    "Shiitake": "Lentinula edodes",
    "Short-eared owl": "Asio flammeus",
    "Shrike": "Laniidae",
    "Sifaka": "Propithecus",
    "Silverfish": "Lepisma saccharina",
    "Skua": "Stercorariidae",
    "Sloth": "Folivora",
    "Sloth bear": "Melursus ursinus",
    "Slow loris": "Nycticebus",
    "Smilodon": "Smilodon",
    "Smooth newt": "Lissotriton vulgaris",
    "Snow leopard": "Panthera uncia",
    "Snow pea": "Pisum sativum var. macrocarpum",
    "Snowy owl": "Bubo scandiacus",
    "Sorrel": "Rumex acetosa",
    "Soursop": "Annona muricata",
    "Spanish moss": "Tillandsia usneoides",
    "Spectacled bear": "Tremarctos ornatus",
    "Spectacled caiman": "Caiman crocodilus",
    "Spectacled owl": "Pulsatrix perspicillata",
    "Sperm whale": "Physeter macrocephalus",
    "Sphagnum": "Sphagnum",
    "Spider monkey": "Ateles",
    "Spinach": "Spinacia oleracea",
    "Spinosaurus": "Spinosaurus",
    "Spoonbill": "Platalea",
    "Spotted salamander": "Ambystoma maculatum",
    "Spring peeper": "Pseudacris crucifer",
    "Spring salamander": "Gyrinophilus porphyriticus",
    "Springbok": "Antidorcas marsupialis",
    "Spruce": "Picea",
    "Stag beetle": "Lucanidae",
    "Staghorn coral": "Acropora cervicornis",
    "Stapelia": "Stapelia",
    "Starfish": "Asteroidea",
    "Starling": "Sturnidae",
    "Stegosaurus": "Stegosaurus",
    "Steller's sea eagle": "Haliaeetus pelagicus",
    "Stingray": "Myliobatoidei",
    "Stoat": "Mustela erminea",
    "Stork": "Ciconiidae",
    "Strawberry": "Fragaria × ananassa",
    "Stygimoloch": "Stygimoloch",
    "Styracosaurus": "Styracosaurus",
    "Sugar glider": "Petaurus breviceps",
    "Sulphur-crested cockatoo": "Cacatua galerita",
    "Sumatran rhinoceros": "Dicerorhinus sumatrensis",
    "Sun bear": "Helarctos malayanus",
    "Sun conure": "Aratinga solstitialis",
    "Sunbird": "Nectariniidae",
    "Sunda clouded leopard": "Neofelis diardi",
    "Swallow": "Hirundinidae",
    "Swallowtail butterfly": "Papilionidae",
    "Swan": "Cygnus",
    "Sweet pea": "Lathyrus odoratus",
    "Sweet potato": "Ipomoea batatas",
    "Swordfish": "Xiphias gladius",
    "Taipan": "Oxyuranus",
    "Tamarind": "Tamarindus indica",
    "Tanager": "Thraupidae",
    "Tangerine": "Citrus ×tangerina",
    "Tapir": "Tapiridae",
    "Tarantula": "Theraphosidae",
    "Taro": "Colocasia esculenta",
    "Tarpon": "Megalops",
    "Tarragon": "Artemisia dracunculus",
    "Tarsier": "Tarsiidae",
    "Tasmanian devil": "Sarcophilus harrisii",
    "Tawny frogmouth": "Podargus strigoides",
    "Tawny owl": "Strix aluco",
    "Teak": "Tectona grandis",
    "Tenontosaurus": "Tenontosaurus",
    "Tern": "Sterninae",
    "Therizinosaurus": "Therizinosaurus",
    "Thornback ray": "Raja clavata",
    "Thorny devil": "Moloch horridus",
    "Thresher shark": "Alopias",
    "Tick": "Ixodida",
    "Tiger": "Panthera tigris",
    "Tiger beetle": "Cicindelinae",
    "Tiger salamander": "Ambystoma tigrinum",
    "Tiger shark": "Galeocerdo cuvier",
    "Tillandsia": "Tillandsia",
    "Titan arum": "Amorphophallus titanum",
    "Titan beetle": "Titanus giganteus",
    "Titanosaurus": "Titanosaurus",
    "Tokay gecko": "Gekko gecko",
    "Tomatillo": "Physalis philadelphica",
    "Tomato": "Solanum lycopersicum",
    "Tomato frog": "Dyscophus",
    "Topi": "Damaliscus lunatus jimela",
    "Toucan": "Ramphastidae",
    "Tradescantia": "Tradescantia",
    "Tragopan": "Tragopan",
    "Tree-kangaroo": "Dendrolagus",
    "Treecreeper": "Certhiidae",
    "Triceratops": "Triceratops",
    "Triggerfish": "Balistidae",
    "Trogon": "Trogonidae",
    "Tuatara": "Sphenodon",
    "Tulip": "Tulipa",
    "Tuna": "Thunnini",
    "Turaco": "Musophagidae",
    "Turkey (bird)": "Meleagris",
    "Turkey vulture": "Cathartes aura",
    "Turmeric": "Curcuma longa",
    "Tyrannosaurus": "Tyrannosaurus",
    "Utahraptor": "Utahraptor",
    "Vampire bat": "Desmodontinae",
    "Velociraptor": "Velociraptor",
    "Velvet ant": "Mutillidae",
    "Venus flytrap": "Dionaea muscipula",
    "Verbena": "Verbena",
    "Verreaux's eagle": "Aquila verreauxii",
    "Vervet monkey": "Chlorocebus pygerythrus",
    "Victoria amazonica": "Victoria amazonica",
    "Viperfish": "Chauliodus",
    "Vireo": "Vireonidae",
    "Wagtail": "Motacilla",
    "Wallace's flying frog": "Rhacophorus nigropalmatus",
    "Walrus": "Odobenus rosmarus",
    "Wasabi": "Eutrema japonicum",
    "Water buffalo": "Bubalus bubalis",
    "Waterbuck": "Kobus ellipsiprymnus",
    "Watercress": "Nasturtium officinale",
    "Watermelon": "Citrullus lanatus",
    "Waxwing": "Bombycilla",
    "Weasel": "Mustela",
    "Weaver ant": "Oecophylla",
    "Wedge-tailed eagle": "Aquila audax",
    "Weevil": "Curculionoidea",
    "Welwitschia": "Welwitschia mirabilis",
    "Whale louse": "Cyamidae",
    "Whale shark": "Rhincodon typus",
    "Whirligig beetle": "Gyrinidae",
    "White rhinoceros": "Ceratotherium simum",
    "White-tailed eagle": "Haliaeetus albicilla",
    "Whitetip reef shark": "Triaenodon obesus",
    "Wildebeest": "Connochaetes",
    "Willow": "Salix",
    "Wisteria": "Wisteria",
    "Wobbegong": "Orectolobidae",
    "Wolf": "Canis lupus",
    "Wolf spider": "Lycosidae",
    "Wolverine": "Gulo gulo",
    "Wombat": "Vombatidae",
    "Wood frog": "Lithobates sylvaticus",
    "Woodlouse": "Oniscidea",
    "Woodpecker": "Picidae",
    "Woolly mammoth": "Mammuthus primigenius",
    "Wrasse": "Labridae",
    "Wren": "Troglodytidae",
    "Yak": "Bos grunniens",
    "Yucca": "Yucca",
    "Yuzu": "Citrus ×junos",
    "Zebra": "Hippotigris",
    "Zinnia": "Zinnia",
    "Zucchini": "Cucurbita pepo var. cylindrica",
}
