SOLAR_SYSTEM = [
    # Planets
    "Mercury (planet)",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    # Dwarf planets
    "Pluto",
    "Ceres (dwarf planet)",
    "Eris (dwarf planet)",
    "Haumea",
    "Makemake",
    # Moons
    "Moon",
    "Io (moon)",
    "Europa (moon)",
    "Ganymede (moon)",
    "Callisto (moon)",
    "Titan (moon)",
    "Enceladus",
    "Triton (moon)",
    "Charon (moon)",
    "Phobos (moon)",
    "Deimos (moon)",
    "Miranda (moon)",
    "Mimas (moon)",
    # Sun
    "Sun",
    # Comets
    "Halley's Comet",
    "Comet Hale–Bopp",
    "Comet Hyakutake",
    "Comet McNaught",
    "Comet NEOWISE",
    "Comet Lovejoy",
    "Comet West",
    # Asteroids & small bodies
    "Asteroid belt",
    "Ceres (dwarf planet)",
    "Vesta (asteroid)",
    "Bennu (asteroid)",
    "Ryugu (asteroid)",
    "Kuiper belt",
    "Oort cloud",
    # Solar system phenomena
    "Solar eclipse",
    "Lunar eclipse",
    "Aurora",
    "Solar flare",
    "Meteor shower",
    # Famous solar system features
    "Olympus Mons",
    "Valles Marineris",
    "Great Red Spot",
    "Rings of Saturn",
    "Van Allen radiation belt",
    # Spacecraft & missions
    "International Space Station",
    "Hubble Space Telescope",
    "James Webb Space Telescope",
    "Voyager 1",
    "Apollo 11",
    "Mars rover",
]

DEEP_SPACE = [
    # Stars
    "Sirius",
    "Betelgeuse",
    "Rigel",
    "Polaris",
    "Alpha Centauri",
    "Proxima Centauri",
    "Vega",
    "Antares",
    "Aldebaran",
    "Canopus",
    "Arcturus",
    "Deneb",
    "Altair",
    "Spica",
    "Fomalhaut",
    "Eta Carinae",
    # Nebulae
    "Orion Nebula",
    "Eagle Nebula",
    "Crab Nebula",
    "Pillars of Creation",
    "Ring Nebula",
    "Helix Nebula",
    "Horsehead Nebula",
    "Cat's Eye Nebula",
    "Lagoon Nebula",
    "Carina Nebula",
    "Tarantula Nebula",
    "Veil Nebula",
    "Rosette Nebula",
    "Butterfly Nebula",
    "Boomerang Nebula",
    "Owl Nebula",
    "Eskimo Nebula",
    "Red Square Nebula",
    # Galaxies
    "Milky Way",
    "Andromeda Galaxy",
    "Triangulum Galaxy",
    "Whirlpool Galaxy",
    "Sombrero Galaxy",
    "Pinwheel Galaxy",
    "Cartwheel Galaxy",
    "Centaurus A",
    "Large Magellanic Cloud",
    "Small Magellanic Cloud",
    "Messier 87",
    "NGC 1300",
    "Antennae Galaxies",
    # Star clusters
    "Pleiades",
    "Hyades (star cluster)",
    "Omega Centauri",
    "Globular cluster",
    "Hercules Cluster",
    # Phenomena
    "Black hole",
    "Supernova",
    "Pulsar",
    "Quasar",
    "Neutron star",
    "White dwarf",
    "Red giant",
    # Famous objects
    "Hubble Deep Field",
    "Pale Blue Dot",
    "Sagittarius A*",
    "Cygnus X-1",
]

ALL = SOLAR_SYSTEM + DEEP_SPACE

LOCATIONS = {
    # Planets
    "Mercury (planet)": "Solar System",
    "Venus": "Solar System",
    "Earth": "Solar System",
    "Mars": "Solar System",
    "Jupiter": "Solar System",
    "Saturn": "Solar System",
    "Uranus": "Solar System",
    "Neptune": "Solar System",
    # Dwarf planets
    "Pluto": "Kuiper belt",
    "Ceres (dwarf planet)": "Asteroid belt",
    "Eris (dwarf planet)": "Scattered disc",
    "Haumea": "Kuiper belt",
    "Makemake": "Kuiper belt",
    # Moons
    "Moon": "Earth",
    "Io (moon)": "Jupiter",
    "Europa (moon)": "Jupiter",
    "Ganymede (moon)": "Jupiter",
    "Callisto (moon)": "Jupiter",
    "Titan (moon)": "Saturn",
    "Enceladus": "Saturn",
    "Triton (moon)": "Neptune",
    "Charon (moon)": "Pluto",
    "Phobos (moon)": "Mars",
    "Deimos (moon)": "Mars",
    "Miranda (moon)": "Uranus",
    "Mimas (moon)": "Saturn",
    # Stars
    "Sun": "Solar System",
    "Sirius": "Canis Major",
    "Betelgeuse": "Orion",
    "Rigel": "Orion",
    "Polaris": "Ursa Minor",
    "Alpha Centauri": "Centaurus",
    "Proxima Centauri": "Centaurus",
    "Vega": "Lyra",
    "Antares": "Scorpius",
    "Aldebaran": "Taurus",
    "Canopus": "Carina",
    "Arcturus": "Boötes",
    "Deneb": "Cygnus",
    "Altair": "Aquila",
    "Spica": "Virgo",
    "Fomalhaut": "Piscis Austrinus",
    "Eta Carinae": "Carina",
    # Nebulae
    "Orion Nebula": "Orion, 1,344 ly",
    "Eagle Nebula": "Serpens, 7,000 ly",
    "Crab Nebula": "Taurus, 6,500 ly",
    "Pillars of Creation": "Serpens, 7,000 ly",
    "Ring Nebula": "Lyra, 2,283 ly",
    "Helix Nebula": "Aquarius, 655 ly",
    "Horsehead Nebula": "Orion, 1,375 ly",
    "Cat's Eye Nebula": "Draco, 3,300 ly",
    "Lagoon Nebula": "Sagittarius, 5,200 ly",
    "Carina Nebula": "Carina, 8,500 ly",
    "Tarantula Nebula": "LMC, 160,000 ly",
    "Veil Nebula": "Cygnus, 2,400 ly",
    "Rosette Nebula": "Monoceros, 5,000 ly",
    "Butterfly Nebula": "Scorpius, 3,800 ly",
    "Boomerang Nebula": "Centaurus, 5,000 ly",
    "Owl Nebula": "Ursa Major, 2,030 ly",
    "Eskimo Nebula": "Gemini, 6,500 ly",
    "Red Square Nebula": "Serpens, 5,000 ly",
    # Galaxies
    "Milky Way": "Our galaxy",
    "Andromeda Galaxy": "2.5 million ly",
    "Triangulum Galaxy": "2.7 million ly",
    "Whirlpool Galaxy": "23 million ly",
    "Sombrero Galaxy": "29 million ly",
    "Pinwheel Galaxy": "21 million ly",
    "Cartwheel Galaxy": "500 million ly",
    "Centaurus A": "13 million ly",
    "Large Magellanic Cloud": "160,000 ly",
    "Small Magellanic Cloud": "200,000 ly",
    "Messier 87": "53 million ly",
    "NGC 1300": "69 million ly",
    "Antennae Galaxies": "45 million ly",
    # Star clusters
    "Pleiades": "Taurus, 444 ly",
    "Hyades (star cluster)": "Taurus, 153 ly",
    "Omega Centauri": "Centaurus, 17,090 ly",
    # Comets
    "Halley's Comet": "75-year orbit",
    "Comet Hale–Bopp": "Seen 1997",
    "Comet Hyakutake": "Seen 1996",
    "Comet McNaught": "Seen 2007",
    "Comet NEOWISE": "Seen 2020",
    "Comet Lovejoy": "Seen 2011",
    "Comet West": "Seen 1976",
    # Phenomena
    "Black hole": "Throughout universe",
    "Supernova": "Stellar explosion",
    "Pulsar": "Rotating neutron star",
    "Quasar": "Active galactic nucleus",
    "Neutron star": "Stellar remnant",
    "White dwarf": "Stellar remnant",
    "Red giant": "Stellar evolution",
    "Solar eclipse": "Earth",
    "Lunar eclipse": "Earth",
    "Aurora": "Earth's poles",
    "Solar flare": "Sun",
    "Meteor shower": "Earth's atmosphere",
    # Famous objects
    "Hubble Deep Field": "Deep space",
    "Pale Blue Dot": "Earth from 6 billion km",
    "Sagittarius A*": "Milky Way center",
    "Cygnus X-1": "Cygnus, 6,070 ly",
    "Olympus Mons": "Mars",
    "Valles Marineris": "Mars",
    "Great Red Spot": "Jupiter",
    "Rings of Saturn": "Saturn",
    # Spacecraft
    "International Space Station": "Low Earth orbit",
    "Hubble Space Telescope": "Low Earth orbit",
    "James Webb Space Telescope": "L2 point",
    "Voyager 1": "Interstellar space",
    "Apollo 11": "Moon, 1969",
    "Mars rover": "Mars",
}
