"""Generate memi/categories/_periodic_data.py from the mendeleev package.

Dev-only — run from the repo root:

    uv run --with mendeleev python scripts/gen_periodic_table.py
"""

import pathlib

from mendeleev import element

OUT = pathlib.Path(__file__).resolve().parent.parent / "memi" / "categories" / "_periodic_data.py"

lines = [
    '"""Generated by scripts/gen_periodic_table.py — do not edit by hand."""',
    "",
    "ELEMENTS = {",
]
for z in range(1, 119):
    e = element(z)
    lines.append(
        f'    "{e.name}": {{"symbol": "{e.symbol}", "number": {e.atomic_number}, '
        f'"category": "{e.series}"}},'
    )
lines.append("}")

OUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {sum(1 for line in lines if line.startswith('    '))} elements to {OUT}")
